### PR TITLE
Converted /network/nodes API to Java

### LINKED ISSUE #12304: Convert `/network/nodes` API to Java
### Problem

As a maintainer, I'd like to convert `/api/v1/network/nodes` to Java to ease maintenance and improve performance.

## Phase One

Phase one implements the new API in Java with it disabled by default. Thorough testing is conducted to verify no
regressions are introduced.

### REST Java

- [ ] Controller, services, repositories, etc. implemented in rest-java
- [ ] Use Jooq for any dynamic SQL, repositories for any static queries
- [ ] New `Cache-Control` entry added to `rest-java/src/main/resources/application.yml`
- [ ] Controller integration tests added with equivalent or better coverage to existing rest spec tests.

### REST

- [ ] `REST_JAVA_INCLUDE` and `testFiles` updated in `rest/build.gradle.kts`
- [ ] All existing rest spec tests passing against rewritten Java endpoint

### Acceptance

- [ ] Acceptance tests updated to use `MirrorNodeClient.callConvertedRestEndpoint()`
- [ ] Passing acceptance tests

### Performance

- [ ] K6 tests for endpoint duplicated in rest-java folder
- [ ] K6 tests passing with equal to or greater than rps as older API

### Deployment

- [ ] New rest-java route added to `docker-compose.yml` haproxy config
- [ ] New `routes.<apiName>` property added to `charts/hedera-mirror-rest-java/values.yaml` and defaulted to `false`
- [ ] New route added to ingress conditional on routes property
- [ ] New route added to gateway conditional on routes property
- [ ] Enable route in integration environment before tagging and test it
- [ ] Enable route in previewnet and watch metrics/logs
- [ ] Enable route in both testnet clusters for a release and watch metrics/logs

## Phase Two

Phase two enables the new route by default so that it rolls out to mainnet for the first time. The legacy code is kept
until we're confident there are no regressions.

- [ ] Enable route by default in Ingress and Gateway
- [ ] Update JavaScript monitor to use REST Java URL for route
- [ ] Remove temporary enablement in previewnet and testnet so that default is used

## Phase Three

Phase three cleans up the legacy code and configuration so that only the rest-java route remains.

- [ ] Delete JavaScript code and tests
- [ ] Delete `Cache-Control` entry in rest config
- [ ] Delete duplicate rest k6 test
- [ ] Remove `routes.<apiName>` property in chart and its use in ingress and gateway
- [ ] Acceptance tests updated to use `MirrorNodeClient.callRestJavaEndpoint()`
- [ ] `REST_JAVA_INCLUDE` and `testFiles` updated to remove route and specs in `rest/build.gradle.kts`

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by ashumahajan**
**Description**:
Converted /network/nodes API to Java

**Related issue(s)**:

Fixes #12304 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 1]
```diff
@@ -77,9 +89,12 @@ final class NetworkController {
     private final ExchangeRateMapper exchangeRateMapper;
     private final FeeScheduleMapper feeScheduleMapper;
     private final FileService fileService;
+    private final LinkFactory linkFactory;
     private final NetworkService networkService;
     private final NetworkStakeMapper networkStakeMapper;
     private final NetworkSupplyMapper networkSupplyMapper;
+    private final org.hiero.mirror.restjava.mapper.NetworkNodeMapper networkNodeMapper;
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: Package name can be omitted and import can be used instead.

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 2]
```diff
@@ -139,4 +154,21 @@ ResponseEntity<?> getSupply(
 
         return ResponseEntity.ok(networkSupplyMapper.map(networkSupply));
     }
+
+    @GetMapping("/nodes")
+    org.hiero.mirror.rest.model.NetworkNodesResponse getNodes(@RequestParameter NetworkNodeRequest request) {
+        var networkNodeDtos = networkService.getNetworkNodes(request);
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: Local variables can be made final.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+import org.hiero.mirror.rest.model.ServiceEndpoint;
+import org.hiero.mirror.rest.model.TimestampRange;
+import org.hiero.mirror.rest.model.TimestampRangeNullable;
+import org.hiero.mirror.restjava.repository.NetworkNodeRow;
+
+/**
+ * Network node DTO representing network node API result.
+ */
+@Data
+public class NetworkNodeDto {
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Removing Dto from the class name would probably be better, similarly to the other DTO classes in the package.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+ * Spring Data JPA creates a proxy implementation that maps query column aliases to these getter methods.
+ */
+public interface NetworkNodeRow {
+    String getDescription();
+
+    String getMemo();
+
+    Long getNodeId();
+
+    String getNodeAccountId();
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: This should probably be of type Long.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+
+            // Direct mappings
+            dto.setAdminKey(row.getAdminKey());
+            dto.setDeclineReward(row.getDeclineReward());
+            dto.setDescription(row.getDescription());
+            dto.setFileId(row.getFileId());
+            dto.setMaxStake(row.getMaxStake());
+            dto.setMemo(row.getMemo());
+            dto.setMinStake(row.getMinStake());
+            dto.setNodeAccountId(row.getNodeAccountId());
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: I think this should look like  (given getNodeAccountId() is changed to return Long)

`dto.setNodeAccountId(EntityId.of(0, 0, row.getNodeAccountId()).toString());`


Otherwise the Java API wouldn't match the JS one.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java [hunk 6]
```diff
@@ -0,0 +1,102 @@
...
+                      AND (:minNodeId = 0 OR abe.node_id >= :minNodeId)
+                      -- Apply upper bound range filter if provided
+                      AND (:maxNodeId = 9223372036854775807 OR abe.node_id <= :maxNodeId)
+                    order by
+                      case when :orderDirection = 'ASC' then abe.node_id end asc,
+                      case when :orderDirection = 'DESC' then abe.node_id end desc
+                    limit :limit
+                    """, nativeQuery = true)
+    List<NetworkNodeRow> findNetworkNodes(
+            @Param("fileId") Long fileId,
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java]: Param annotations can be removed, since the values are matching the parameter names.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 7]
```diff
@@ -0,0 +1,92 @@
...
+            dto.setNodeId(row.getNodeId());
+            dto.setPublicKey(row.getPublicKey());
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: We probably want to prefix the public key with 0x like in the JS api, so we may be looking for something like:

```
final var publicKey = row.getPublicKey();
dto.setPublicKey(publicKey != null ? "0x" + publicKey : null);
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 8]
```diff
@@ -0,0 +1,92 @@
...
+            dto.setRewardRateStart(row.getRewardRateStart());
+            dto.setStake(row.getStake());
+            dto.setStakeNotRewarded(row.getStakeNotRewarded());
+            dto.setStakeRewarded(row.getStakeRewarded());
+
+            // Convert nodeCertHash from byte[] to String
+            var nodeCertHash = row.getNodeCertHash();
+            dto.setNodeCertHash(nodeCertHash != null ? new String(nodeCertHash) : null);
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: nodeCertHash is bytea in the DB, respectively byte[] should be better suited as its type in the DTO. In such case the above row should probably look like this:
`dto.setNodeCertHash(nodeCertHash != null ? "0x" + Hex.encodeHexString(nodeCertHash) : "0x");`

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeData.java [hunk 9]
```diff
@@ -0,0 +1,92 @@
...
+    private Boolean declineReward;
+    private String description;
+    private String fileId;
+    private ServiceEndpoint grpcProxyEndpoint;
+    private Long maxStake;
+    private String memo;
+    private Long minStake;
+    private String nodeAccountId;
+    private Long nodeId;
+    private String nodeCertHash;
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeData.java]: nodeCertHash is bytea in the DB, respectively byte[] should be better suited as its type in the DTO

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+            dto.setNodeAccountId(row.getNodeAccountId());
+            dto.setNodeId(row.getNodeId());
+            dto.setPublicKey(row.getPublicKey());
+            dto.setRewardRateStart(row.getRewardRateStart());
+            dto.setStake(row.getStake());
+            dto.setStakeNotRewarded(row.getStakeNotRewarded());
+            dto.setStakeRewarded(row.getStakeRewarded());
+
+            // Convert nodeCertHash from byte[] to String
+            var nodeCertHash = row.getNodeCertHash();
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Local variables can be final.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 11]
```diff
@@ -0,0 +1,92 @@
...
+            // Parse service endpoints JSON
+            var serviceEndpointsJson = row.getServiceEndpoints();
+            var serviceEndpoints =
+                    objectMapper.readValue(serviceEndpointsJson, new TypeReference<List<ServiceEndpoint>>() {});
+            dto.setServiceEndpoints(serviceEndpoints);
+
+            // Set timestamp range from address book start/end timestamps
+            if (row.getStartConsensusTimestamp() != null) {
+                var timestamp = new TimestampRange();
+                timestamp.setFrom(String.valueOf(row.getStartConsensusTimestamp()));
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: This will result in different response in the Java API compared to the JS one so we are probably looking for `timestamp.setFrom(DomainUtils.toTimestamp(row.getStartConsensusTimestamp())); `

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 12]
```diff
@@ -0,0 +1,92 @@
...
+                if (row.getEndConsensusTimestamp() != null) {
+                    timestamp.setTo(String.valueOf(row.getEndConsensusTimestamp()));
```
Comment (sdimitrov9) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: `timestamp.setTo(DomainUtils.toTimestamp(row.getEndConsensusTimestamp()));`

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java (hunk 4 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: This is string only "node_account_id": "0.0.3"

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java (hunk 3 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: NetworkNode clashes with same name in rest.model. This caused clashes at code level. I renamed in to NetworkNodeData

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java (hunk 4 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: getNodeAccountId is String based on query coalesce(n.account_id, abe.node_account_id) as nodeAccountId,

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java (hunk 3 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: I removed NetworkNodeDto completely

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java (hunk 5 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Added the logic in mapper

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java (hunk 7 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: In Mapper class

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java [hunk 13]
```diff
@@ -45,10 +45,17 @@ public <T> Links create(List<T> items, Pageable pageable, Function<T, Map<String
...
+        // If nextLink is null, it means the pagination range would be empty - no more results
+        if (nextLink == null) {
+            return DEFAULT_LINKS;
+        }
+
         servletRequestAttributes.getResponse().setHeader(HttpHeaders.LINK, LINK_HEADER.formatted(nextLink));
         return new Links().next(nextLink);
     }
 
+    @org.jspecify.annotations.Nullable
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java:145]: Don't think this method can return null. Can remove.

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java [hunk 14]
```diff
@@ -45,10 +45,17 @@ public <T> Links create(List<T> items, Pageable pageable, Function<T, Map<String
         var request = servletRequestAttributes.getRequest();
         var lastItem = Objects.requireNonNull(CollectionUtils.lastElement(items));
         var nextLink = createNextLink(lastItem, pageable, extractor, request);
+
+        // If nextLink is null, it means the pagination range would be empty - no more results
+        if (nextLink == null) {
+            return DEFAULT_LINKS;
+        }
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java:139]: Don't think createNextLink can be null so this is dead code. If I'm wrong, please add a test to `LinkFactoryTest`.

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java [hunk 15]
```diff
@@ -0,0 +1,210 @@
...
+import org.springframework.web.method.support.HandlerMethodArgumentResolver;
+import org.springframework.web.method.support.ModelAndViewContainer;
+import org.springframework.web.servlet.HandlerMapping;
+
+/**
+ * Resolves controller method parameters annotated with {@link RequestParameter}. Uses Spring's WebDataBinder for
+ * binding and validation, exactly like Spring's built-in @RequestParam resolver. The only difference: annotations are
+ * on DTO fields instead of method parameters.
+ */
+@Component
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java]: Prefer jakarta `@Named` here and every where else.

File: rest/__tests__/specs/network/nodes/invalid-params.json [hunk 16]
```diff
@@ -3,25 +3,58 @@
...
+            "message": "Invalid parameter: file.id"
+          },
+          {
+            "data": null,
+            "detail": null,
+            "message": "Invalid parameter: node.id"
+          },
+          {
+            "data": null,
+            "detail": null,
```
Comment (steven-sheehy) [inline rest/__tests__/specs/network/nodes/invalid-params.json]: I thought the `JacksonConfiguration` change would omit these null fields?

File: rest/__tests__/specs/network/nodes/node-range.json [hunk 17]
```diff
@@ -252,77 +252,152 @@
...
+                "to": "172800.000000000"
+              },
+              "timestamp": {
+                "from": "187654.000123457",
+                "to": null
+              }
             }
+          ],
+          "links": {
+            "next": "/api/v1/network/nodes?node.id=gt:4&node.id=lt:5&limit=2&order=desc"
```
Comment (steven-sheehy) [inline rest/__tests__/specs/network/nodes/node-range.json]: Why would the js and java response differ for this test case?

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java [hunk 18]
```diff
@@ -0,0 +1,67 @@
...
+
+package org.hiero.mirror.restjava.repository;
+
+import org.springframework.lang.Nullable;
+
+/**
+ * Interface-based projection representing a network node query result row from the database. Spring Data JPA creates a
+ * proxy implementation that maps query column aliases to these getter methods.
+ */
+public interface NetworkNodeRow {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: Prefer not to use the low level term `row` in code. Maybe just `NetworkNode` or `NetworkNodeDto`.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java [hunk 19]
```diff
@@ -0,0 +1,67 @@
...
+    @Nullable
+    Long getStakeNotRewarded();
+
+    @Nullable
+    Long getStakeRewarded();
+
+    @Nullable
+    Long getStakingPeriod();
+
+    String getServiceEndpoints();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: We should return this as a list of objects so we don't have to do json mapping in the mapper layer. Either as existing `ServiceEndpoint` or some interface projection.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java [hunk 20]
```diff
@@ -0,0 +1,67 @@
...
+    @Nullable
+    String getNodeAccountId();
+
+    @Nullable
+    byte[] getNodeCertHash();
+
+    @Nullable
+    String getPublicKey();
+
+    Long getFileId();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: Prefer we sort all the method names

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkService.java [hunk 21]
```diff
@@ -2,11 +2,16 @@
...
+import org.hiero.mirror.restjava.dto.NetworkNodeRequest;
 import org.hiero.mirror.restjava.dto.NetworkSupply;
+import org.hiero.mirror.restjava.repository.NetworkNodeRow;
 
 public interface NetworkService {
     NetworkStake getLatestNetworkStake();
 
     NetworkSupply getSupply(Bound timestamp);
+
+    List<NetworkNodeRow> getNetworkNodes(NetworkNodeRequest request);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkService.java]: nit: sort by method name

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/EntityIdEqualParameter.java [hunk 22]
```diff
@@ -0,0 +1,64 @@
...
+import org.apache.commons.lang3.StringUtils;
+import org.hiero.mirror.common.CommonProperties;
+import org.hiero.mirror.common.domain.entity.EntityId;
+import org.hiero.mirror.restjava.common.RangeOperator;
+
+/**
+ * Entity ID parameter that only accepts equality values (no range operators like gt:, lt:).
+ * Accepts formats: "100", "0.0.100", "eq:200", "eq:0.0.200"
+ */
+public record EntityIdEqualParameter(EntityId entityId) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/parameter/EntityIdEqualParameter.java]: I don't think we need this class. We can use `EntityIdRangeParameter` and throw an error in controller if operator != EQ

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 23]
```diff
@@ -0,0 +1,156 @@
...
+import org.hiero.mirror.rest.model.TimestampRange;
+import org.hiero.mirror.rest.model.TimestampRangeNullable;
+import org.hiero.mirror.restjava.repository.NetworkNodeRow;
+import org.mapstruct.Mapper;
+import org.springframework.beans.factory.annotation.Autowired;
+
+@Mapper(config = MapperConfiguration.class)
+public abstract class NetworkNodeMapper {
+
+    @Autowired
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Prefer jakarta `@Resource` here and in every other file in diff.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 24]
```diff
@@ -0,0 +1,156 @@
...
+import org.hiero.mirror.rest.model.NetworkNodesResponse;
+import org.hiero.mirror.rest.model.ServiceEndpoint;
+import org.hiero.mirror.rest.model.TimestampRange;
+import org.hiero.mirror.rest.model.TimestampRangeNullable;
+import org.hiero.mirror.restjava.repository.NetworkNodeRow;
+import org.mapstruct.Mapper;
+import org.springframework.beans.factory.annotation.Autowired;
+
+@Mapper(config = MapperConfiguration.class)
+public abstract class NetworkNodeMapper {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: This should be an interface, not a class. Add `uses = CommonMapper.class` to `@Mapper` to get access to it.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 25]
```diff
@@ -0,0 +1,156 @@
...
+
+            // Direct mappings
+            node.setDeclineReward(row.getDeclineReward());
+            node.setDescription(row.getDescription());
+            node.setMemo(row.getMemo());
+            node.setNodeId(row.getNodeId());
+            node.setRewardRateStart(row.getRewardRateStart());
+            node.setStake(row.getStake());
+            node.setStakeRewarded(row.getStakeRewarded());
+
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: I think you misunderstood the purpose of mapstruct. By default it handles all obvious mappings and you only need to implement the corner cases.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java (hunk 24 above)
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: This should extend CollectionMapper. We should only call mapper once, not one per item in list.

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java [hunk 26]
```diff
@@ -89,6 +91,20 @@ private ResponseEntity<Object> typeMismatch(final TypeMismatchException e, final
         return handleExceptionInternal(e, problem, null, BAD_REQUEST, request);
     }
 
+    @ExceptionHandler(org.springframework.validation.BindException.class)
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]: nit: why fully qualified name here?

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 27]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+
+    private Pair<Long, Long> combineOverlappingRanges(Collection<EntityIdRangeParameter> rangeSet) {
+
+        if (rangeSet.isEmpty()) {
+            return Pair.of(0L, Long.MAX_VALUE);
+        }
+
+        // Calculate lower bound: min of (value+1 for GT, value for GTE)
+        Long lowerBound = rangeSet.stream()
+                .filter(x -> x.operator() == RangeOperator.GTE || x.operator() == RangeOperator.GT)
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: This seems wrong. `node.id=gte:10&node.id=gte:20 ` should yield lower bound 20, but the current logic would yield 10

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 28]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                .map(x -> x.operator() == RangeOperator.GT ? x.value() + 1 : x.value())
+                .min(Comparator.naturalOrder())
+                .orElse(0L);
+
+        // Calculate upper bound: max of (value-1 for LT, value for LTE)
+        Long upperBound = rangeSet.stream()
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Same comment as above

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RestJavaQueryParam.java [hunk 29]
```diff
@@ -0,0 +1,45 @@
...
+    /**
+     * Whether the parameter is required. Default is true, leading to an exception being thrown if the parameter is
+     * missing.
+     */
+    boolean required() default true;
+
+    /**
+     * The default value to use as a fallback when the request parameter is not provided or empty.
+     */
+    String defaultValue() default "\n\t\t\n\t\t\n\ue000\ue001\ue002\n\t\t\t\t\n"; // ValueConstants.DEFAULT_NONE
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/RestJavaQueryParam.java]: Can you clarify this value here? Shouldn't this just reference the constant directly?

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java [hunk 30]
```diff
@@ -0,0 +1,244 @@
...
+    /**
+     * Validates that all query parameters in the request are known (defined in the DTO). Adds errors to the binding
+     * result for any unknown parameters.
+     */
+    private void addUnknownParameterErrors(
+            BindingMetadata metadata, NativeWebRequest webRequest, WebDataBinder binder) {
+        Map<String, String[]> allParams = webRequest.getParameterMap();
+
+        // Collect all known parameter names from annotations
+        var knownParams = metadata.queryParams.values().stream()
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java]: shouldn't we use the field name if no value or name set?

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java [hunk 31]
```diff
@@ -0,0 +1,244 @@
...
+    // Cache reflection metadata to avoid repeated lookups - same pattern as Spring
+    private final Map<Class<?>, BindingMetadata> metadataCache = new ConcurrentHashMap<>();
+
+    @Override
+    public boolean supportsParameter(MethodParameter parameter) {
+        return parameter.hasParameterAnnotation(RequestParameter.class);
+    }
+
+    @Override
+    public Object resolveArgument(
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java:46]: Shouldn't this be written in a way that allows request fields to be private?

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 32]
```diff
@@ -0,0 +1,156 @@
...
+    /**
+     * Maps staking period timestamp to TimestampRangeNullable.
+     */
+    protected TimestampRangeNullable mapStakingPeriod(Long stakingPeriod) {
+        if (stakingPeriod == null) {
+            return null;
+        }
+
+        // Add 1 nanosecond to staking period start
+        long stakingPeriodStart = stakingPeriod + 1L;
```
Comment (jnels124) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: nit: final var for local vars

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 33]
```diff
@@ -0,0 +1,40 @@
...
+    public static final int DEFAULT_LIMIT = 10;
+
+    @RestJavaQueryParam(name = "file.id", required = false, defaultValue = "0.0.102")
+    EntityIdEqualParameter fileId;
+
+    @RestJavaQueryParam(name = "node.id", required = false)
+    List<EntityIdRangeParameter> nodeId;
+
+    @RestJavaQueryParam(name = "limit", defaultValue = "10")
+    int limit;
```
Comment (martingeorgiev1) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: missing `@Positive/@Min(1)` compared to the [HooksController](https://github.com/hiero-ledger/hiero-mirror-node/blob/main/rest-java/src/main/java/org/hiero/mirror/restjava/controller/HooksController.java) pattern, also you can add validation tests for 0 and -1

File: rest/__tests__/specs/network/nodes/invalid-params.json [hunk 34]
```diff
@@ -3,25 +3,58 @@
   "setup": {},
   "url": "/api/v1/network/nodes?file.id=a&node.id=b&limit=c&order=d&token.id=2",
```
Comment (martingeorgiev1) [inline rest/__tests__/specs/network/nodes/invalid-params.json:4]: For `limit` You can add a tests for 0 and -1

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java (hunk 13 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java:145]: This was added based on one of the rest spec testcases, to which you had mentioned below about response being different in java. I had removed the code that returned null when range is not applicable. Either i remove this and keep the change in reponse for for rest spec test. Please suggest.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 35]
```diff
@@ -0,0 +1,99 @@
...
+import org.hiero.mirror.rest.model.TimestampRangeNullable;
+import org.hiero.mirror.restjava.dto.NetworkNodeDto;
+import org.mapstruct.Mapper;
+import org.mapstruct.Mapping;
+import org.mapstruct.Named;
+
+@Mapper(config = MapperConfiguration.class, uses = CommonMapper.class)
+public interface NetworkNodeMapper extends CollectionMapper<NetworkNodeDto, NetworkNode> {
+
+    CommonMapper COMMON_MAPPER = new CommonMapperImpl();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Can remove. It's already present in the generated impl class. Should not need to call statically.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 36]
```diff
@@ -0,0 +1,99 @@
...
+    @Mapping(target = "stakingPeriod", expression = "java(mapStakingPeriod(row.getStakingPeriod()))")
+    @Mapping(target = "timestamp", expression = "java(mapTimestampRange(row))")
+    NetworkNode map(NetworkNodeDto row);
+
+    default NetworkNodesResponse mapToResponse(List<NetworkNode> nodes, Links links) {
+        var response = new NetworkNodesResponse();
+        response.setNodes(nodes);
+        response.setLinks(links);
+        return response;
+    }
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Can remove. We usually just use mapper for the list and create the wrapper response inside the controller.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 37]
```diff
@@ -0,0 +1,99 @@
...
+
+    @Named("mapKey")
+    default Key mapKey(byte[] bytes) {
+        return COMMON_MAPPER.mapKey(bytes);
+    }
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Remove as this should be mapped automatically.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 38]
```diff
@@ -0,0 +1,41 @@
...
+import java.util.List;
+import lombok.Data;
+import org.hiero.mirror.restjava.common.RestJavaQueryParam;
+import org.hiero.mirror.restjava.parameter.EntityIdRangeParameter;
+import org.springframework.data.domain.Sort.Direction;
+
+/**
+ * Network nodes request DTO for testing annotation framework.
+ */
+@Data
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java:24]: This should be an immutable class like the other request classes. Either `@Value` or record is fine as long as they have builder.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 39]
```diff
@@ -0,0 +1,41 @@
...
+public class NetworkNodeRequest {
+
+    public static final int MAX_LIMIT = 25;
+    public static final int DEFAULT_LIMIT = 10;
+
+    @RestJavaQueryParam(name = "file.id", required = false, defaultValue = "0.0.102")
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: This default won't work for non-zero realm. Maybe just use "102" and add common properties shard and realm if missing

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 40]
```diff
@@ -0,0 +1,41 @@
...
+    private EntityIdRangeParameter fileId;
+
+    @RestJavaQueryParam(name = "node.id", required = false)
+    private List<EntityIdRangeParameter> nodeId;
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: Should be default of `List.of()` to avoid null checks

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java [hunk 41]
```diff
@@ -64,7 +67,8 @@ class GenericControllerAdvice extends ResponseEntityExceptionHandler {
     private final RestJavaProperties properties;
 
     @Bean
-    @SuppressWarnings("java:S5122") // Make sure that enabling CORS is safe here.
+    @SuppressWarnings("java:S5122")
+    // Make sure that enabling CORS is safe here.
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]: Can remove comment. Sounds like a todo but it's safe here.

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 42]
```diff
@@ -47,6 +59,9 @@
 final class NetworkController {
 
     static final FeeEstimateResponse FEE_ESTIMATE_RESPONSE;
+    private static final String NODE_ID = "node.id";
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: Should go to Constants class.

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 43]
```diff
@@ -77,9 +92,12 @@ final class NetworkController {
     private final ExchangeRateMapper exchangeRateMapper;
     private final FeeScheduleMapper feeScheduleMapper;
     private final FileService fileService;
+    private final LinkFactory linkFactory;
     private final NetworkService networkService;
     private final NetworkStakeMapper networkStakeMapper;
     private final NetworkSupplyMapper networkSupplyMapper;
+    private final NetworkNodeMapper networkNodeMapper;
+    private final CommonMapper commonMapper;
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: unused

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 44]
```diff
@@ -139,4 +157,26 @@ ResponseEntity<?> getSupply(
...
         return ResponseEntity.ok(networkSupplyMapper.map(networkSupply));
     }
+
+    @GetMapping("/nodes")
+    ResponseEntity<NetworkNodesResponse> getNodes(@RequestParameter NetworkNodeRequest request) {
+        if (request.getFileId().operator() != RangeOperator.EQ) {
+            throw new IllegalArgumentException("Only equality operator is supported for file.id");
+        }
+        final var networkNodeRows = networkService.getNetworkNodes(request);
+        // Use effective limit (capped at MAX_LIMIT) to match rest module behavior
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: Remove comment as rest module won't be around forever

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 45]
```diff
@@ -139,4 +157,26 @@ ResponseEntity<?> getSupply(
...
+        final var limit = request.getEffectiveLimit();
+
+        // Map database rows to response model
+        final var networkNodes = networkNodeMapper.map(networkNodeRows);
+
+        // Create pagination links using LinkFactory
+        // Matches Node.js behavior: generate next link when results.size() == limit (optimistic pagination)
+        // No link when results.size() < limit (definitively at the end)
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: The comments are unnecessary. This comment is more appropriate in a javadoc on the LinkFactory itself.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 46]
```diff
@@ -0,0 +1,98 @@
...
+
+import com.fasterxml.jackson.core.type.TypeReference;
+import com.fasterxml.jackson.databind.ObjectMapper;
+import java.io.IOException;
+import java.util.List;
+import org.hiero.mirror.rest.model.ServiceEndpoint;
+import org.jspecify.annotations.Nullable;
+
+/**
+ * Interface-based projection representing a network node query result from the database. Spring Data JPA creates a
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Is it actually a proxy based implementation or runtime generated? If former, can we use a record instead to avoid the proxy penalty?

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 47]
```diff
@@ -0,0 +1,98 @@
...
+
+    @Nullable
+    default ServiceEndpoint getGrpcProxyEndpoint() {
+        var json = getGrpcProxyEndpointJson();
+        if (json == null || json.isEmpty()) return null;
+        try {
+            return Parser.MAPPER.readValue(json, ServiceEndpoint.class);
+        } catch (IOException e) {
+            throw new RuntimeException("Failed to parse grpc proxy endpoint", e);
+        }
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: We should not do json parsing in any layer. We should let Spring or jackson convert it for us by using `@JsonDeserialize` or some spring converter.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 48]
```diff
@@ -0,0 +1,98 @@
...
+    Long getMaxStake();
+
+    @Nullable
+    String getMemo();
+
+    @Nullable
+    Long getMinStake();
+
+    @Nullable
+    String getNodeAccountId();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Should be either a Long or an EntityId

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 49]
```diff
@@ -0,0 +1,98 @@
...
+    @Nullable
+    String getPublicKey();
+
+    @Nullable
+    Long getRewardRateStart();
+
+    default List<ServiceEndpoint> getServiceEndpoints() {
+        try {
+            return Parser.MAPPER.readValue(getServiceEndpointsJson(), Parser.SERVICE_ENDPOINT_LIST_TYPE);
+        } catch (IOException e) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Use annotation to convert

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 50]
```diff
@@ -0,0 +1,99 @@
...
+            return null;
+        }
+        return new TimestampRange()
+                .from(COMMON_MAPPER.mapTimestamp(row.getStartConsensusTimestamp()))
+                .to(COMMON_MAPPER.mapTimestamp(row.getEndConsensusTimestamp()));
+    }
+
+    @Named("mapStake")
+    default Long mapStake(Long stake) {
+        if (stake == null || stake == -1L) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Change db query to case or coalesce these and remove this func.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 51]
```diff
@@ -0,0 +1,99 @@
...
+    @Named("addHexPrefix")
+    default String addHexPrefix(String hexData) {
+        if (hexData == null || hexData.isEmpty()) {
+            return "0x";
+        }
+        return hexData.startsWith("0x") ? hexData : "0x" + hexData;
+    }
+
+    @Named("mapNodeCertHash")
+    default String mapNodeCertHash(byte[] nodeCertHash) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: This method not needed

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 52]
```diff
@@ -0,0 +1,99 @@
...
+
+    CommonMapper COMMON_MAPPER = new CommonMapperImpl();
+
+    @Override
+    @Mapping(target = "adminKey", qualifiedByName = "mapKey")
+    @Mapping(target = "fileId", qualifiedByName = "mapEntityId")
+    @Mapping(
+            target = "nodeAccountId",
+            expression =
+                    "java(row.getNodeAccountId() != null ? mapEntityId(Long.parseLong(row.getNodeAccountId())) : null)")
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: These should not be necessary

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 53]
```diff
@@ -0,0 +1,99 @@
...
+    @Mapping(target = "publicKey", qualifiedByName = "addHexPrefix")
+    @Mapping(target = "nodeCertHash", qualifiedByName = "mapNodeCertHash")
+    @Mapping(target = "maxStake", qualifiedByName = "mapStake")
+    @Mapping(target = "minStake", qualifiedByName = "mapStake")
+    @Mapping(target = "stakeNotRewarded", qualifiedByName = "mapStake")
+    @Mapping(target = "stakingPeriod", expression = "java(mapStakingPeriod(row.getStakingPeriod()))")
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Doesn't this work?
```suggestion
    @Mapping(target = "stakingPeriod", qualifiedByName = "mapStakingPeriod")
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java [hunk 54]
```diff
@@ -0,0 +1,93 @@
...
+            left join latest_node_stake ns
+              on abe.node_id = ns.node_id
+            left join node_info n
+              on abe.node_id = n.node_id
+            where (coalesce(array_length(:nodeIds, 1), 0) = 0 or abe.node_id = any(:nodeIds))
+              and abe.node_id >= :minNodeId
+              and abe.node_id <= :maxNodeId
+            order by
+              case when :orderDirection = 'ASC' then abe.node_id end asc,
+              case when :orderDirection = 'DESC' then abe.node_id end desc
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java:100]: Should be able to directly pass a `Pageable` and omit order by and limit. See `HookStorageChangeRepository.findByKeyBetweenAndTimestampBetween`

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 55]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+        // Extract order direction from request
+        // Query for exact limit (not limit+1) to match Node.js behavior
+        // Pagination link is generated when results.size() == limit (optimistic pagination)
+        final var orderDirection = request.getOrder().name();
+
+        return networkNodeRepository.findNetworkNodes(
+                fileId, equalitySet, rangeBounds.getLeft(), rangeBounds.getRight(), orderDirection, limit);
+    }
+
+    private Pair<Long, Long> combineOverlappingRanges(Collection<EntityIdRangeParameter> rangeSet) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Please never use `Pair` as it's a code smell. You can just use a `Range` here.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java [hunk 56]
```diff
@@ -0,0 +1,93 @@
...
+            limit :limit
+            """, nativeQuery = true)
+    List<NetworkNodeDto> findNetworkNodes(
+            Long fileId, Long[] nodeIds, long minNodeId, long maxNodeId, String orderDirection, int limit);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java:104]:
```suggestion
            Long fileId, Collection<Long> nodeIds, long minNodeId, long maxNodeId, Pageable pageable);
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 57]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+        final var nodeIdParams = request.getNodeId();
+
+        // Create two sets: equality operators and range operators
+        // Use empty array when there are no parameters - SQL handles this with array_length check
+        final var equalitySet = (nodeIdParams == null || nodeIdParams.isEmpty())
+                ? new Long[0]
+                : nodeIdParams.stream()
+                        .filter(x -> RangeOperator.EQ.equals(x.operator()))
+                        .map(EntityIdRangeParameter::value)
+                        .toArray(Long[]::new);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Use HashSet to collapse duplicates and avoid mutable arrays.

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 58]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+        final var fileId = request.getFileId().value();
+        // Use effective limit (capped at MAX_LIMIT) to match rest module behavior
+        final var limit = request.getEffectiveLimit();
+        final var nodeIdParams = request.getNodeId();
+
+        // Create two sets: equality operators and range operators
+        // Use empty array when there are no parameters - SQL handles this with array_length check
+        final var equalitySet = (nodeIdParams == null || nodeIdParams.isEmpty())
+                ? new Long[0]
+                : nodeIdParams.stream()
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Set nodeId as an empty list to avoid null checks here and below.
```suggestion
        final var nodeIds = nodeIdParams.stream()
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 59]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                        .filter(x -> RangeOperator.EQ.equals(x.operator()))
+                        .map(EntityIdRangeParameter::value)
+                        .toArray(Long[]::new);
+
+        final var rangeSet = (nodeIdParams == null || nodeIdParams.isEmpty())
+                ? List.<EntityIdRangeParameter>of()
+                : nodeIdParams.stream()
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]:
```suggestion
        final var rangeSet = nodeIdParams.stream()
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 60]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                        .filter(x -> !RangeOperator.EQ.equals(x.operator()))
+                        .collect(Collectors.toSet());
+
+        // Always calculate range bounds (defaults to 0L and Long.MAX_VALUE if no range parameters)
+        var rangeBounds = combineOverlappingRanges(rangeSet);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: If there exists both eq and ranges then we need to validate them to ensure they have overlap otherwise reject. See HookServiceImpl

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameter.java [hunk 61]
```diff
@@ -0,0 +1,39 @@
+// SPDX-License-Identifier: Apache-2.0
+
+package org.hiero.mirror.restjava.common;
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameter.java]: This should be in parameter package

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RestJavaPathParam.java [hunk 62]
```diff
@@ -0,0 +1,39 @@
+// SPDX-License-Identifier: Apache-2.0
+
+package org.hiero.mirror.restjava.common;
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/RestJavaPathParam.java]: parameter package and other related request param classes currently in common.

File: rest-java/src/main/java/org/hiero/mirror/restjava/config/WebMvcConfiguration.java [hunk 63]
```diff
@@ -0,0 +1,25 @@
...
+import org.springframework.context.annotation.Configuration;
+import org.springframework.web.method.support.HandlerMethodArgumentResolver;
+import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
+
+/**
+ * Spring MVC configuration to register custom argument resolvers.
+ */
+@Configuration
+@RequiredArgsConstructor
+public class WebMvcConfiguration implements WebMvcConfigurer {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/config/WebMvcConfiguration.java]:
```suggestion
@Configuration(proxyBeanMethods = false)
@RequiredArgsConstructor
final class WebMvcConfiguration implements WebMvcConfigurer {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java [hunk 64]
```diff
@@ -89,6 +93,20 @@ private ResponseEntity<Object> typeMismatch(final TypeMismatchException e, final
...
 
+    @ExceptionHandler(BindException.class)
+    private ResponseEntity<Object> bindException(
+            final org.springframework.validation.BindException e, final WebRequest request) {
+        return handleExceptionInternal(e, null, null, BAD_REQUEST, request);
+    }
+
+    @ExceptionHandler(InvalidParameterCountException.class)
+    private ResponseEntity<Object> invalidParameter(final InvalidParameterCountException e, final WebRequest request) {
+        // For InvalidParameterException, use the exception message directly as the error detail
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]: Why do we need this new exception type? Why can't we use IllegalArgumentException which already uses the exception message directly as the error detail.

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 65]
```diff
@@ -71,4 +82,67 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                : nodeIdParams.stream()
+                        .filter(x -> RangeOperator.EQ.equals(x.operator()))
+                        .map(EntityIdRangeParameter::value)
+                        .toArray(Long[]::new);
+
+        final var rangeSet = (nodeIdParams == null || nodeIdParams.isEmpty())
+                ? List.<EntityIdRangeParameter>of()
+                : nodeIdParams.stream()
+                        .filter(x -> !RangeOperator.EQ.equals(x.operator()))
+                        .collect(Collectors.toSet());
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: We loop too many times in this class over the same node ids: once for eq, once for ranges, again over gt* ranges, again over lt* ranges. We should just have a single loop to determine all of this at once. See `HooksController.hooksRequest`.

File: rest-java/src/test/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapperTest.java [hunk 66]
```diff
@@ -0,0 +1,344 @@
...
+import java.util.List;
+import org.hiero.mirror.common.util.DomainUtils;
+import org.hiero.mirror.rest.model.Links;
+import org.hiero.mirror.rest.model.NetworkNode;
+import org.hiero.mirror.rest.model.NetworkNodesResponse;
+import org.hiero.mirror.rest.model.ServiceEndpoint;
+import org.hiero.mirror.restjava.dto.NetworkNodeDto;
+import org.junit.jupiter.api.Test;
+
+class NetworkNodeMapperTest {
```
Comment (steven-sheehy) [inline rest-java/src/test/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapperTest.java]: final

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java [hunk 67]
```diff
@@ -0,0 +1,246 @@
...
+    /**
+     * Get or compute binding metadata for a DTO class. Cached to avoid reflection on every request - same pattern as
+     * Spring's internal caching.
+     */
+    private BindingMetadata getMetadata(Class<?> clazz) {
+        return metadataCache.computeIfAbsent(clazz, c -> {
+            Map<Field, RestJavaQueryParam> queryParams = new LinkedHashMap<>();
+            Map<Field, RestJavaPathParam> pathParams = new LinkedHashMap<>();
+
+            for (Field field : c.getDeclaredFields()) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java]: We should try to use final var for non-primitive fields everywhere in this class.

```suggestion
            for (final var field : c.getDeclaredFields()) {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java [hunk 68]
```diff
@@ -0,0 +1,246 @@
...
+     * for thread safety.
+     */
+    private record BindingMetadata(
+            Map<Field, RestJavaQueryParam> queryParams, Map<Field, RestJavaPathParam> pathParams) {
+
+        BindingMetadata(Map<Field, RestJavaQueryParam> queryParams, Map<Field, RestJavaPathParam> pathParams) {
+            // Make maps unmodifiable for thread safety - preserves LinkedHashMap order
+            this.queryParams = Collections.unmodifiableMap(queryParams);
+            this.pathParams = Collections.unmodifiableMap(pathParams);
+        }
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java]: Be simpler to just wrap the params that you pass in when creating since it's only created in one method in one class.

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java [hunk 69]
```diff
@@ -0,0 +1,246 @@
...
+        // Get cached metadata (computed once per DTO class)
+        BindingMetadata metadata = getMetadata(parameterType);
+
+        // Get path variables from request attributes
+        @SuppressWarnings("unchecked")
+        Map<String, String> pathVariables = (Map<String, String>) webRequest.getAttribute(
+                HandlerMapping.URI_TEMPLATE_VARIABLES_ATTRIBUTE, NativeWebRequest.SCOPE_REQUEST);
+
+        // Create instance using default constructor - same as Spring's @ModelAttribute
+        Object attribute = parameterType.getDeclaredConstructor().newInstance();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java:64]: This class is neat but it means we can't use immutable request DTOs? Or is there a way around this?

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 70]
```diff
@@ -0,0 +1,41 @@
...
+@Data
+public class NetworkNodeRequest {
+
+    public static final int MAX_LIMIT = 25;
+    public static final int DEFAULT_LIMIT = 10;
+
+    @RestJavaQueryParam(name = "file.id", required = false, defaultValue = "0.0.102")
+    private EntityIdRangeParameter fileId;
+
+    @RestJavaQueryParam(name = "node.id", required = false)
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: Should use Constants class for these name fields

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java [hunk 71]
```diff
@@ -0,0 +1,246 @@
...
+        String objectName = parameterType.getSimpleName();
+        WebDataBinder binder = binderFactory.createBinder(webRequest, attribute, objectName);
+        binder.initDirectFieldAccess();
+        binder.bind(propertyValues);
+
+        // Validate - same as Spring's validation
+        binder.validate();
+
+        // Check for unknown query parameters and add to binding result
+        addUnknownParameterErrors(metadata, webRequest, binder);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java]: Do we reject unknown parameters in current rest-java?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java (hunk 51 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: default  commonmapper implementation is not working. Since database stores node_cert_hash as UTF-8 text (e.g., bytes of "a1b2c3d4"), not as raw binary data. This change results in rest test failure.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java (hunk 54 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java:100]: Using pageable is not working with complex query. Spring jpa is incorrectly forming the query check below
`where (coalesce(array_length(?, 1), 0) = 0 or abe.node_id = any(?))
  and abe.node_id >= ?
  and abe.node_id <= ?
, nodeId asc fetch first ? rows only]`

A "," is added before nodeId, which is failing the query.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java (hunk 56 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRepository.java:104]: Using pageable is now working with complex query. Spring jpa is incorrectly forming the query check below
where (coalesce(array_length(?, 1), 0) = 0 or abe.node_id = any(?)) and abe.node_id >= ? and abe.node_id <= ? , nodeId asc fetch first ? rows only]

A "," is added before nodeId, which is failing the query.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java (hunk 38 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java:24]: Since current implementation needs a no-arg constructor and fields (needs to be non-final) are populated post instance creation,  we will need mutable implementation.

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java (hunk 69 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java:64]: Based on the current implementation, we will need mutable request DTOs. I can later look into a way for the annotations to work with immutable dtos

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java (hunk 71 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java]: Yes, that is the current rest implementation. There is a specific test to check it.

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java [hunk 72]
```diff
@@ -61,6 +153,13 @@ private <T> String createNextLink(
 
         addParamMapToQueryParams(paramsMap, paginationParamsMap, order, queryParams);
         addExtractedParamsToQueryParams(sortOrders, paginationParamsMap, order, queryParams);
+
+        // Check if the pagination would create an empty range (e.g., gt:4 AND lt:5 with no values in between)
+        // If so, return null to indicate no more results
+        if (isEmptyRange(queryParams, sortOrders)) {
```
Comment (xin-hedera) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java]: should just pass `primarySort`

```suggestion
        if (isEmptyRange(primarySort, queryParams)) {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java [hunk 73]
```diff
@@ -31,6 +31,91 @@ final class LinkFactoryImpl implements LinkFactory {
...
+        }
+
+        var values = queryParams.get(primaryField);
+        if (values == null || values.isEmpty()) {
+            return false;
+        }
+
+        // Compute the effective range bounds from all query parameters
+        Long lower = null;
+        Long upper = null;
```
Comment (xin-hedera) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java]: initialize with sensible default values


```suggestion
        long lower = Long.MIN_VALUE;
        long upper = Long.MAX_VALUE;
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java [hunk 74]
```diff
@@ -31,6 +31,91 @@ final class LinkFactoryImpl implements LinkFactory {
...
+
+        for (var value : values) {
+            var normalized = value.toLowerCase();
+
+            try {
+                // Extract the numeric value and update bounds
+                if (normalized.startsWith("gt:")) {
+                    long val = Long.parseLong(value.substring(3)) + 1; // gt:4 → gte:5
+                    lower = lower == null ? val : Math.max(lower, val);
```
Comment (xin-hedera) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java]: remove all null checks

```suggestion
                    lower = Math.max(lower, val);
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java [hunk 75]
```diff
@@ -31,6 +31,91 @@ final class LinkFactoryImpl implements LinkFactory {
...
+                    long val = Long.parseLong(value.substring(4));
+                    upper = upper == null ? val : Math.min(upper, val);
+                }
+            } catch (NumberFormatException e) {
+                // Skip invalid values
+            }
+        }
+
+        // If we have both bounds and upper < lower, the range is empty
+        return lower != null && upper != null && upper < lower;
```
Comment (xin-hedera) [inline rest-java/src/main/java/org/hiero/mirror/restjava/common/LinkFactoryImpl.java]:
```suggestion
        return upper < lower;
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java [hunk 76]
```diff
@@ -89,6 +91,12 @@ private ResponseEntity<Object> typeMismatch(final TypeMismatchException e, final
         return handleExceptionInternal(e, problem, null, BAD_REQUEST, request);
     }
 
+    @ExceptionHandler(BindException.class)
+    private ResponseEntity<Object> bindException(
+            final org.springframework.validation.BindException e, final WebRequest request) {
```
Comment (xin-hedera) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]:
```suggestion
            final BindException e, final WebRequest request) {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java [hunk 77]
```diff
@@ -156,25 +164,52 @@ private Error errorResponse(List<? extends MessageSourceResolvable> errors) {
...
 
     private ErrorStatusMessagesInner formatErrorMessage(MessageSourceResolvable error) {
-        var detail = error.getDefaultMessage();
+        var message = error.getDefaultMessage();
 
         if (error instanceof FieldError fieldError) {
-            detail = fieldError.getField() + " field " + fieldError.getDefaultMessage();
+            // Convert field name from camelCase to dot notation (e.g., nodeId -> node.id)
+            var paramName = camelCaseToParameterName(fieldError.getField());
+            message = "Invalid parameter: " + paramName;
```
Comment (xin-hedera) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]: are we overriding the message and throwing away `error.getDefaultMessage()`?

Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]: This is based on the way messages are currently sent as part of error response. Verified using rest spec tests.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java (hunk 51 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: The query could be changed to `decode(node_cert_hash, 'hex')` to avoid this.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java (hunk 52 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: Still there

File: rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java (hunk 67 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/common/RequestParameterArgumentResolver.java]: You only changed the one line, not the entire class as asked.

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java (hunk 71 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java]: I asked about rest-java, not rest. Existing rest-java APIs do not validate unknown query parameters and this new code should match that. We risk cross site scripting attacks by reflecting unknown parameters back to the user.

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 78]
```diff
@@ -71,4 +82,73 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
 
         return firstDay.toLocalDate().atStartOfDay(ZoneOffset.UTC).toEpochSecond() * DomainUtils.NANOS_PER_SECOND;
     }
+
+    @Override
+    public List<NetworkNodeDto> getNetworkNodes(NetworkNodeRequest request) {
+        // fileId has a default value of 102, so it's always present
+        final var fileId = request.getFileId().value();
+        // Use effective limit (capped at MAX_LIMIT) to match rest module behavior
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Remove unnecessary comments as we should stay DRY about default values and prepare for rest module going away.

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java (hunk 65 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: We're still looping too many times. In the initial loop where we parse into eq set and range set we should adjust it to also extract the min and max range. Then we only need one additional loop if eq set not empty to verify overlaps. It should look exactly like:

```java
        final var hookIds = new TreeSet<Long>();
        long lowerBound = 0L;
        long upperBound = MAX_VALUE;

        for (final var hookIdFilter : hookIdFilters) {
            if (hookIdFilter.operator() == RangeOperator.EQ) {
                hookIds.add(hookIdFilter.value());
            } else if (hookIdFilter.hasLowerBound()) {
                lowerBound = Math.max(lowerBound, hookIdFilter.getInclusiveValue());
            } else if (hookIdFilter.hasUpperBound()) {
                upperBound = Math.min(upperBound, hookIdFilter.getInclusiveValue());
            }
        }
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 79]
```diff
@@ -71,4 +82,73 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+            final var idsInRange = equalitySet.stream()
+                    .filter(nodeId -> nodeId >= rangeBounds.getMinimum() && nodeId <= rangeBounds.getMaximum())
+                    .toArray(Long[]::new);
+
+            if (idsInRange.length == 0) {
+                return List.of(); // No overlap between equality and range filters
+            }
+            nodeIds = idsInRange;
+        } else {
+            nodeIds = equalitySet.isEmpty() ? new Long[0] : equalitySet.toArray(Long[]::new);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: We should be consistent and use Set for eq set everywhere. We should not re-allocate any memory if only eq.

File: rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java (hunk 19 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/repository/NetworkNodeRow.java]: Unfortunately JPA's @Convert annotations only work with JPA entities and not with projection

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java (hunk 49 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: Annotation does not work with projection

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java [hunk 80]
```diff
@@ -0,0 +1,34 @@
...
+ * <p>Parameter order matches the SQL SELECT clause order (alphabetically sorted by alias name).
+ */
+public record NetworkNodeDto(
+        byte @Nullable [] adminKey,
+        @Nullable Boolean declineReward,
+        @Nullable String description,
+        @Nullable Long endConsensusTimestamp,
+        @Nullable Long fileId,
+        @Nullable String grpcProxyEndpointJson,
+        @Nullable Long maxStake,
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeDto.java]: The nullables are not needed and too verbose. Can either omit them or add `@NullUnmarked` to class.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 81]
```diff
@@ -0,0 +1,53 @@
...
+    public static final int MAX_LIMIT = 25;
+
+    @RestJavaQueryParam(name = FILE_ID, required = false, defaultValue = "102")
+    private EntityIdRangeParameter fileId;
+
+    @RestJavaQueryParam(name = NODE_ID, required = false)
+    @Builder.Default
+    private List<EntityIdRangeParameter> nodeId = List.of();
+
+    @RestJavaQueryParam(name = LIMIT, defaultValue = "10")
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: Are the defaultValue annotations needed? Can't we just use actual Java defaults for the fields like nodeId?

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java [hunk 82]
```diff
@@ -0,0 +1,53 @@
...
+
+    public static final int DEFAULT_LIMIT = 10;
+    public static final int MAX_LIMIT = 25;
+
+    @RestJavaQueryParam(name = FILE_ID, required = false, defaultValue = "102")
+    private EntityIdRangeParameter fileId;
+
+    @RestJavaQueryParam(name = NODE_ID, required = false)
+    @Builder.Default
+    private List<EntityIdRangeParameter> nodeId = List.of();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]:
```suggestion
    private List<EntityIdRangeParameter> nodeIds = List.of();
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java (hunk 71 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/parameter/RequestParameterArgumentResolver.java]: I will remove the validation and update the rest testcase

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java [hunk 83]
```diff
@@ -0,0 +1,70 @@
...
+    @Mapping(
+            target = "nodeAccountId",
+            expression = "java(row.nodeAccountId() != null ? commonMapper.mapEntityId(row.nodeAccountId()) : null)")
+    @Mapping(target = "nodeCertHash", qualifiedByName = "mapNodeCertHash")
+    @Mapping(
+            target = "grpcProxyEndpoint",
+            expression = "java(StringToServiceEndpointConverter.INSTANCE.convert(row.grpcProxyEndpointJson()))")
+    @Mapping(
+            target = "serviceEndpoints",
+            expression = "java(StringToServiceEndpointListConverter.INSTANCE.convert(row.serviceEndpointsJson()))")
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: There's not really any point to have these in a separate class that we invoke statically. Might as well just have them as a method in the mapper.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java (hunk 51 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: There is an issue with this change. The problem is that in the importer we are inserting byteArray (binary bytes), where we could directly use encode() to get hex. However, the way test data is set up in both DomainBuilder and REST specs, nodeCertHash is stored as "hex-as-ASCII". In integrationDomainOps.js, line 550 defines the default value as a hex string '01d173753810c0aae794ba72d5443c292e9ff962b...', and lines 556-560 show the critical issue: when input is provided (line 559), Buffer.from(hex_string, 'hex') correctly converts to binary bytes, but when using the default (line 560), Buffer.from(hex_string) without the 'hex' parameter stores the hex characters as ASCII bytes. This means the default creates 96 ASCII bytes instead of 48 binary bytes.   
  
Similarly, DomainBuilder uses .nodeCertHash(bytes(96)) which generates random binary bytes. The current mapper implementation works because Java's UTF-8 decoder is lenient—it doesn't throw errors on invalid UTF-8 sequences like PostgreSQL does. This allows the mapper to handle both the hex-as-ASCII format from REST specs and the binary format from DomainBuilder/production. However, if we move this logic to SQL using convert_from(), PostgreSQL will fail with "invalid byte sequence for encoding UTF8" when encountering binary data, which is why the hybrid approach checking length is necessary to support both production (binary) and test (hex-as-ASCII) data formats.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java (hunk 82 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: I am having some issue with the way error is being generated after changing the field name as a rest spec testcase fails for Invalid parameter. I will work on this to make sure change field name change should not impact response error

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java (hunk 81 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: Somehow, without default it is not working. I will have to check the reason.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java (hunk 82 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: Done

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java (hunk 51 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/NetworkNodeMapper.java]: updated

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 84]
```diff
@@ -71,4 +79,53 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                }
+                if (filteredNodeIds.isEmpty()) {
+                    return List.of();
+                }
+                nodeIdArray = filteredNodeIds.toArray(Long[]::new);
+            } else {
+                nodeIdArray = nodeIds.toArray(Long[]::new);
+            }
+        } else {
+            nodeIdArray = new Long[0];
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Why do we need this nodeIdArray? Why doesn't it work with `Collection<Long>` and the existing nodeIds?

File: docker-compose.yml [hunk 85]
```diff
@@ -217,6 +217,7 @@ configs:
         location ~ "^/api/v1/accounts/(\d+\.){0,2}(\d+|(0x)?[A-Fa-f0-9]{40}|(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}|[A-Z2-7]{4,5}|[A-Z2-7]{7,8}))/hooks/(0|[1-9]\d*)/storage$" { proxy_pass http://rest_java_host$$request_uri; }
         location = /api/v1/network/exchangerate { proxy_pass http://rest_java_host$$request_uri; }
         location = /api/v1/network/fees { proxy_pass http://rest_java_host$$request_uri; }
+        location = /api/v1/network/nodes { proxy_pass http://rest_java_host$$request_uri; }
         location = /api/v1/network/stake { proxy_pass http://rest_java_host$$request_uri; }
         location = /api/v1/network/supply { proxy_pass http://rest_java_host$$request_uri; }
```
Comment (steven-sheehy) [inline docker-compose.yml]: We can simplify to be a single line `/api/v1/network/.+`

File: rest/__tests__/specs/network/nodes/invalid-params.json [hunk 86]
```diff
@@ -3,25 +3,53 @@
...
+            "message": "Invalid parameter: node.id"
+          },
+          {
+            "data": null,
+            "detail": null,
+            "message": "Invalid parameter: limit"
+          },
+          {
+            "data": null,
+            "detail": null,
```
Comment (steven-sheehy) [inline rest/__tests__/specs/network/nodes/invalid-params.json]: Why is data and detail null but we have logic to omit null error fields?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java (hunk 84 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: This is because of any clause in repository, which requires array. I will update the query with in clause and use collection instead

File: rest/__tests__/specs/network/nodes/invalid-params.json (hunk 86 above)
Comment (ashumahajan) [reply rest/__tests__/specs/network/nodes/invalid-params.json]: ErrorStatusMessage is generated using OpenAPI generator, which by default adds  @JsonInclude(USE_DEFAULTS) 

To remove it we will need to modify the OpenAPI generator template to not add @JsonInclude(USE_DEFAULTS)

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java (hunk 84 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Which SQL approach is more performant?

Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Arrays use a single bind parameter, which maintains consistent query plans regardless of array size. With Collections and IN clauses, Spring expands them into multiple parameters (IN (?, ?, ?...)), generating different SQL for each size. Thus, I would rather stick with arrays.

Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: ok, can stick with arrays if it provides sql benefits.

File: rest/__tests__/specs/network/nodes/invalid-params.json (hunk 86 above)
Comment (ashumahajan) [reply rest/__tests__/specs/network/nodes/invalid-params.json]: I checked that updating template will require me to download the standrad tempate model for openapi. Instead, I will create a subclass that would not include non-null fields.

File: rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java (hunk 81 above)
Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/dto/NetworkNodeRequest.java]: Its working now

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 87]
```diff
@@ -71,4 +79,53 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                nodeIds.add(nodeIdParam.value());
+            } else if (nodeIdParam.hasLowerBound()) {
+                lowerBound = Math.max(lowerBound, nodeIdParam.getInclusiveValue());
+            } else if (nodeIdParam.hasUpperBound()) {
+                upperBound = Math.min(upperBound, nodeIdParam.getInclusiveValue());
+            }
+        }
+
+        if (lowerBound > upperBound) {
+            throw new IllegalArgumentException("Invalid range for : node.id");
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Existing error messages in the code use the below wording:
```suggestion
            throw new IllegalArgumentException("Invalid range provided for node.id");
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java (hunk 84 above)
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: `new Long[0];` is immutable so can be a static class constant.

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java [hunk 88]
```diff
@@ -71,4 +79,53 @@ private long getFirstDayOfMonth(long timestamp, int monthOffset) {
...
+                        filteredNodeIds.add(nodeId);
+                    }
+                }
+                if (filteredNodeIds.isEmpty()) {
+                    return List.of();
+                }
+                nodeIdArray = filteredNodeIds.toArray(Long[]::new);
+            } else {
+                nodeIdArray = nodeIds.toArray(Long[]::new);
+            }
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Can be simplified:

```suggestion
            nodeIdArray = nodeIds.stream()
                    .filter(nodeId -> nodeId >= lowerBound && nodeId <= upperBound)
                    .mapToLong(Long::longValue)
                    .toArray();

            if (nodeIdArray.length == 0)) {
                return List.of();
            }
```

Comment (ashumahajan) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: lowerBound and upperBound will need to be final to use stream filter. Or I will have to create 2 more final variables

Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/service/NetworkServiceImpl.java]: Two extra final vars is fine. But might be better to do:

```java
final var range = Range.closed(lowerBound, upperBound));
nodeIdArray = nodeIds.stream().filter(range::contains)
```

**Comment by steven-sheehy** [comment]
The acceptance tests are failing. Should fix it if you merge from upstream main on your fork.

**Comment by steven-sheehy** [comment]
Some merge conflicts

**Review by steven-sheehy — APPROVED** [review]
