### PR TITLE
Properly validate gas consumption for contract creates in acceptance tests

### LINKED ISSUE #12154: Acceptance failure in previewnet
### Description

Acceptance Tests fail in previewnet

### Steps to reproduce

Run acceptance tests against previewnet.

Notice failure
```
2025-10-08T23:12:27.783Z ERROR ForkJoinPool-1-worker-3 o.h.m.t.e.a.s.EthereumFeature Scenario failure:
I successfully created a signer account with an EVM address alias
I successfully create contract by Legacy ethereum transaction
the mirror node REST API should return status 200 for the eth contract creation transaction
the mirror node contract results API should return an accurate gas consumed <-
expected: 214864L
 but was: 4200000L
the mirror node contract results opcodes API should return a non-empty response
I successfully call function using EIP-1559 ethereum transaction
the mirror node REST API should return status 200 for the ethereum transaction
the mirror node contract results API should return an accurate gas consumed
the mirror node REST API should verify the ethereum called contract function
the mirror node Rest API should verify the contracts have correct nonce
I successfully call function using EIP-2930 ethereum transaction
the mirror node REST API should return status 200 for the ethereum transaction
the mirror node contract results API should return an accurate gas consumed
the mirror node REST API should verify the ethereum called contract function
 org.opentest4j.AssertionFailedError:
expected: 214864L
 but was: 4200000L
	at org.hiero.mirror.test.e2e.acceptance.steps.AbstractEstimateFeature.verifyGasConsumed(AbstractEstimateFeature.java:210)
	at org.hiero.mirror.test.e2e.acceptance.steps.EthereumFeature.verifyGasConsumedIsCorrect(EthereumFeature.java:138)
	at ✽.the mirror node contract results API should return an accurate gas consumed(classpath:features/contract/ethereum.feature:10)
```

### Additional context

_No response_

### Hedera network

_No response_

### Version

v0.140.0

### Operating system

None

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:
Following HIP-1249, consensus nodes populate gasUsed field including code debit costs and refunds, without refund logic. Currently in mirror node's acceptance tests we validated the gas consumed by a transaction by manually constructing it using sidecars and manually calculated intrinsic gas. After the importer logic switched to assign gasConsumed directly to gasUsed, the way we construct the expected gas in acceptance tests should also change.

This PR reflects this need by adding manually calculated code deposit costs, using contract's runtime bytecode.

**Related issue(s)**:

Fixes #12154 

**Notes for reviewer**:

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java [hunk 1]
```diff
@@ -69,12 +69,19 @@ public void createAccountWithEvmAddressAlias() {
...
 
         gasConsumedSelector = Objects.requireNonNull(mirrorClient
                 .getContractInfo(deployedParentContract.contractId().toEvmAddress())
                 .getBytecode());
+
+        String txId = networkTransactionResponse.getTransactionIdStringNoCheckSum();
+        var contractId = Objects.requireNonNull(
+                        mirrorClient.getTransactions(txId).getTransactions())
+                .getFirst()
+                .getEntityId();
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java]: If this is a create, the `networkTransactionResponse.getReceipt().contractId` should already have the contractId. Same comment elsewhere.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java [hunk 2]
```diff
@@ -43,6 +48,30 @@ abstract class AbstractEstimateFeature extends BaseContractFeature {
     @Autowired
     protected FeatureProperties featureProperties;
 
+    private final Supplier<Boolean> shouldUseCodeDepositCost = Suppliers.memoize(() -> {
+        try {
+            var blocksResponse = mirrorClient.getBlocks(Order.DESC, 1);
+            verifyMirrorTransactionsResponse(mirrorClient, 200);
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java:52]: Why do we need this here? This assumes there's another random call to /api/v1/transactions somewhere not related to us calling blocks API.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java [hunk 3]
```diff
@@ -24,14 +26,17 @@
...
 import org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient;
 import org.hiero.mirror.test.e2e.acceptance.config.FeatureProperties;
+import org.hiero.mirror.test.e2e.acceptance.props.Order;
 import org.hiero.mirror.test.e2e.acceptance.util.ModelBuilder;
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.web.client.HttpClientErrorException;
 
 abstract class AbstractEstimateFeature extends BaseContractFeature {
 
+    private static final int MINOR_HAPI_VERSION_WITHOUT_GAS_REFUND = 67;
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java]: This assumes HIP-1254 won't be delayed later. Should add a temporary property to FeatureProperties that we check.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java [hunk 4]
```diff
@@ -210,6 +245,29 @@ protected void verifyGasConsumed(String txId) {
...
+            totalGasFee = calculateIntrinsicValue(gasConsumedSelector);
+        } catch (DecoderException e) {
+            throw new RuntimeException("Failed to decode hexadecimal string.", e);
+        }
+        var gasConsumed = getGasConsumedByTransactionId(txId);
+        var gasUsed = getGasFromActions(txId);
+        // If there is a nested deploy the gas consumption is already captured in sidecars, so we shouldn't add
+        // additional code deposit
+        var codeDepositCost = !shouldUseCodeDepositCost.get() || hasNestedDeploy ? 0L : getCodeDepositGas(contractId);
+        AssertionsForClassTypes.assertThat(gasConsumed).isEqualTo(gasUsed + codeDepositCost + totalGasFee);
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java]: Use regular Assertions class and static import for assertThat.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java (hunk 2 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java:52]: The block wasn't fetched across several attempts. After adding this verification, it gets fetched on first invocation.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java (hunk 4 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java]: Fixed

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java (hunk 3 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/AbstractEstimateFeature.java]: Added

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java (hunk 1 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java]: Fixed
