### PR TITLE
Use shard and realm properties in web3 API

### LINKED ISSUE #10412: `EntityIdUtils` ignores realm and shard
### Problem

The web3 module incorrectly uses just long entity num in places instead of using shard, realm and num.

### Solution

* Change any method in `EntityIdUtils` to use shard and realm when encoding from an object to/from bytes or numerics
* Remove `BitPackUtils`
* Change `EntityNum` to internally use `EntityId`
* Investigate other areas like `AllowanceId`

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:

**Related issue(s)**:

Fixes #10412 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java [hunk 1]
```diff
@@ -16,32 +17,31 @@
...
-        if (!isValidNum(l)) {
-            return MISSING_NUM;
-        }
-        final var value = codeFromNum(l);
-        return new EntityNum(value);
+        return new EntityNum(EntityId.of(l));
     }
 
     public static EntityNum fromAccountId(final AccountID grpc) {
+        // Should this remain restricted?
```
Comment (jnels124) [inline hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:44]: This function returns true if shard and realm are both zero.

File: hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java [hunk 2]
```diff
@@ -350,6 +383,24 @@ void toEvmAddressContractID() throws Exception {
...
+        var id = TokenID.newBuilder()
+                .setShardNum(entityId.getShard())
+                .setRealmNum(entityId.getRealm())
+                .setTokenNum(entityId.getNum())
+                .build();
+
+        String expected = "000001FF000000000000FFFF0000003FFFFFFFFF";
+        String expectedEmpty = "0000000000000000000000000000000000000000";
+        assertThat(DomainUtils.toEvmAddress(id)).asHexString().isEqualTo(expected);
+        assertThat(DomainUtils.toEvmAddress(AccountID.getDefaultInstance()))
```
Comment (jnels124) [inline hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java:398]: should be `TokenID.getDefaultInstance()`

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java (hunk 1 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:44]: I think we should probably change this to shard/realm from common properties. This is old mono logic that will be deleted after completion of modularized evm.

**Review by kselveliev — DISMISSED** [review]

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java [hunk 3]
```diff
@@ -295,6 +313,14 @@ public static byte[] toEvmAddress(EntityId contractId) {
         return toEvmAddress((int) contractId.getShard(), contractId.getRealm(), contractId.getNum());
     }
 
+    public static byte[] toEvmAddress(long id) {
+        return toEvmAddress(EntityId.of(id));
+    }
+
+    public static byte[] toEvmAddress(long shard, long realm, long num) {
+        return toEvmAddress((int) shard, realm, num);
```
Comment (bilyana-gospodinova) [inline hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java:321]: I have some concerns about casting the `long` directly to an `int`. It seems to me that it would be safer to check if the value would fit into an `int` first in order to prevent some runtime unexpected exceptions. For reference there is a similar check in `EntityId.encode(...)`.

Comment (jnels124) [reply hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java:321]: I will take another look at this. Thanks

File: hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java [hunk 4]
```diff
@@ -332,6 +331,40 @@ void toEvmAddressEntityId() {
...
+    @Test
+    void toEvmAddressAccountId() {
+        var entityId = EntityId.of(Long.MAX_VALUE);
+        var id = AccountID.newBuilder()
+                .setShardNum(entityId.getShard())
+                .setRealmNum(entityId.getRealm())
+                .setAccountNum(entityId.getNum())
+                .build();
+
+        String expected = "000001FF000000000000FFFF0000003FFFFFFFFF";
```
Comment (filev94) [inline hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java:343]: You can create a constant for this variable as it is present at least 3 times

File: hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java [hunk 5]
```diff
@@ -350,6 +383,24 @@ void toEvmAddressContractID() throws Exception {
...
+    void toEvmAddressTokenId() {
+        var entityId = EntityId.of(Long.MAX_VALUE);
+        var id = TokenID.newBuilder()
+                .setShardNum(entityId.getShard())
+                .setRealmNum(entityId.getRealm())
+                .setTokenNum(entityId.getNum())
+                .build();
+
+        String expected = "000001FF000000000000FFFF0000003FFFFFFFFF";
+        String expectedEmpty = "0000000000000000000000000000000000000000";
```
Comment (filev94) [inline hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java:396]: Whenever possible, try to use final var for non-primitives

File: hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java [hunk 6]
```diff
@@ -4,10 +4,7 @@
 
 import static com.hedera.mirror.common.util.CommonUtils.nextBytes;
 import static org.assertj.core.api.Assertions.assertThat;
-import static org.junit.jupiter.api.Assertions.assertAll;
-import static org.junit.jupiter.api.Assertions.assertEquals;
-import static org.junit.jupiter.api.Assertions.assertNull;
-import static org.junit.jupiter.api.Assertions.assertThrows;
+import static org.junit.jupiter.api.Assertions.*;
```
Comment (filev94) [inline hedera-mirror-common/src/test/java/com/hedera/mirror/common/util/DomainUtilsTest.java:7]: I think there is a rule not to use wildcard imports

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java (hunk 3 above)
Comment (jnels124) [reply hedera-mirror-common/src/main/java/com/hedera/mirror/common/util/DomainUtils.java:321]: Removed this as the only thing relying on this is ` Id.asEvmAddress` which calls a utility function in entity id utils. I have changed that function to convert the id to entityId before getting the evm address. This will result in an `InvalidEntityException` if the id has an invalid shard, realm, or num

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/BitPackUtils.java [hunk 7]
```diff
@@ -1,55 +0,0 @@
...
-
-    /**
-     * Checks if the given long is not a number in the allowed range
-     *
-     * @param num given long number to check
-     * @return true if valid, else returns false
-     */
-    public static boolean isValidNum(long num) {
-        return num >= 0 && num <= MAX_NUM_ALLOWED;
-    }
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/services/utils/BitPackUtils.java:54]: Where do we check this now?

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java [hunk 8]
```diff
@@ -16,60 +18,68 @@
...
         return fromLong(grpc.getTokenNum());
     }
 
+    /**
+     * This method is unsafe to use before the spring context is fully initialized.
+     * */
     static boolean areValidNums(final long shard, final long realm) {
-        return shard == 0 && realm == 0;
+        var commonProps = CommonProperties.getInstance();
+        return shard == commonProps.getShard() && realm == commonProps.getRealm();
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:69]: Why do we need to validate that they're from the configured shard and realm here? This would mean we can't support tables that might have entities across different realms or shards.

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java [hunk 9]
```diff
@@ -16,60 +18,68 @@
...
 
-    public int intValue() {
-        return value;
+    public static EntityNum fromId(Id id) {
+        return new EntityNum(EntityId.of(id.shard(), id.realm(), id.num()));
     }
 
-    public long longValue() {
-        return numFromCode(value);
+    public long getId() {
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:76]: Don't think we should expose the encoded ID. Should update the caller to use `EntityNum` directly. It looks like the only user is `CryptoOpsUsage` which is just using the allowances map to calculate cost.

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/common/Web3UnitTest.java [hunk 10]
```diff
@@ -0,0 +1,13 @@
...
+package com.hedera.mirror.web3.common;
+
+import com.hedera.mirror.common.CommonProperties;
+import org.junit.jupiter.api.BeforeAll;
+
+public abstract class Web3UnitTest {
+    @BeforeAll
+    static void setUp() {
+        new CommonProperties().init();
+    }
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/common/Web3UnitTest.java:12]: Not a fan of this whole class and having to remember to extend unit tests from it. We can just change `CommonProperties.getInstance()` to create one if it doesn't exist and to always set it in `PostConstruct` even when not null.

Or if you feel strongly that's a bad approach, we should call init in a global, centralized place in JUnit so that it occurs only once per JVM. The way to do this looks to be [LauncherSessionListener](https://junit.org/junit5/docs/current/user-guide/#launcher-api-launcher-session-listeners-custom).

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java [hunk 11]
```diff
@@ -16,60 +18,68 @@
...
+        return new EntityNum(DomainUtils.fromEvmAddress(address.toArrayUnsafe()));
     }
 
     public static EntityNum fromInt(final int i) {
         return new EntityNum(i);
     }
 
     public static EntityNum fromLong(final long l) {
-        if (!isValidNum(l)) {
-            return MISSING_NUM;
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:38]: There's some logic that depends upon MISSING_NUM in TransferLogic. Not sure if this removal could cause it problems.

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/BitPackUtils.java (hunk 7 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/services/utils/BitPackUtils.java:54]: Calls now pass through `EntityId.of()` which will validate but throw on an invalid shard,realm,num. It will return fine for 0 id but not for invalid shard, realm, or num. Should we modify the method it uses now(uses EntityNum.fromId) to return an empty id (0.0.0) for these invalid cases?

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java (hunk 8 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:69]: I wasn't sure about  this change initially and the comments on this pr suggested it change to use the configured shard and realm

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/common/Web3UnitTest.java (hunk 10 above)
Comment (jnels124) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/common/Web3UnitTest.java:12]: I agree and wanted to do something globally but wasn't sure of the approach so did this initially

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java (hunk 11 above)
Comment (jnels124) [reply hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:38]: TransferLogic now calls the fromId method which could result in an invalid entity exception if the id is not valid. If it is id:0 it will return empty but for invalid values in shard,realm, or num it will throw an InvalidEntityException. Should we catch that exception on calls from here and return the empty entity num instead?

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java (hunk 8 above)
Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:65]: Probably doesn't matter at this point as this code will go away before we have to consider inter-realm transactions. Let's keep with validating against props.

File: hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java (hunk 11 above)
Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/services/utils/EntityNum.java:38]: I think we should catch the exception and return the empty entity num in order not to change the flow.

**Review by steven-sheehy — APPROVED** [review]
