### PR TITLE
Fix historical.feature failing acceptance tests against modularized EVM

### LINKED ISSUE #10497: Fix historical.feature acceptance test suite against modularized EVM
Fix the failing tests in `historical.feature` and adapt them to work against modularized EVM

### PR DESCRIPTION
**Pull request by nickeynikolovv**
This PR fixes the failing acceptance tests from historical.feature branch
- Two of the tests were failing because of the missing fees upon token creation
-  `Then I successfully update the contract storage and get the initial value via historical data` was failing because of wrong input for slotKey in `ContractStorageReadableKVState` -> `findStorageByBlockTimestamp()`. In order to execute the query correctly the slotKey bytes have to be without leading zeros

**Related issue(s)**:

Fixes #10497 

Note: There are few flaky tests in that suite e.g. `Then I verify that historical data for "FUNGIBLEHISTORICAL" is returned via getTokenInfo`  - The flakiness is not caused by this PR it also occurs in the not modularized EVM flow. Will be fixed in future

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Comment by steven-sheehy** [comment]
Spotless check failing

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java [hunk 1]
```diff
@@ -134,36 +134,40 @@ public void contractDeployed() {
         assertThat(response.getRuntimeBytecode()).isNotBlank();
     }
 
-    @Given("I create fungible and non-fungible token")
-    public void createFungibleToken() {
+    @Given("I create {token} and {token} token with custom fees")
+    public void createTokens(TokenNameEnum fungibleTokenName, TokenNameEnum nftTokenName) {
```
Comment (bilyana-gospodinova) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java:138]: Isn't it better to have separate methods for each token creation type? This way if one of the token fails to be created it would be easier to identify the issue.

Comment (nickeynikolovv) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java]: Done

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM
