### PR TITLE
Honor timestamp param for token by id endpoint

### LINKED ISSUE #10408: When getting a deleted token by ID and passing a timestamp, deleted is always set to true
### Description

When calling https://testnet.mirrornode.hedera.com/api/v1/docs/#/tokens/getToken with the ID of a token that was deleted, then the `deleted` flag is set to true. However if we pass a timestamp before the deletion, then deleted is still set to true even though the token wasn't deleted for that timestamp. 

### Steps to reproduce

1. Call /api/v1/tokens/{tokenId} with a token ID that was deleted and pass a timestamp for which the token wasn't yet deleted
2. Observe that deleted is set to true

### Additional context

_No response_

### Hedera network

_No response_

### Version

v0.118.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:
Updates tokens by id endpoint to support timestamp parameter
* add new k6 test
* add historical token by id spec test

**Related issue(s)**:

Fixes #10408

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by jnels124** [comment]
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=11.003..11.004 rows=1 loops=1)
                                                                                                                QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0) (actual time=11.003..11.004 rows=1 loops=1)
   Task Count: 1
   Tuple data received from nodes: 562 bytes
   Tasks Shown: All
   ->  Task
         Tuple data received from node: 562 bytes
         Node: host=10.4.6.17 port=6432 dbname=mirror_node
         ->  Nested Loop Left Join  (cost=8.57..12.01 rows=1 width=568) (actual time=0.102..0.104 rows=1 loops=1)
               ->  Nested Loop  (cost=5.76..8.04 rows=1 width=528) (actual time=0.064..0.066 rows=1 loops=1)
                     ->  Subquery Scan on t_1  (cost=2.81..3.94 rows=1 width=425) (actual time=0.032..0.033 rows=1 loops=1)
                           Filter: (t_1.token_id = 1275)
                           ->  Limit  (cost=2.81..3.93 rows=1 width=433) (actual time=0.031..0.031 rows=1 loops=1)
                                 ->  Merge Append  (cost=2.81..5.05 rows=2 width=433) (actual time=0.030..0.031 rows=1 loops=1)
                                       Sort Key: (lower(t_2.timestamp_range)) DESC
                                       ->  Sort  (cost=2.52..2.52 rows=1 width=412) (actual time=0.014..0.015 rows=1 loops=1)
                                             Sort Key: (lower(t_2.timestamp_range)) DESC
                                             Sort Method: quicksort  Memory: 25kB
                                             ->  Index Scan using token__pk_102491 on token_102491 t_2  (cost=0.29..2.51 rows=1 width=412) (actual time=0.009..0.010 rows=1 loops=1)
                                                   Index Cond: (token_id = 1275)
                                                   Filter: (lower(timestamp_range) <= '1706816457709028192'::bigint)
                                       ->  Limit  (cost=0.28..2.50 rows=1 width=451) (actual time=0.015..0.015 rows=0 loops=1)
                                             ->  Index Scan Backward using token_history__token_id_timestamp_range_102507 on token_history_102507 t_2_1  (cost=0.28..2.50 rows=1 width=451) (actual time=0.015..0.015 rows=0 loops=1)
                                                   Index Cond: ((token_id = 1275) AND (lower(timestamp_range) <= '1706816457709028192'::bigint))
                     ->  Subquery Scan on e_1  (cost=2.96..4.09 rows=1 width=103) (actual time=0.030..0.031 rows=1 loops=1)
                           Filter: (e_1.id = 1275)
                           ->  Limit  (cost=2.96..4.08 rows=1 width=111) (actual time=0.030..0.030 rows=1 loops=1)
                                 ->  Merge Append  (cost=2.96..5.20 rows=2 width=111) (actual time=0.030..0.030 rows=1 loops=1)
                                       Sort Key: (lower(e_2.timestamp_range)) DESC
                                       ->  Sort  (cost=2.66..2.66 rows=1 width=101) (actual time=0.012..0.012 rows=1 loops=1)
                                             Sort Key: (lower(e_2.timestamp_range)) DESC
                                             Sort Method: quicksort  Memory: 25kB
                                             ->  Index Scan using entity__id_type_102015 on entity_102015 e_2  (cost=0.42..2.65 rows=1 width=101) (actual time=0.009..0.009 rows=1 loops=1)
                                                   Index Cond: (id = 1275)
                                                   Filter: (lower(timestamp_range) <= '1706816457709028192'::bigint)
                                       ->  Limit  (cost=0.29..2.51 rows=1 width=121) (actual time=0.018..0.018 rows=1 loops=1)
                                             ->  Index Scan Backward using entity_history__id_lower_timestamp_102267 on entity_history_102267 e_2_1  (cost=0.29..2.51 rows=1 width=121) (actual time=0.018..0.018 rows=1 loops=1)
                                                   Index Cond: ((id = 1275) AND (lower(timestamp_range) <= '1706816457709028192'::bigint))
               ->  Subquery Scan on cf_1  (cost=2.81..3.94 rows=1 width=540) (actual time=0.028..0.029 rows=1 loops=1)
                     Filter: (cf_1.entity_id = 1275)
                     ->  Limit  (cost=2.81..3.93 rows=1 width=548) (actual time=0.028..0.028 rows=1 loops=1)
                           ->  Merge Append  (cost=2.81..5.05 rows=2 width=548) (actual time=0.028..0.028 rows=1 loops=1)
                                 Sort Key: (lower(cf_2.timestamp_range)) DESC
                                 ->  Sort  (cost=2.52..2.53 rows=1 width=522) (actual time=0.017..0.017 rows=1 loops=1)
                                       Sort Key: (lower(cf_2.timestamp_range)) DESC
                                       Sort Method: quicksort  Memory: 25kB
                                       ->  Index Scan using custom_fee__pk_102235 on custom_fee_102235 cf_2  (cost=0.29..2.51 rows=1 width=522) (actual time=0.014..0.014 rows=1 loops=1)
                                             Index Cond: (entity_id = 1275)
                                             Filter: (lower(timestamp_range) <= '1706816457709028192'::bigint)
                                 ->  Limit  (cost=0.27..2.49 rows=1 width=574) (actual time=0.011..0.011 rows=0 loops=1)
                                       ->  Index Scan Backward using custom_fee_history__token_id_timestamp_range_102251 on custom_fee_history_102251 cf_2_1  (cost=0.27..2.49 rows=1 width=574) (actual time=0.011..0.011 rows=0 loops=1)
                                             Index Cond: ((entity_id = 1275) AND (lower(timestamp_range) <= '1706816457709028192'::bigint))
             Planning Time: 1.780 ms
             Execution Time: 0.183 ms
 Planning Time: 0.873 ms
 Execution Time: 11.037 ms
```

**Comment by jnels124** [comment]
| Scenario | URL | VUS | Pass% | RPS | Pass RPS | Avg. Req Duration | Skipped? | Comment |
|----------|----------|-----|-------|-----|----------|-------------------|--------|---------|
| rampUp | /accounts | 1500 | 98.14 | 209.64/s | 205.74/s | 3587.86ms | No | |
| tokensId | /tokens/2186153 | 1500 | 99.84 | 6349.38/s | 6339.22/s | 234.98ms | No | |
| tokensIdTimestampLte | /tokens/2186153?timestamp=lte:1740548828.862 | 1500 | 99.93 | 6290.06/s | 6285.66/s | 236.29ms | No | |

**Comment by jnels124** [comment]
Lots of sql tests that I would prefer to write after any feedback on functionality is addressed.

File: hedera-mirror-rest/model/token.js [hunk 1]
```diff
@@ -1,11 +1,31 @@
-// SPDX-License-Identifier: Apache-2.0
-
```
Comment (steven-sheehy) [inline hedera-mirror-rest/model/token.js:2]: Revert

**Review by steven-sheehy — CHANGES_REQUESTED** [review]
Approach seems good. Tests are failing and it's missing spec changes to account for history tables.

Edit: Now I see your last comment.

**Review by steven-sheehy — APPROVED** [review]
LGTM

**Review by edwin-greene — APPROVED** [review]
Looks good to me
