### PR TITLE
Convert `/network/fees` to Java

### LINKED ISSUE #12303: Convert `/network/fees` API to Java
### Problem

As a maintainer, I'd like to convert `/api/v1/network/fees` to Java to ease maintenance and improve performance.

## Phase One

Phase one implements the new API in Java with it disabled by default. Thorough testing is conducted to verify no
regressions are introduced.

### REST Java

- [ ] Controller, services, repositories, etc. implemented in rest-java
- [ ] Use Jooq for any dynamic SQL, repositories for any static queries
- [ ] New `Cache-Control` entry added to `rest-java/src/main/resources/application.yml`
- [ ] Controller integration tests added with equivalent or better coverage to existing rest spec tests.

### REST

- [ ] `REST_JAVA_INCLUDE` and `testFiles` updated in `rest/build.gradle.kts`
- [ ] All existing rest spec tests passing against rewritten Java endpoint

### Acceptance

- [ ] Acceptance tests updated to use `MirrorNodeClient.callConvertedRestEndpoint()`
- [ ] Passing acceptance tests

### Performance

- [ ] K6 tests for endpoint duplicated in rest-java folder
- [ ] K6 tests passing with equal to or greater than rps as older API

### Deployment

- [ ] New rest-java route added to `docker-compose.yml` haproxy config
- [ ] New `routes.<apiName>` property added to `charts/hedera-mirror-rest-java/values.yaml` and defaulted to `false`
- [ ] New route added to ingress conditional on routes property
- [ ] New route added to gateway conditional on routes property
- [ ] Enable route in integration environment before tagging and test it
- [ ] Enable route in previewnet and watch metrics/logs
- [ ] Enable route in both testnet clusters for a release and watch metrics/logs

## Phase Two

Phase two enables the new route by default so that it rolls out to mainnet for the first time. The legacy code is kept
until we're confident there are no regressions.

- [ ] Enable route by default in Ingress and Gateway
- [ ] Update JavaScript monitor to use REST Java URL for route
- [ ] Remove temporary enablement in previewnet and testnet so that default is used

## Phase Three

Phase three cleans up the legacy code and configuration so that only the rest-java route remains.

- [ ] Delete JavaScript code and tests
- [ ] Delete `Cache-Control` entry in rest config
- [ ] Delete duplicate rest k6 test
- [ ] Remove `routes.<apiName>` property in chart and its use in ingress and gateway
- [ ] Acceptance tests updated to use `MirrorNodeClient.callRestJavaEndpoint()`
- [ ] `REST_JAVA_INCLUDE` and `testFiles` updated to remove route and specs in `rest/build.gradle.kts`

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by martingeorgiev1**
**Description**:
Add /api/v1/network/fees to rest-java module
Add k6 tests for rest-java network fees
Add routes.fees* with a default of false to Helm chart

**Related issue(s)**:

Fixes #12303 

**Notes for reviewer**:
Tested on local machine and the results:

Rest Endpoint:
```
  ✓ 'p(95)>=0' p(95)=28.29ms
    checks_total.......: 13687   455.970375/s
    checks_succeeded...: 100.00% 13687 out of 13687
    checks_failed......: 0.00%   0 out of 13687
```

After switching to java-rest endpoint:
```
    ✓ 'p(95)<500' p(95)=2.6ms
    checks_total.......: 165067  5501.708104/s
    checks_succeeded...: 100.00% 165067 out of 165067
    checks_failed......: 0.00%   0 out of 165067
```
Result:
~11× lower latency (p95)
~12× higher throughput

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 1]
```diff
@@ -39,6 +44,16 @@ NetworkExchangeRateSetResponse getExchangeRate(
         return exchangeRateMapper.map(exchangeRateSet);
     }
 
+    @GetMapping("/fees")
+    NetworkFeesResponse getFees(
+            @RequestParam(required = false) @Size(max = 2) TimestampParameter[] timestamp,
+            @RequestParam(required = false, defaultValue = "asc") String order) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]:
```suggestion
            @RequestParam(required = false, defaultValue = "asc") Sort.Direction order) {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/service/FileServiceImpl.java [hunk 2]
```diff
@@ -35,6 +36,11 @@ public SystemFile<ExchangeRateSet> getExchangeRate(Bound timestamp) {
         return getSystemFile(systemEntity.exchangeRateFile(), timestamp, ExchangeRateSet::parseFrom);
     }
 
+    @Override
+    public SystemFile<CurrentAndNextFeeSchedule> getFeeSchedule(Bound timestamp) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/service/FileServiceImpl.java:40]: Needs a test

File: rest/__tests__/specs/network/fees/timestamp-invalid-params.json [hunk 3]
```diff
@@ -3,19 +3,32 @@
...
-          "message": "Unknown query parameter: limit"
-        }
-      ]
+  "responseJsonMatrix": {
+    "java": {
+      "_status": {
+        "messages": [
+          {
+            "data": null,
+            "detail": "Failed to convert 'timestamp'",
```
Comment (steven-sheehy) [inline rest/__tests__/specs/network/fees/timestamp-invalid-params.json:12]: It looks like we're not accruing multiple validation failures. Might be something we need to look into, not necessarily part of this ticket.

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 4]
```diff
@@ -39,6 +44,16 @@ NetworkExchangeRateSetResponse getExchangeRate(
...
+        final var bound = timestampBound(timestamp);
+        final var feeSchedule = fileService.getFeeSchedule(bound);
+        final var exchangeRate = fileService.getExchangeRate(bound);
+        return feeScheduleMapper.map(feeSchedule, exchangeRate, order, commonMapper);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: You don't need to pass commonMapper explicitly. If you look at the generated source for feeschedulemapper it will already have an injected commonMapper.

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+            SystemFile<ExchangeRateSet> exchangeRateFile,
+            String order,
+            CommonMapper commonMapper) {
+
+        var schedule = feeScheduleFile.protobuf().getCurrentFeeSchedule();
+        var rate = exchangeRateFile.protobuf().getCurrentRate();
+
+        var fees = schedule.getTransactionFeeScheduleList().stream()
+                .filter(s -> ENABLED_TRANSACTION_TYPES.containsKey(s.getHederaFunctionality()) && s.getFeesCount() > 0)
+                .map(s -> mapToNetworkFee(s, rate.getHbarEquiv(), rate.getCentEquiv()))
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]: Can pass a single rate param through to mapToNetworkFee and convertGasPriceToTinyBars

```suggestion
                .map(s -> mapToNetworkFee(s, rate))
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+import java.util.Comparator;
+import java.util.Map;
+import org.hiero.mirror.rest.model.NetworkFee;
+import org.hiero.mirror.rest.model.NetworkFeesResponse;
+import org.hiero.mirror.restjava.dto.SystemFile;
+import org.jspecify.annotations.Nullable;
+import org.mapstruct.Mapper;
+
+@Mapper(config = MapperConfiguration.class, uses = CommonMapper.class)
+public interface FeeScheduleMapper {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java:24]: Needs tests

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+            String order,
+            CommonMapper commonMapper) {
+
+        var schedule = feeScheduleFile.protobuf().getCurrentFeeSchedule();
+        var rate = exchangeRateFile.protobuf().getCurrentRate();
+
+        var fees = schedule.getTransactionFeeScheduleList().stream()
+                .filter(s -> ENABLED_TRANSACTION_TYPES.containsKey(s.getHederaFunctionality()) && s.getFeesCount() > 0)
+                .map(s -> mapToNetworkFee(s, rate.getHbarEquiv(), rate.getCentEquiv()))
+                .filter(f -> f != null)
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]:
```suggestion
                .filter(Objects::nonNull)
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+
+        return tinyBars == null ? null : new NetworkFee().gas(tinyBars).transactionType(type);
+    }
+
+    @Nullable
+    default Long convertGasPriceToTinyBars(long gasPrice, int hbars, int cents) {
+        return cents == 0 ? null : Math.max((gasPrice * hbars) / (cents * FEE_DIVISOR_FACTOR), 1L);
+    }
+
+    default Comparator<NetworkFee> getComparator(String order) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]:
```suggestion
    default Comparator<NetworkFee> getComparator(Sort.Order order) {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+        var comparator = Comparator.comparing(NetworkFee::getTransactionType, String.CASE_INSENSITIVE_ORDER);
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]: Store comparator as static class var.

File: rest-java/src/test/java/org/hiero/mirror/restjava/controller/NetworkControllerTest.java [hunk 10]
```diff
@@ -222,6 +231,258 @@ private SystemFile<ExchangeRateSet> systemFile() {
...
+            "?timestamp=gt:{0}&timestamp=lte:{1}, 1"
+        })
+        void timestampBounds(String parameters, int expectedIndex) {
+            // given - create matching pairs of exchange rates and fee schedules
+            final var exchangeRate0 = systemFileExchangeRate();
+            final var fee0 = systemFileFee();
+            final var exchangeRate1 = systemFileExchangeRate();
+            final var fee1 = systemFileFee();
+            final var exchangeRate2 = systemFileExchangeRate();
+            final var fee2 = systemFileFee();
```
Comment (steven-sheehy) [inline rest-java/src/test/java/org/hiero/mirror/restjava/controller/NetworkControllerTest.java:331]: nit: Group exchangerates together and fees together to make it more readable.

Comment (martingeorgiev1) [reply rest-java/src/test/java/org/hiero/mirror/restjava/controller/NetworkControllerTest.java:331]: We cannot group them like that, because  each fee needs an exchange rate created just before it to be found within the query bounds.

File: rest/__tests__/specs/network/fees/timestamp-invalid-params.json (hunk 3 above)
Comment (martingeorgiev1) [reply rest/__tests__/specs/network/fees/timestamp-invalid-params.json:12]: I've created a follow up ticket: https://github.com/hiero-ledger/hiero-mirror-node/issues/12382

File: .github/workflows/copy-stackgres-cluster.yml [hunk 11]
```diff
@@ -204,7 +204,7 @@ jobs:
           echo "CLOUDSDK_BIN_DIR=$CLOUDSDK_BIN_DIR" >> "$GITHUB_ENV"
 
       - name: Setup Testkube CLI
-        uses: kubeshop/setup-testkube@12a1cb43ab0cc9a90aef8c8447fa22a3b2c7e7c8 # v1.0.10
+        uses: kubeshop/setup-testkube@e06cc069575f7cd2a67403c7da0a48229371a1db # v1.0.11
```
Comment (steven-sheehy) [inline .github/workflows/copy-stackgres-cluster.yml:207]: Some merge issues. Maybe try merging from main

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java [hunk 12]
```diff
@@ -26,7 +30,9 @@
 @RestController
 final class NetworkController {
 
+    private final CommonMapper commonMapper;
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/NetworkController.java]: Unused

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java (hunk 6 above)
Comment (steven-sheehy) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java:24]: Still no test

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Comment by steven-sheehy** [comment]
Needs merge from main

File: charts/hedera-mirror-rest-java/values.yaml [hunk 13]
```diff
@@ -78,6 +78,12 @@ gateway:
         - path:
             type: RegularExpression
             value: '/api/v1/network/exchangerate'
+        {{- end }}
```
Comment (steven-sheehy) [inline charts/hedera-mirror-rest-java/values.yaml]: Need to remove this end block

**Review by steven-sheehy — APPROVED** [review]
