### PR TITLE
HIP-1056 Set receipt.AccountID for crypto update transactions

### LINKED ISSUE #12343: HIP-1056 Blockstream transformer should set receipt.AccountID for crypto update transaction
### Description

Differential testing has detected discrepancy that for successful `CyrptoUpdate` transactions, the receipt transformed from blockstream leaves `AccountID` unset.

### Steps to reproduce

Run differential testing against blocks with `CryptoUpdate` transactions.

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.143.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes receipt.AccountID not set

- Set receipt.AccountID for crypto update transactions

**Related issue(s)**:

Fixes #12343 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: common/src/main/java/org/hiero/mirror/common/domain/transaction/StateChangeContext.java [hunk 1]
```diff
@@ -196,18 +203,24 @@ private void processAccountStateChange(MapUpdateChange mapUpdate) {
...
+            if (account.getSmartContract()) {
+                contractIds.put(
+                        account.getAlias(),
+                        ContractID.newBuilder()
+                                .setShardNum(accountId.getShardNum())
+                                .setRealmNum(accountId.getRealmNum())
+                                .setContractNum(accountId.getAccountNum())
+                                .build());
+            } else {
+                accountIds.put(alias, account.getAccountId());
```
Comment (IvanKavaldzhiev) [inline common/src/main/java/org/hiero/mirror/common/domain/transaction/StateChangeContext.java]: nit: we have accountId declared already above the if statement.

File: common/src/main/java/org/hiero/mirror/common/domain/transaction/StateChangeContext.java [hunk 2]
```diff
@@ -196,18 +203,24 @@ private void processAccountStateChange(MapUpdateChange mapUpdate) {
...
-                            .setRealmNum(accountId.getRealmNum())
-                            .setContractNum(accountId.getAccountNum())
-                            .build());
+        if (account.getAlias() != ByteString.EMPTY) {
+            final var accountId = account.getAccountId();
+            final var alias = account.getAlias();
+
+            if (account.getSmartContract()) {
+                contractIds.put(
+                        account.getAlias(),
```
Comment (IvanKavaldzhiev) [inline common/src/main/java/org/hiero/mirror/common/domain/transaction/StateChangeContext.java]: nit: we have alias declared above

File: common/src/test/java/org/hiero/mirror/common/domain/transaction/StateChangeContextTest.java [hunk 3]
```diff
@@ -77,6 +77,29 @@ void accounts() {
...
+                .addStateChanges(contractMapUpdateChange(contractId, evmAddress))
+                .addStateChanges(otherMapUpdateChange())
+                .build();
+
+        // when
+        final var context = new StateChangeContext(List.of(stateChanges));
+
+        // then
+        assertThat(context.getAccountId(account1Alias)).contains(accountId1);
+        assertThat(context.getAccountId(evmAddress)).isEmpty();
```
Comment (IvanKavaldzhiev) [inline common/src/test/java/org/hiero/mirror/common/domain/transaction/StateChangeContextTest.java:100]: Probably we can also check:

`assertThat(context.getContractId(evmAddress)).contains(contractId);`

**Review by steven-sheehy — APPROVED** [review]

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM
