### PR TITLE
Fixing InitializeEntityBalanceMigration SQL query and tests 

### LINKED ISSUE #10898: Fix InitializeEntityBalanceMigration to match entityId conversion to the correct entityId size
### Description

With the change in entityId size the manipulation of entity_id in InitializeEntityBalanceMigration sql is incorrect. This needs to be fixed.
We also need to re-add encodeEntityId sql function.
 like 
```
 create function encodeEntityId(shard bigint, realm bigint, num bigint)
    returns entity_id as
$$
begin
    -- Encoding: 15 bits for shard (mask = 0x7fff = 32767), followed by 16 bits for realm (mask = 0xffff = 65535),
    -- followed by 32 bits for num (max = 0xffffffff = 4294967295)
    return (num & 4294967295) | ((realm & 65535) << 32) | ((shard & 32767) << 48);
end
$$ language plpgsql;
```

in a repeatable migration.

### Steps to reproduce

1. Set Realm to non-zero in CommonProperties and CommonIntegrationTest and run the InitializeEntityBalanceMigrationTest. These fail in the given situation.

### Additional context

_No response_

### Hedera network

OTHER

### Version

 v0.127.0 

### Operating system

None

### PR DESCRIPTION
**Pull request by filev94**
**Description**:
This PR changes the INITIALIZE_ENTITY_BALANCE_SQL to accommodate for the new size of entityId and makes modifications to the InitializeEntityBalanceMigrationTest to make it pass with non-zero realm.

**Related issue(s)**:

Fixes #10898 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java [hunk 1]
```diff
@@ -38,7 +38,7 @@ select entity_id, sum(amount) as amount
                 full outer join change on account_id = entity_id
             )
             insert into entity (balance, balance_timestamp, deleted, id, num, realm, shard, timestamp_range)
-            select s.balance, s.balance_timestamp, s.deleted, s.account_id, (s.account_id & 4294967295), ((s.account_id >> 32) & 65535), (s.account_id  >> 48), '[0,)'
+            select s.balance, s.balance_timestamp, s.deleted, s.account_id, (s.account_id & 274877906943), ((s.account_id >> 38) & 65535), ((s.account_id  >> 54) & 1023), '[0,)'
             from state s
```
[the remark this answers is not in the document]
Comment (filev94) [reply hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigration.java:42]: Addressed

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java [hunk 2]
```diff
@@ -75,10 +75,10 @@ private EntityId(long id) {
      * operations too. That's because JavaScript's support for bitwise operations is very limited (truncates numbers to
      * 32 bits internally before bitwise operation).
      * <p/>
-     * Format: <br/> First bit (sign bit) is left 0. <br/> Next 15 bits are for shard, followed by 16 bits for realm,
-     * and then 32 bits for entity num. <br/> This encoding will support following ranges: <br/> shard: 0 - 32767 <br/>
-     * realm: 0 - 65535 <br/> num: 0 - 4294967295 <br/> Placing entity num in the end has the advantage that encoded ids
-     * <= 4294967295 will also be human-readable.
+     * Format: <br/> First bit (sign bit) is left 0. <br/> Next 10 bits are for shard, followed by 16 bits for realm,
```
Comment (xin-hedera) [inline hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java:78]:
```suggestion
     * Format: First 10 bits are for shard, followed by 16 bits for realm,
```

File: hedera-mirror-importer/src/main/resources/db/migration/v2/R__encode_entity_id.sql [hunk 3]
```diff
@@ -0,0 +1,9 @@
+create or replace function encodeEntityId(shard bigint, realm bigint, num bigint)
```
Comment (xin-hedera) [inline hedera-mirror-importer/src/main/resources/db/migration/v2/R__encode_entity_id.sql:1]: don't think this is needed. in V1 it's dropped by migration V1.46.5, and it never existed in V2.

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java (hunk 2 above)
Comment (steven-sheehy) [inline hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java:78]: Can remove `Only 63 bits (excluding signed bit)` above.

File: hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java [hunk 4]
```diff
@@ -324,17 +324,17 @@ private void setup() {
     private void setupForFirstAccountBalanceFile() {
         // account2 not in db, its balance information is deduped and its account balance timestamp is before
         // accountBalanceFile1
-        long id = domainBuilder.id();
+        var entityId = domainBuilder.entityId();
         account2 = Entity.builder()
```
Comment (steven-sheehy) [inline hedera-mirror-importer/src/test/java/com/hedera/mirror/importer/migration/InitializeEntityBalanceMigrationTest.java:328]:
```suggestion
        account2 = systemEntity.treasuryAccount()
                   .toEntity()
                   .toBuilder()
```

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java (hunk 2 above)
Comment (filev94) [reply hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java]: Fixed

Comment (filev94) [reply hedera-mirror-common/src/main/java/com/hedera/mirror/common/domain/entity/EntityId.java]: Removed

**Review by jnels124 — APPROVED** [review]

**Review by xin-hedera — APPROVED** [review]
LGTM
