### PR TITLE
Fix unsuccessful Ethereum transactions not found on contract results API

### LINKED ISSUE #3954: Contract Results is not reporting EthereumTransaction with Status Errors
### Description

An EthereumTransaciton does not have a corresponding contract/results/<hash> result even though it was accepted for consensus.

```
https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.2859100-1655309548-529823609?nonce=0

{
  "transactions": [
    {
      "bytes": null,
      "charged_tx_fee": 153681,
      "consensus_timestamp": "1655309560.345897097",
      "entity_id": null,
      "max_fee": "200000000",
      "memo_base64": "",
      "name": "ETHEREUMTRANSACTION",
      "node": "0.0.4",
      "nonce": 0,
      "parent_consensus_timestamp": null,
      "result": "INVALID_CONTRACT_ID",
      "scheduled": false,
      "transaction_hash": "shiSPH3j394EG8RCxoTqHMdu3qeYbHcGsDNcle0flTeBet5fMHKaOMSLuXEKLaq4",
      "transaction_id": "0.0.2859100-1655309548-529823609",
      "transfers": [
        {
          "account": "0.0.4",
          "amount": 5454,
          "is_approval": false
        },
        {
          "account": "0.0.98",
          "amount": 148227,
          "is_approval": false
        },
        {
          "account": "0.0.2859100",
          "amount": -153681,
          "is_approval": false
        }
      ],
      "valid_duration_seconds": "120",
      "valid_start_timestamp": "1655309548.529823609"
    }
  ]
}
```

```
https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0.0.2859100-1655309548-529823609

{
  "_status": {
    "messages": [
      {
        "message": "Not found"
      }
    ]
  }
}
```

I would have expected something more like this (hacked up from 0x34ceebae4ce11e84468f014c99e3c800c70dffc4154107d75851bd5f802bc710)
```
{
  "amount": 0,
  "bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "call_result": "0x",
  "contract_id": "0.0.45911647",
  "created_contract_ids": [],
  "error_message": "INVALID_CONTRACT_ID",
  "from": "0x0000000000000000000000000000000002bc8e61",
  "function_parameters": "0x",
  "gas_limit": 0,
  "gas_used": 21000,
  "timestamp": "1655311425.435874180",
  "to": "0x0000000000000000000000000000000002bc8e5f",
  "block_hash": "0x303cdeceec34aa41c288dafc41c970f5f27a9a7066d7de301e0a7ceada0594a34ff55b133759660421b0df1fd9a453e0",
  "block_number": 21969469,
  "logs": [],
  "result": "INVALID_CONTRACT_ID",
  "transaction_index": 0,
  "hash": "0x34ceebae4ce11e84468f014c99e3c800c70dffc4154107d75851bd5f802bc710",
  "state_changes": [],
  "status": "0x0",
  "access_list": "0x",
  "block_gas_used": 21000,
  "chain_id": "0x12a",
  "gas_price": "0x",
  "max_fee_per_gas": "0x086",
  "max_priority_fee_per_gas": "0x086",
  "r": "0xf96a2c93cee9a71f8999948242e0ec0f1dc1d1eeabdcb951813a99f3b366313c",
  "s": "0x0a915689072292abf894fd4bc523c9bb1b059efbde5eb71a18439e67fc3dee31",
  "type": 2,
  "v": 1,
  "nonce": 2
}
```

Major Differences are 
* "status" is "0x0"
* "result" is the response code
* "error" is the text of the response code.

bloom will be all zeros, call result is zero length, created contract IDs is empty, state changes is empty array, etc.

If we get a record from the record query we should generate a transaction receipt, even if the transaction had no ledger effect aside from fees/gas consumption and has an error hedera status..

### Steps to reproduce

create an ethereum transaction targeting an address with no account
submit to consensus
attempt to query via `https://testnet.mirrornode.hedera.com/api/v1/contracts/results/<ethereumHash>`

### Additional context

_No response_

### Hedera network

testnet

### Version

0.57.2

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by ar-conmit**
Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #3954 

**Notes for reviewer**:
Example response:
```
{
  "amount": 0,
  "bloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "call_result": "0x",
  "contract_id": "0.0.1006",
  "created_contract_ids": [],
  "error_message": "INVALID_CONTRACT_ID",
  "from": "0x0000000000000000000000000000000000000002",
  "function_parameters": "0x",
  "gas_limit": 0,
  "gas_used": 0,
  "timestamp": "1655985454.224602715",
  "to": "0x00000000000000000000000000000000000003ee",
  "hash": "0x8fd6307a325ae86ae726bb4167319903662f4b933cf1875ad23a689739f5fb52",
  "block_hash": "0xe260af3a31c19ee7d5f728e45201696f3e5cf9daf036e5d37869665acbc8fbbc1e611e3a7d49df74e6816129f8e8705b",
  "block_number": 793,
  "logs": [],
  "result": 16,
  "transaction_index": 1,
  "state_changes": [],
  "status": "0x0",
  "access_list": "0x",
  "block_gas_used": 320000,
  "chain_id": "0x12a",
  "gas_price": "0x",
  "max_fee_per_gas": "0xdb",
  "max_priority_fee_per_gas": "0xdb",
  "r": "0x2661712d86a4f8217dd1ccc6eac333f6ebf817b9c89964ee16af76b79071082e",
  "s": "0x5f5b573d569a9556dfaf8bda7c325fabeaf1c0174277514e650661a73d097c45",
  "type": 2,
  "v": 1,
  "nonce": 1
}
```
**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-rest/controllers/contractController.js [hunk 1]
```diff
@@ -1074,17 +1093,34 @@ class ContractController extends BaseController {
...
+    return {
+      bloom: Buffer.alloc(256),
+      callResult: null,
+      createdContractIds: [],
+      functionParameters: [],
+      payerAccountId: transaction.payerAccountId,
+      errorMessage: TransactionResult.getName(transaction.result),
+      consensusTimestamp: transaction.consensusTimestamp,
+      contractId:
+        transaction.toAddress && transaction.toAddress.toString('hex') ? transaction.toAddress.toString('hex') : null,
```
Comment (Nana-EC) [inline hedera-mirror-rest/controllers/contractController.js:1120]: nit: pull out toAddress conversion
```
const toAddress = transaction.toAddress ? transaction.toAddress.toString('hex') : null;
```
```suggestion
        toAddress ? toAddress : null,
```

File: hedera-mirror-rest/controllers/contractController.js [hunk 2]
```diff
@@ -1074,17 +1093,34 @@ class ContractController extends BaseController {
...
       transaction,
       contractLogs,
       contractStateChanges,
-      fileData
+      fileData,
+      shouldMockContractResults
     );
   };
+
+  getMockedContractResultByTransaction = (transaction) => {
```
Comment (Nana-EC) [inline hedera-mirror-rest/controllers/contractController.js:1110]: nit: mocked doesn't really inform the scenario
```suggestion
  getDefaultFailureContractResultByTransaction = (transaction) => {
```

File: hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js [hunk 3]
```diff
@@ -48,7 +48,15 @@ class ContractResultDetailsViewModel extends ContractResultViewModel {
...
    */
-  constructor(contractResult, recordFile, transaction, contractLogs, contractStateChanges, fileData) {
+  constructor(
+    contractResult,
+    recordFile,
+    transaction,
+    contractLogs,
+    contractStateChanges,
+    fileData,
+    isContractResultMocked
```
Comment (Nana-EC) [inline hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js:58]: nit:
```suggestion
    isFailedContractResult
```

**Review by Nana-EC — COMMENTED** [review]
Looks good.
Though I think we could better describe the scenario. It's less a mock and more of a default failure result we're falling back on

File: hedera-mirror-rest/controllers/contractController.js [hunk 4]
```diff
@@ -1074,17 +1093,34 @@ class ContractController extends BaseController {
...
+    return {
+      bloom: Buffer.alloc(256),
```
Comment (xin-hedera) [inline hedera-mirror-rest/controllers/contractController.js:1112]: can make `Buffer.alloc(256)` to a constant. frequently alloc then garbage collect it may create performance issue

File: hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js [hunk 5]
```diff
@@ -66,6 +74,11 @@ class ContractResultDetailsViewModel extends ContractResultViewModel {
         ? ContractResultDetailsViewModel._SUCCESS_RESULT
         : ContractResultDetailsViewModel._FAIL_RESULT;
 
+    if (isContractResultMocked) {
+      this.result = transaction.result;
+      this.status = ContractResultDetailsViewModel._FAIL_RESULT;
+    }
```
Comment (xin-hedera) [inline hedera-mirror-rest/viewmodel/contractResultDetailsViewModel.js:80]: not needed. once the block is removed, the new function parameter `isContractResultMocked` is not needed either.

File: hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+    "gas_limit": 1000000,
+    "gas_price": "0x4a817c80",
+    "gas_used": 0,
+    "hash": "0x4a563af33c4871b51a8b108aa2fe1dd5280a30dfb7236170ae5e5e7957eb6392",
+    "logs": [],
+    "max_fee_per_gas": "0x",
+    "max_priority_fee_per_gas": "0x",
+    "nonce": 1,
+    "r": "0xd693b532a80fed6392b428604171fb32fdbf953728a3a7ecc7d4062b1652c042",
+    "result": 16,
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json:64]: the result should be a string. reverting the changes in `contractResultDetailsViewModel.js` should fix it

File: hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+        "hash": "6ceecd8bb224da491"
+      }
+    ]
+  },
+  "urls": [
+    "/api/v1/contracts/results/0.0.8001-167654-000123455",
+    "/api/v1/contracts/results/4a563af33c4871b51a8b108aa2fe1dd5280a30dfb7236170ae5e5e7957eb6392",
+    "/api/v1/contracts/results/0x4a563af33c4871b51a8b108aa2fe1dd5280a30dfb7236170ae5e5e7957eb6392"
+  ],
+  "responseStatus": 206,
```
Comment (xin-hedera) [inline hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json:40]: I believe this should be `200` instead of `206`. @Nana-EC can you look into it since I'm not sure the 206 missing contract call result should apply to this scenario or not?

**Review by xin-hedera — CHANGES_REQUESTED** [review]

File: hedera-mirror-rest/controllers/contractController.js (hunk 1 above)
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:1120]: This is incorrect. The `contract_id` should always be the `shard.realm.num` format and not a hex number.

File: hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json (hunk 6 above)
Comment (ar-conmit) [reply hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json:64]: In the issue is pointed out that `result` should be the response code and the `error_message` should be the text of the response code

File: hedera-mirror-rest/controllers/contractController.js (hunk 1 above)
Comment (ar-conmit) [reply hedera-mirror-rest/controllers/contractController.js:1120]: `toAddress` is now replaced with `entityId` which is always a number or null

Comment (ar-conmit) [reply hedera-mirror-rest/controllers/contractController.js:1120]: `toAddress` is now replaced with `entityId`

**Review by xin-hedera — DISMISSED** [review]
LGTM

File: hedera-mirror-rest/controllers/contractController.js [hunk 8]
```diff
@@ -1085,6 +1103,20 @@ class ContractController extends BaseController {
...
+  getDefaultFailureContractResultByTransaction = (transaction) => {
+    return {
+      bloom: emptyBloomBuffer,
+      callResult: null,
+      createdContractIds: [],
+      functionParameters: [],
+      payerAccountId: transaction.payerAccountId,
+      errorMessage: TransactionResult.getName(transaction.result),
+      consensusTimestamp: transaction.consensusTimestamp,
+      contractId: transaction.entityId,
```
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:1116]: Technically if there's no contract result there's no `transaction.entityId` since it's populated from the `record.contractFunctionResult.contractID` in the importer for EthereumTransaction. So it's a bit useless to return this in this scenario. You can see this reflected in the original ticket's JSON response:

https://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.2859100-1655309548-529823609?nonce=0

Recommend you revert query returning entityId and set null here.

```suggestion
      contractId: null,
```

File: hedera-mirror-rest/controllers/contractController.js [hunk 9]
```diff
@@ -1085,6 +1103,20 @@ class ContractController extends BaseController {
       fileData
     );
   };
+
+  getDefaultFailureContractResultByTransaction = (transaction) => {
+    return {
+      bloom: emptyBloomBuffer,
+      callResult: null,
+      createdContractIds: [],
+      functionParameters: [],
```
Comment (steven-sheehy) [inline hedera-mirror-rest/controllers/contractController.js:1112]: nit: sort these fields

File: hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json (hunk 7 above)
Comment (Nana-EC) [reply hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json:40]: The 206 case was used when the ContractFunctionResult returned from the network was partial. In this case since there's none it can be 200

**Review by Nana-EC — DISMISSED** [review]
LG

File: hedera-mirror-rest/controllers/contractController.js (hunk 8 above)
Comment (ar-conmit) [reply hedera-mirror-rest/controllers/contractController.js]: Done

File: hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json (hunk 7 above)
Comment (ar-conmit) [reply hedera-mirror-rest/__tests__/specs/contracts-result-details-22-transactionid-or-hash-eth-tx-result-mocked.spec.json]: Done

**Review by steven-sheehy — APPROVED** [review]
LGTM
