### PR TITLE
Fix "Unhandled failure for input" error

### LINKED ISSUE #11963: Investigate "Unhandled failure for input" error
Several errors (2 for the last 24 hours from opening the ticket) of type "Unhandled failure for input" are observed in Grafana due to java.lang.UnsupportedOperationException: null.

To see the whole stacktrace filter by "|~ "Unhandled failure for input" in Grafana explorer.

### PR DESCRIPTION
**Pull request by bilyana-gospodinova**
**Description**:
In some rare cases when the sender of a transaction is a hollow account and we have an inner child transaction that makes a transfer from this account to another account, the first one needs to be completed. However, by calling the `TransactionExecutor` directly in the MN, we bypass the account completion (which happens in the `HandleWorkflow` on the consensus node). This PR modifies the sender hollow account in the state by setting a default key for it and this way "completing" it, so that the transaction execution can proceed as expected. After this change the transaction passed against MN and CN will be successful in both cases. 

Fixes #11963

### CODE REVIEW

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java [hunk 1]
```diff
@@ -225,6 +227,15 @@ private AccountID getSenderAccountID(final CallServiceParameters params) {
             throwPayerAccountNotFoundException(SENDER_NOT_FOUND);
         } else if (account.smartContract()) {
             throwPayerAccountNotFoundException(SENDER_IS_SMART_CONTRACT);
+        } else if (!account.hasKey() || account.key().equals(HOLLOW_ACCOUNT_KEY)) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: Can you use `KeyUtils.IMMUTABILITY_SENTINEL_KEY`?

File: web3/src/main/java/org/hiero/mirror/web3/state/Utils.java [hunk 2]
```diff
@@ -20,6 +20,18 @@ public class Utils {
     public static final int EVM_ADDRESS_LEN = 20;
     public static final Key EMPTY_KEY_LIST =
             Key.newBuilder().keyList(KeyList.DEFAULT).build();
+    public static final Key DEFAULT_KEY = Key.newBuilder()
+            .keyList(KeyList.newBuilder()
+                    .keys(Key.newBuilder()
+                            .ecdsaSecp256k1(com.hedera.pbj.runtime.io.buffer.Bytes.wrap(new byte[] {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/Utils.java]:
```suggestion
                            .ecdsaSecp256k1(Bytes.wrap(new byte[] {
```

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java:1]: > Note that this way we skip one synthetic crypto update for the hollow account completion and this may result in a slightly inaccurate gas estimation.

Why would a synthetic update increase gas? Shouldn't that just cause higher payer fees which our code doesn't care about?

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java [hunk 3]
```diff
@@ -225,6 +227,15 @@ private AccountID getSenderAccountID(final CallServiceParameters params) {
...
+            // If the account is hollow, complete it in the state as a workaround
+            // as this happens in HandleWorkflow in hedera-app but calling the
+            // transaction executor directly skips this account completion and
+            // this results in failed transactions that would otherwise succeed
+            // against the consensus node.
+            final var writableAccountCache = ContractCallContext.get().getWriteCacheState(AccountReadableKVState.KEY);
+            final var completedAccount = account.copyBuilder().key(DEFAULT_KEY).build();
+            writableAccountCache.put(account.accountId(), completedAccount);
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java:238]: Is it possible to ask upstream to move the completion from handle to somewhere invoked by hedera-app so we can remove this workaround in the future?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java (hunk 1 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: Changed

File: web3/src/main/java/org/hiero/mirror/web3/state/Utils.java (hunk 2 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/Utils.java]: Fixed

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java (hunk 3 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java:238]: I forwarded the question. I am waiting for a response now.

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java:1]: It's possible. I reached out to the execution team to confirm.

**Review by steven-sheehy — APPROVED** [review]

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java:1]: They confirmed that the gas consumption will not change, so we are good there.

Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java:1]: I updated the PR description to reflect this discussion.

**Review by sdimitrov9 — APPROVED** [review]
