### PR TITLE
Adapt web3 startup with modularized for non genesis startup

### LINKED ISSUE #10555: Disable account balance verification on startup
### Problem

On web3 container startup when the DB is not empty (as it will be on an environment that is not local) the following exception occurs on state initialization:

```
Error creating bean with name 'mirrorNodeState': Invocation of init method failed
...
Caused by: java.lang.IllegalStateException: Total balance of all accounts does not match the total float: actual: 0 vs expected: 5000000000000000000
2025-03-06 14:10:21     at com.hedera.node.app.service.token.impl.schemas.V0490TokenSchema.createGenesisSchema(V0490TokenSchema.java:194)
2025-03-06 14:10:21     at com.hedera.node.app.service.token.impl.schemas.V0490TokenSchema.migrate(V0490TokenSchema.java:116)
2025-03-06 14:10:21     at com.hedera.mirror.web3.state.components.SchemaRegistryImpl.migrate(SchemaRegistryImpl.java:127)
2025-03-06 14:10:21     at com.hedera.mirror.web3.state.components.ServiceMigratorImpl.lambda$doMigrations$0(ServiceMigratorImpl.java:69)
...
```

The reason for that is that on startup all of the account balances are summed up and the value is expected to be equal to 50,000,000,000 HBARs (comes from config). Currently the account size is not returned correctly and no actual sum is performed.

### Solution

Disable the account balance verification since it is not applicable for the mirror node.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
Seems like during state initialization when we do migrations we have the options to pass previous version (`SoftwareVersion`).

Currently we are passing null as previous version which later on during the migrations is checked if null then do all genesis startup logic and validations which is pretty big operation and takes a lot of time.
This is a good approach to do on empty db like integration tests startup.

But after testing with mainnet snapshots we are getting into trouble since our db is already populated with all system accounts etc and we get into failures.

This pr assigns a previous version if db is not empty if completely empty then we should proceed with genesis logic otherwise couple of our singletons querying for record files will start failing.

Changes:
`MirrorNodeState` - add logic to set previous version during startup on non empty db.
tests..

**Related issue(s)**:

Fixes #10555

**Notes for reviewer**:
During startup with non genesis we need to set latest recordFile in context since it's being read in our custom singleton implementations during the init.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java [hunk 1]
```diff
@@ -101,15 +105,25 @@ private void init() {
...
+        Optional<RecordFile> latest = recordFileRepository.findLatest();
+        final var bootstrapConfig = new BootstrapConfigProviderImpl().getConfiguration();
+        final var currentSemanticVersion =
+                bootstrapConfig.getConfigData(VersionConfig.class).servicesVersion();
+        final var currentVersion = new ServicesSoftwareVersion(currentSemanticVersion);
+        final var previousVersion = latest.isEmpty()
+                ? null
+                : new ServicesSoftwareVersion(SemanticVersion.newBuilder()
+                        .minor(currentSemanticVersion.minor() - 1)
+                        .build());
```
[the remark this answers is not in the document]
Comment (bilyana-gospodinova) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java:117]: Will this be an issue if the previous version results to a version that does not actually exist? Have you tested it? Or if the current version has minor == 0?

**Review by bilyana-gospodinova — DISMISSED** [review]
LGTM

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java (hunk 1 above)
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java:117]: Think this means we would always attempt to run migrations from current-1 to current on startup instead of only doing that once. Are we sure that's what we want? Maybe we should set them equal or use a stateful previous?

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java [hunk 2]
```diff
@@ -101,15 +105,25 @@ private void init() {
             return;
         }
 
+        Optional<RecordFile> latest = recordFileRepository.findLatest();
+        final var bootstrapConfig = new BootstrapConfigProviderImpl().getConfiguration();
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java:109]: Can we use mirrorNodeEvmProperties.getConfiguration() here?

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java [hunk 3]
```diff
@@ -101,15 +105,25 @@ private void init() {
...
+        final var currentSemanticVersion =
+                bootstrapConfig.getConfigData(VersionConfig.class).servicesVersion();
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java:111]: Does this have an accurate version reflecting the library version? I see in VersionConfig it defaults to 0.0.0.

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java (hunk 2 above)
Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/MirrorNodeState.java]: We can addressed.

**Review by steven-sheehy — APPROVED** [review]
