### PR TITLE
Fix acceptance tests that were failing with INSUFFICIENT_GAS

### LINKED ISSUE #11121: Fix failing acceptance tests with the latest version of services and hedera app
### Problem

Service team have invreased the cost for contract deploy and contract create so with the latest versions of services 62.1 and above we have failing acceptance tests related to contract deploy, contract create. 

### Solution

Fix the failing acceptance tests

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by nickeynikolovv**
With the latest version of services 0.62 and above, there were some changes in gas prices for contract deploy and contract create and those changes were causing some failures in our acceptance tests. 
- Update the gas that is passed for contract create from 3_000_000 to 5_250_000
- update the operator USD balance from 70 to 75
- update the transferred amount of hbars from operator to ethereum signer account from 5 to 30

**Related issue(s)**:

Fixes #11121

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by bilyana-gospodinova — DISMISSED** [review]

**Review by kselveliev — DISMISSED** [review]

**Review by bilyana-gospodinova — APPROVED** [review]

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public void createAccountWithEvmAddressAlias() {
                 .getPublicKey()
                 .toAccountId(commonProperties.getShard(), commonProperties.getRealm());
 
-        networkTransactionResponse = accountClient.sendCryptoTransfer(ethereumSignerAccount, Hbar.from(5L), null);
+        networkTransactionResponse = accountClient.sendCryptoTransfer(ethereumSignerAccount, Hbar.from(30L), null);
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java:62]: It looks like there's an hbar leak here. We're lazy creating this account but not deleting it and transferring its remaining funds back to the treasury at the end?

Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java:62]: Are we sure this account needs all 30 hbars? Can we reduce this any?

Comment (steven-sheehy) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java:62]: Probably what we should do is replace `ethereumSignerAccount` and `ethereumSignerPrivateKey` with an `ExpandedAccountId ethereumSigner`. Then add an `AccountClient.addAliasAccount(ethereumSigner)` that adds it to the `AccountClient.accountIds` for automatic cleanup at the end.

**Review by kselveliev — APPROVED** [review]

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java (hunk 1 above)
Comment (nickeynikolovv) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/EthereumFeature.java]: Removed the hollow account creation and added a normal account as a signer

File: test/src/test/resources/features/contract/ethereum.feature [hunk 2]
```diff
@@ -3,9 +3,7 @@ Feature: Ethereum transactions Coverage Feature
 
   Scenario Outline: Validate Ethereum Contract create and call
 
-
   Given I successfully created a signer account with an EVM address alias
-  Then validate the signer account and its balance
```
Comment (steven-sheehy) [inline test/src/test/resources/features/contract/ethereum.feature:8]: Should remove the equivalent java code as well

Comment (nickeynikolovv) [reply test/src/test/resources/features/contract/ethereum.feature:8]: removed

**Review by steven-sheehy — APPROVED** [review]

**Review by xin-hedera — APPROVED** [review]
LGTM
