### PR TITLE
Adjust k6 tests to work with static snapshot

### LINKED ISSUE #13375: Fix copy live environment issues when using static snapshot
### Problem

After running k6 tests, there are issues with apis that bind timestamp ranges. Also, fixed issue with importer scaling down at the wrong time. 

### Solution

- [ ] add max timestamp to relevant k6 tests
- [ ] scale importer down after helm release of new release is complete

### Alternatives

_No response_

### LINKED ISSUE #13406: Update copy live environment workflow to work without flux
### Problem

There are use cases for this workflow where flux is not running in the target cluster. We should update the scripts to allow user to manually handle chart deployment

### Solution

1. When resuming any charts (currently dependent on flux and helm release status) we should add appropriate checks to make sure expected components are deployed. 

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by jnels124**
**Description**:
this pr enhances previous work done to use static snapshots
* modifies k6 tests for endpoints that bind timestamp range to include an upper bound
* enhance copy script to scale down importer at appropriate time 
* enhance copy script to work without clean target

**Related issue(s)**:

Fixes #13375 
Fixes #13406

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: tools/k6/src/rest/test/transactionsCryptoCreateAccountDebit.js
Comment (jnels124) [inline tools/k6/src/rest/test/transactionsCryptoCreateAccountDebit.js:1]: test disabled several years ago and no longer used

File: tools/k6/src/rest/test/accountsId.js [hunk 1]
```diff
@@ -6,7 +6,8 @@ import {isSuccess, RestTestScenarioBuilder} from '../libex/common.js';
 
 const urlTag = '/accounts/{accountId}';
 
-const getUrl = (testParameters) => `/accounts/${testParameters['DEFAULT_ACCOUNT_ID']}`;
+const getUrl = (testParameters) =>
+  `/accounts/${testParameters['DEFAULT_ACCOUNT_ID']}?timestamp=lte:${testParameters['DEFAULT_MAX_BLOCK_TIMESTAMP']}&limit=${testParameters['DEFAULT_LIMIT']}`;
```
Comment (jnels124) [inline tools/k6/src/rest/test/accountsId.js]: note added limit to this call

**Review by steven-sheehy — DISMISSED** [review]

**Review by steven-sheehy — APPROVED** [review]

**Review by xin-hedera — APPROVED** [review]
LGTM
