### PR TITLE
Fix stream file archive path when groupByDay is disabled

### LINKED ISSUE #12284: Stream files are archived to incorrect path when groupByDay is disabled
### Description

When configured with `groupByDay=false`, importer will save record stream files in the following folder:

```bash
$ ls -lR data/streams/2025-10-24T13_25_50.372197593Z.rcd.gz
total 0
drwxr-xr-x  9 xin  staff  288 Oct 27 09:30 recordstreams

data/streams/2025-10-24T13_25_50.372197593Z.rcd.gz/recordstreams:
total 0
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.3
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.4
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.5
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.6
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.7
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.8
drwxr-xr-x  3 xin  staff  96 Oct 27 09:30 record0.0.9

data/streams/2025-10-24T13_25_50.372197593Z.rcd.gz/recordstreams/record0.0.3:
total 16
-rw-r--r--  1 xin  staff  6451 Oct 27 09:30 2025-10-24T13_25_50.372197593Z.rcd.gz

data/streams/2025-10-24T13_25_50.372197593Z.rcd.gz/recordstreams/record0.0.4:
total 16
-rw-r--r--  1 xin  staff  6451 Oct 27 09:30 2025-10-24T13_25_50.372197593Z.rcd.gz
```

The correct path without grouping should be `data/streams/recordstreams/record0.0.3/{filename}`

### Steps to reproduce

Run importer with `groupByDay=false` and `downloader.record.writeFiles=true`.

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.142.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the incorrect archive path issue.

**Related issue(s)**:

Fixes #12284

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: importer/src/main/java/org/hiero/mirror/importer/ImporterProperties.java [hunk 1]
```diff
@@ -76,7 +76,8 @@ public Path getArchiveDestinationFolderPath(StreamFileData streamFileData) {
         if (groupByDay) {
             return getStreamPath().resolve(streamFileData.getFilename().substring(0, 10));
         }
-        return getStreamPath().resolve(streamFileData.getFilename());
+
+        return getStreamPath();
```
Comment (steven-sheehy) [inline importer/src/main/java/org/hiero/mirror/importer/ImporterProperties.java:80]: Is it possible to have an integration test in downloader so we can catch future regressions?

Comment (xin-hedera) [reply importer/src/main/java/org/hiero/mirror/importer/ImporterProperties.java:80]: added test coverage
