### PR TITLE
K6 web3 tests fixes and data adaptation

### LINKED ISSUE #10736: Update k6 env vars for mainnet
### Problem

After adding the new k6 test environment variables in this PR - https://github.com/hiero-ledger/hiero-mirror-node/pull/10653 we need to set the correct values for mainnet in the deploy branch too.

### Solution

Create a PR to the deploy branch with the correct values for mainnet.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by nickeynikolovv**
This PR fixes some issues with the k6 tests in order to use a newly added data in deploy branch

**Related issue(s)**:

Fixes #10736 

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/k6/src/web3/test/contractCallEstimateDissociateTokens.js [hunk 1]
```diff
@@ -9,6 +9,9 @@ const token = __ENV.FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS;
 const selector = '0x2390c1fa'; //dissociateTokensExternal
 const runMode = __ENV.RUN_WITH_VARIABLES;
 const testName = 'estimateDissociateTokens';
+const data =
+  '0000000000000000000000000000000000000000000000000000000000000040' +
+  '0000000000000000000000000000000000000000000000000000000000000001';
```
Comment (steven-sheehy) [inline hedera-mirror-test/k6/src/web3/test/contractCallEstimateDissociateTokens.js:14]: Add comments at the end describing what they represent

File: hedera-mirror-test/k6/README.md [hunk 2]
```diff
@@ -118,33 +118,34 @@ The following parameters can be used to configure a rosetta test:
...
+| SERIAL_NUMBER                                                 |         | 64 character hex encoded nft serial number without `0x` prefix                                                                                                                    |
+| SPENDER_ADDRESS                                               |         | 64 character hex encoded account address without `0x` prefix                                                                                                                      |
+| TOKEN_ADDRESS                                                 |         | 64 character hex encoded token address without `0x` prefix                                                                                                                        |
+| TOKENS_FREEZE_KEY_ACCOUNT_ADDRESS                             |         | 64 character hex encoded account evm address without `0x` prefix - a freeze key account for FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS and NON_FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS |
```
Comment (steven-sheehy) [inline hedera-mirror-test/k6/README.md:146]: Prefer `TOKEN_FREEZE_KEY_ACCOUNT_ADDRESS`

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-test/k6/src/web3/test/contractCallEstimateDissociateTokens.js (hunk 1 above)
Comment (nickeynikolovv) [reply hedera-mirror-test/k6/src/web3/test/contractCallEstimateDissociateTokens.js:15]: Done

File: hedera-mirror-test/k6/README.md (hunk 2 above)
Comment (nickeynikolovv) [reply hedera-mirror-test/k6/README.md]: Done

File: hedera-mirror-test/k6/src/web3/test/contractCallEstimateFreezeNft.js [hunk 3]
```diff
@@ -4,7 +4,7 @@ import {ContractCallTestScenarioBuilder} from './common.js';
 import {ContractCallEstimateTestTemplate} from './commonContractCallEstimateTemplate.js';
 
 const contract = __ENV.ESTIMATE_PRECOMPILE_CONTRACT;
-const account = __ENV.NON_FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ASSOCIATED_ACCOUNT_ADDRESS;
+const account = __ENV.TOKEN_FREEZE_KEY_ACCOUNT_ADDRES;
```
Comment (bilyana-gospodinova) [inline hedera-mirror-test/k6/src/web3/test/contractCallEstimateFreezeNft.js:7]: nit: One more "S" at the end is needed

Comment (nickeynikolovv) [reply hedera-mirror-test/k6/src/web3/test/contractCallEstimateFreezeNft.js]: Fixed

File: hedera-mirror-test/k6/src/web3/test/contractCallEstimateUnfreezeToken.js [hunk 4]
```diff
@@ -4,10 +4,10 @@ import {ContractCallTestScenarioBuilder} from './common.js';
 import {ContractCallEstimateTestTemplate} from './commonContractCallEstimateTemplate.js';
 
 const contract = __ENV.ESTIMATE_PRECOMPILE_CONTRACT;
-const account = __ENV.FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ASSOCIATED_ACCOUNT_ADDRESS;
+const account = __ENV.TOKEN_FREEZE_KEY_ACCOUNT_ADDRESS;
 const token = __ENV.FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS;
 const runMode = __ENV.RUN_WITH_VARIABLES;
-const selector = '0x9333700b'; //freezeTokenExternal
+const selector = '0xe95a71e5'; //freezeTokenExternal
```
Comment (bilyana-gospodinova) [inline hedera-mirror-test/k6/src/web3/test/contractCallEstimateUnfreezeToken.js:10]: I think the comment needs to be updated with the new function selector - "unfreezeTokenExternal".

File: hedera-mirror-test/k6/src/web3/test/contractCallEstimateFreezeToken.js [hunk 5]
```diff
@@ -4,10 +4,10 @@ import {ContractCallTestScenarioBuilder} from './common.js';
 import {ContractCallEstimateTestTemplate} from './commonContractCallEstimateTemplate.js';
 
 const contract = __ENV.ESTIMATE_PRECOMPILE_CONTRACT;
-const account = __ENV.FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ASSOCIATED_ACCOUNT_ADDRESS;
+const account = __ENV.TOKEN_FREEZE_KEY_ACCOUNT_ADDRESS;
 const token = __ENV.FUNGIBLE_TOKEN_WITH_FREEZE_KEY_ADDRESS;
 const runMode = __ENV.RUN_WITH_VARIABLES;
-const selector = '0xe95a71e5'; //unfreezeTokenExternal
+const selector = '0x9333700b'; //unfreezeTokenExternal
```
Comment (bilyana-gospodinova) [inline hedera-mirror-test/k6/src/web3/test/contractCallEstimateFreezeToken.js:10]: I think the comment needs to be updated here as well:
1. 0x9333700b == freezeTokenExternal
2. 0xe95a71e5 == unfreezeTokenExternal

Comment (nickeynikolovv) [reply hedera-mirror-test/k6/src/web3/test/contractCallEstimateFreezeToken.js]: fixed

**Review by steven-sheehy — APPROVED** [review]

**Review by bilyana-gospodinova — APPROVED** [review]

**Comment by steven-sheehy** [comment]
spotless problem

**Review by steven-sheehy — APPROVED** [review]
