### PR TITLE
Ensure latest exchange rate is used in web3

### LINKED ISSUE #12907: Mirror node API underestimates gas for hollow account creation transfers
### Description

When using the mirror node's `/api/v1/contracts/call` endpoint to estimate gas for a plain HBAR transfer to an EVM address that does not yet exist on the network (hollow account creation), the returned gas estimate is too low, causing the transaction to fail when submitted with that gas limit.

In my scenario, the mirror node estimated **483,526** gas, but the actual gas required was **575,521** (~16% higher). The discrepancy appears to be caused by the mirror node not factoring in the cost of lazy/hollow account creation when the target EVM address has no existing account on the network. 

This seems to work for a regular HBAR transfer of course so no issue there.

### Steps to reproduce

1. Identify a `TO` EVM address that does not yet have an account on Hedera testnet (i.e., will trigger hollow account creation).

2. Estimate gas via the mirror node:

```bash
curl -s -X POST "https://testnet.mirrornode.hedera.com/api/v1/contracts/call" \
  -H "Content-Type: application/json" \
  -d '{
    "from": "0xA98556A4deeB07f21f8a66093989078eF86faa30",
    "to": "0x52A36463684032Ccbfb4f578c351571432F52364",
    "value": 10000000,
    "estimate": true
  }'
```

**Returned estimate:** `0x00000000000760c6` = **483,526 gas**

3. Submit the transaction using the returned gas estimate as the gas limit:

```bash
cast send 0x52A36463684032Ccbfb4f578c351571432F52364 \
  --value 0.1ether \
  --rpc-url https://testnet.hashio.io/api \
  --private-key $PRIVATE_KEY \
  --gas-limit 483526
```

**Result:** Transaction fails with `status: 0 (failed)`
- TX hash: `0x0cfdba7b859b01d5e42b26972cb5b8fd1d0a960f790aa9a18b1fb5ad42ee28d9`

4. Retry with a higher gas limit (1,000,000):

```bash
cast send 0x52A36463684032Ccbfb4f578c351571432F52364 \
  --value 0.1ether \
  --rpc-url https://testnet.hashio.io/api \
  --private-key $PRIVATE_KEY \
  --gas-limit 1000000
```

**Result:** Transaction succeeds with `status: 1 (success)`
- TX hash: `0x95a0b18b817efdbff2396d6c896d4fb10ce6a62d3860328ae419133509ad3957`
- Actual gas used: **575,521**
- `contractAddress` field populated, confirming hollow account creation occurred

### Additional context

Any client relying on the mirror node's gas estimation(this includes the JSON RPC Relay that also utilizes Mirror Nodes) for HBAR transfers will experience transaction failures when sending to new/unfunded EVM addresses. This is a common scenario for onboarding new users.

### Hedera network

testnet, other

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by bilyana-gospodinova**
**Description**:
After investigation of a gas estimate issue in hollow account creation it turned out that there are 2 exchange rates used at the same time in the mirror node. 
- The first one is the latest found file in the DB. 
- The second one is the default exchange rate file defined in the configurations.
These two exchange rates are used in parallel for the same calculation resulting in incorrect final value. The reason for that is `BlockStreamInfoSingleton` returns always a default instance. This instance is then used in initializing the `ExchangeRateManager` and since the lastHandleTime == 0, it treats the environment as a genesis one and uses the default exchange rate. At the same time in other parts of the code we use the latest available file in the DB.
With this PR we make sure that only the correct file is used - the latest one from the DB or in case we are in a historical call - the latest file that at the given timestamp.

Fixes #12907

### CODE REVIEW

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/client/EthereumClient.java
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/client/EthereumClient.java:1]: Is there an acceptance test we can add/adjust to ensure we're calculating accurate gas e2e?

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 1]
```diff
@@ -36,6 +46,15 @@ public String getServiceName() {
     @SneakyThrows
     @Override
     public ExchangeRateSet get() {
-        return cachedExchangeRateSet;
+        final var current = systemFileLoader.load(exchangeRatesFileId, getCurrentTimestamp());
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Shouldn't we load this at the block timestamp instead of now? If so, we should also ensure the other area that loads the file uses the same block timestamp.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 2]
```diff
@@ -36,6 +46,15 @@ public String getServiceName() {
...
+        return current != null ? ExchangeRateSet.PROTOBUF.parse(current.contents()) : cachedExchangeRateSet;
+    }
+
+    private FileID getExchangeRateFileId() {
+        return FileID.newBuilder()
+                .shardNum(CommonProperties.getInstance().getShard())
+                .realmNum(CommonProperties.getInstance().getRealm())
+                .fileNum(systemEntity.exchangeRateFile().getNum())
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]:
```suggestion
        final var fileId = systemEntity.exchangeRateFile();
        return FileID.newBuilder()
                .shardNum(fileId.getShard())
                .realmNum(fileId.getRealm())
                .fileNum(fileId.getNum())
```

**Comment by steven-sheehy** [comment]
There's another problem that `SystemFileLoader.load(key, timestamp)` only takes into account the key for caching. So if we call `load(key, now)` and right after do `load(key, oneYearAgo)` the method will return the latest exchange rate for both. Thus the historical call will have inaccurate gas estimation due to the gasPrice being off.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 1 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Right, I changed it to reflect the block timestamp. This way we will be able to load historical exchange rates correctly. Nice catch.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 2 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Addressed

**Comment by bilyana-gospodinova** [comment]
> There's another problem that `SystemFileLoader.load(key, timestamp)` only takes into account the key for caching. So if we call `load(key, now)` and right after do `load(key, oneYearAgo)` the method will return the latest exchange rate for both. Thus the historical call will have inaccurate gas estimation due to the gasPrice being off.

True. I updated the cache key to include the timestamp as well in order to mitigate this issue.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 3]
```diff
@@ -71,7 +71,7 @@ public class SystemFileLoader {
     @Cacheable(
             cacheManager = CACHE_MANAGER_SYSTEM_FILE_MODULARIZED,
             cacheNames = CACHE_NAME_MODULARIZED,
-            key = "#key",
+            key = "#key.toString() + '-' + #consensusTimestamp",
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: You can just remove the key param and by default it should use all fields. This would help avoid the costly reflection of using expressions.

File: web3/src/main/java/org/hiero/mirror/web3/state/Utils.java [hunk 4]
```diff
@@ -50,4 +51,9 @@ public static Timestamp convertToTimestamp(final long timestamp) {
         var instant = Instant.ofEpochSecond(0, timestamp);
         return new Timestamp(instant.getEpochSecond(), instant.getNano());
     }
+
+    public static long getCurrentTimestamp() {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/Utils.java:57]: Is this still used?

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 5]
```diff
@@ -36,6 +47,38 @@ public String getServiceName() {
...
+        cache.put(timestamp, rates);
+        return rates;
+    }
+
+    private long resolveTimestamp(final ContractCallContext context) {
+        final var params = context.getCallServiceParameters();
+        final var block = params != null ? params.getBlock() : BlockType.LATEST;
+        return block == BlockType.LATEST
+                ? Long.MAX_VALUE
+                : context.getRecordFile().getConsensusEnd();
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]:
```suggestion
        return context.getTimestamp().orElse(Long.MAX_VALUE);
```

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 3 above)
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: This could cause a performance regression since now it will load system files every 2s instead of every 10 min for historical requests. Not sure if there's anything we can do to fix though as this approach does provide accurate data. We could try to normalize the timestamps to round up/down to every 10 minute mark, but that rounding could cross a system file update and return inaccurate data. Not sure we should change anything, just noting a concern and interested in your thoughts.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

**Comment by steven-sheehy** [comment]
Can merge from main to fix block acceptance

File: web3/src/main/java/org/hiero/mirror/web3/state/Utils.java (hunk 4 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/Utils.java:57]: Yes, in `FileReadableKVState`.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 6]
```diff
@@ -36,6 +47,38 @@ public String getServiceName() {
...
+        }
+
+        final var file = systemFileLoader.load(exchangeRatesFileId, timestamp);
+        final var rates = file != null ? ExchangeRateSet.PROTOBUF.parse(file.contents()) : cachedExchangeRateSet;
+        cache.put(timestamp, rates);
+        return rates;
+    }
+
+    private long resolveTimestamp(final ContractCallContext context) {
+        final var params = context.getCallServiceParameters();
```
Comment (IvanKavaldzhiev) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: It makes sense to have the `resolveTimestamp` method hidden inside the ContractCallContext.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 5 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 6 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: When comment https://github.com/hiero-ledger/hiero-mirror-node/pull/12943#discussion_r2824157813 gets addressed, this method will not be needed anymore.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 3 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Perhaps we should open a task to add more metrics that detect how much actually historical data is fetched by users. If the usage is low, we won't have that many queries after all.

Comment (xin-hedera) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: exchange rate updates every 60 minutes and each exchange rate file has both the current rate and the next rate. In general, the next rate in the N-1 exchange rate file is the current rate in the N exchange file. Also, each rate has a expiration timestamp in epoch seconds.

We should do heavy optimization based on the above characteristics and cache the rate as long as we want, instead of loading the exchange rate file every 2s.

Comment (steven-sheehy) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Yes, but this method is used by different system files, not just exchange rate. So they each have different caching characteristics. We'd have to move the caching to a different layer and make it smarter per file. Maybe open a ticket to track.

Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Analyzing the past file update transactions (https://hashscan.io/mainnet/transactions?type=fileupdate&p=1&k=1771516857.974717546) it seems like the file gets updated in the first minute of the next round hour. For example, the exchange rate gets updated at about 5:00:57.4564. So if we round down all queried timestamps between 5:00:00 and 6:00:00 to 5:02:00 (and the cache entry becomes (fileId, 5:02:00 as timestamp)) we can cache the result for about an hour and all transactions between 5:00:00 and 6:00:00 should have a valid exchange rate as they would match the file from 5:00:57.4564 anyway. Am I right?

Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: I implemented this suggestion. @xin-hedera, @steven-sheehy, the PR is ready for re-review. I would appreciate your thoughts on this.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 7]
```diff
@@ -3,24 +3,37 @@
...
 
 @Named
 final class MidnightRatesSingleton implements SingletonState<ExchangeRateSet> {
 
+    private static final long NANOS_PER_HOUR = 3600L * 1_000_000_000L;
+    private static final long NANOS_PER_TWO_MINUTES = 2L * 60L * 1_000_000_000L;
+
     private final ExchangeRateSet cachedExchangeRateSet;
+    private final SystemFileLoader systemFileLoader;
+    private final SystemEntity systemEntity = new SystemEntity(CommonProperties.getInstance());
```
Comment (xin-hedera) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: there is a `systemEntity` bean, 
```suggestion
    private final SystemEntity systemEntity;
```

and inject it through the constructor.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 8]
```diff
@@ -36,6 +49,41 @@ public String getServiceName() {
...
     @Override
     public ExchangeRateSet get() {
-        return cachedExchangeRateSet;
+        final var context = ContractCallContext.get();
+        long timestamp = context.getTimestamp().orElse(Utils.getCurrentTimestamp());
+        // Round the timestamp to the nearest hour and two minutes - the file gets updated every hour,
+        // it gets available until the first or the second minute of that hour. All timestamps up until
+        // the next file update would match that file, so parse the timestamp here to reduce the number
+        // of the DB calls and cache entries.
+        timestamp = roundDownToHourAndTwoMinutes(timestamp);
```
Comment (xin-hedera) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Since we want to round the timestamp in order to map many distinct timestamps in the same range to a single key and thus make efficient use of the cache, we can just round it down to the closest hour as the logic is simpler and still correct.

It's correct because the worst scenario is when we round a timestamp `T` to hour `N`, we'll get a exchange rate published in hour `N-1`, not the one published right before `T`. However, in that case, the logic depending on the exchangerate set should just pick the `nextRate`.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 9]
```diff
@@ -82,6 +91,19 @@ public class SystemFileLoader {
...
 
+    @Cacheable(
+            cacheManager = CACHE_MANAGER_SYSTEM_FILE_MODULARIZED,
+            cacheNames = CACHE_NAME_MODULARIZED,
+            unless = "#result == null")
+    public @Nullable File loadExchangeRates(long consensusTimestamp) {
+        var systemFile = getSystemFiles().get(exchangeRateFileId);
+        if (systemFile == null) {
+            return null;
+        }
```
Comment (xin-hedera) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java:122]: this can't be null.

```suggestion
```

File: web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java [hunk 10]
```diff
@@ -35,6 +35,9 @@ public class CacheProperties {
     @NotBlank
     private String fee = "expireAfterWrite=10m,maximumSize=20,recordStats";
 
+    @NotBlank
+    private String exchangeRate = "expireAfterWrite=60m,maximumSize=20,recordStats";
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java]: Need to document

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 11]
```diff
@@ -82,6 +91,19 @@ public class SystemFileLoader {
         return loadWithRetry(key, consensusTimestamp, systemFile);
     }
 
+    @Cacheable(
+            cacheManager = CACHE_MANAGER_SYSTEM_FILE_MODULARIZED,
+            cacheNames = CACHE_NAME_MODULARIZED,
+            unless = "#result == null")
+    public @Nullable File loadExchangeRates(long consensusTimestamp) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: This breaks the interface of the SystemFileLoader API. Now there's two ways to get the same file with different behaviors depending upon which you call. It's not generic and reusable across multiple places now as the client has to know which to call based upon file id.

Please revert this change and add conditional logic inside existing `load()` that delegates to different caches depending upon file id. You'll have to create the caches manually from the properties or inject multiple cache managers.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Shouldn't we also fix it so that other system files load at the correct timestamp from the cache? Particularly it seems like the fee schedule could be wildly off if it loads and caches the latest then a historical call for a block from a year ago comes in during the next 10 minutes.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 3 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Removed String key building.

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 7 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 8 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Addressed - changed the rounding down to the nearest hour. Removed the 2-minute logic.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 9 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java:122]: Removed

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 11 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: The fee schedules do not change very often as this will require council voting, I think. Even so, you are right that we should make the loading consistent for all files. I updated the `load()` method to search for the correct cache manager, use different caching depending on the file and synced the fee schedules and exchange rates with the same caching property so that they will be matching.

File: web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java (hunk 10 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java]: Added

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java [hunk 12]
```diff
@@ -45,10 +45,10 @@ public class EvmConfiguration {
     public static final String CACHE_NAME_ALIAS = "alias";
     public static final String CACHE_NAME_EXCHANGE_RATE = "exchangeRate";
     public static final String CACHE_NAME_FEE_SCHEDULE = "feeSchedule";
-    public static final String CACHE_NAME_MODULARIZED = "cacheModularized";
     public static final String CACHE_NAME_NFT = "nft";
     public static final String CACHE_NAME_NFT_ALLOWANCE = "nftAllowance";
     public static final String CACHE_NAME_RECORD_FILE_LATEST = "latest";
+    public static final String CACHE_NAME_SYSTEM_FILE = "cacheSystemFile";
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]:
```suggestion
    public static final String CACHE_NAME_SYSTEM_FILE = "systemFile";
```

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java [hunk 13]
```diff
@@ -35,7 +35,7 @@ public class EvmConfiguration {
     public static final String CACHE_MANAGER_RECORD_FILE_TIMESTAMP = "recordFileTimestamp";
     public static final String CACHE_MANAGER_SLOTS_PER_CONTRACT = "slotsPerContract";
     public static final String CACHE_MANAGER_SYSTEM_FILE = "systemFile";
-    public static final String CACHE_MANAGER_SYSTEM_FILE_MODULARIZED = "systemFileModularized";
+    public static final String CACHE_MANAGER_EXCHANGE_RATES_SYSTEM_FILE = "systemFileExchangeRates";
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]: Rename and sort

```suggestion
    public static final String CACHE_MANAGER_EXCHANGE_RATE = "exchangeRate";
```

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java [hunk 14]
```diff
@@ -140,15 +140,15 @@ CacheManager cacheManagerTokenType() {
     @Bean(CACHE_MANAGER_SYSTEM_FILE)
     CacheManager cacheManagerSystemFile() {
         final CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
-        caffeineCacheManager.setCacheNames(Set.of(CACHE_NAME_EXCHANGE_RATE, CACHE_NAME_FEE_SCHEDULE));
-        caffeineCacheManager.setCacheSpecification(cacheProperties.getFee());
+        caffeineCacheManager.setCacheNames(Set.of(CACHE_NAME_SYSTEM_FILE));
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]:
```suggestion
        caffeineCacheManager.setCacheNames(Set.of(CACHE_NAME));
```

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java [hunk 15]
```diff
@@ -140,15 +140,15 @@ CacheManager cacheManagerTokenType() {
...
         return caffeineCacheManager;
     }
 
-    @Bean(CACHE_MANAGER_SYSTEM_FILE_MODULARIZED)
-    CacheManager cacheManagerSystemFileModularized() {
+    @Bean(CACHE_MANAGER_EXCHANGE_RATES_SYSTEM_FILE)
+    CacheManager cacheManagerSystemFileExchangeRates() {
         final CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
-        caffeineCacheManager.setCacheNames(Set.of(CACHE_NAME_MODULARIZED));
+        caffeineCacheManager.setCacheNames(Set.of(CACHE_NAME_EXCHANGE_RATE, CACHE_NAME_FEE_SCHEDULE));
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]: Since the file id is part of the key and they use the same cache spec, we can just have one cache for both. We should use the `default` name if only single cache in cache manager.

```suggestion
        caffeineCacheManager.setCacheNames(Set.of(CACHE_NAME));
```

File: web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java [hunk 16]
```diff
@@ -33,7 +33,10 @@ public class CacheProperties {
     private String entity = ENTITY_CACHE_CONFIG;
 
     @NotBlank
-    private String fee = "expireAfterWrite=10m,maximumSize=20,recordStats";
+    private String systemFile = "expireAfterWrite=10m,maximumSize=20,recordStats";
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java]: nit: sort

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java [hunk 17]
```diff
@@ -4,23 +4,37 @@
...
+import org.hiero.mirror.common.domain.SystemEntity;
+import org.hiero.mirror.web3.common.ContractCallContext;
 import org.hiero.mirror.web3.evm.properties.EvmProperties;
+import org.hiero.mirror.web3.state.SystemFileLoader;
+import org.hiero.mirror.web3.state.Utils;
 
 @Named
 final class MidnightRatesSingleton implements SingletonState<ExchangeRateSet> {
 
+    private static final long NANOS_PER_HOUR = 3600L * 1_000_000_000L;
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]:
```suggestion
    private static final long NANOS_PER_HOUR = 3600L * DomainUtils.NANOS_PER_SECOND;
```

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 18]
```diff
@@ -193,5 +236,30 @@ private byte[] createMockAddressBook() {
...
+        return manager.getCache(cacheName);
+    }
+
     private record SystemFile(File genesisFile, Codec<?> codec) {}
+
+    private record CacheKey(long shard, long realm, long fileNum, long timestamp) {
+
+        static CacheKey of(FileID fileId, long consensusTimestamp) {
+            return new CacheKey(fileId.shardNum(), fileId.realmNum(), fileId.fileNum(), consensusTimestamp);
+        }
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: FileID is itself hashable so we can use it directly.

```suggestion
    private record CacheKey(FileID fileId, long timestamp) {
    }
```

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 19]
```diff
@@ -193,5 +236,30 @@ private byte[] createMockAddressBook() {
...
     }
 
+    /**
+     * Returns the cache for the given file id: exchange rate file and fee schedule file use the
+     * exchange-rates cache manager (longer TTL). Other system files use the default manager.
+     *
+     * @param key the file id
+     * @return the cache for this file id, or null if the manager has no such cache
+     */
+    private Cache getCacheForKey(@NonNull FileID key) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Can we remove NonNull and use `@NullMarked` on the class?

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 20]
```diff
@@ -193,5 +236,30 @@ private byte[] createMockAddressBook() {
...
+        final var isExchangeRate = key.equals(exchangeRateFileId);
+        final var isFeeSchedule = key.equals(feeSchedulesFileId);
+        final var useExchangeRatesManager = isExchangeRate || isFeeSchedule;
+        final var manager = useExchangeRatesManager ? exchangeRatesCacheManager : defaultSystemFileCacheManager;
+        final var cacheName = isExchangeRate
+                ? CACHE_NAME_EXCHANGE_RATE
+                : isFeeSchedule ? CACHE_NAME_FEE_SCHEDULE : CACHE_NAME_SYSTEM_FILE;
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Can simplify once we change to use one cache for both exchange rates and fees.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 21]
```diff
@@ -68,12 +90,33 @@ public class SystemFileLoader {
...
-            key = "#key",
-            unless = "#result == null")
+    /**
+     * Load system file by id and consensus timestamp. Uses a cache manager chosen by file id:
+     * exchange rate file uses {@value org.hiero.mirror.web3.evm.config.EvmConfiguration#CACHE_MANAGER_EXCHANGE_RATES_SYSTEM_FILE}
+     * (e.g. longer TTL); other system files use
+     * {@value org.hiero.mirror.web3.evm.config.EvmConfiguration#CACHE_MANAGER_SYSTEM_FILE}.
+     */
     public @Nullable File load(@NonNull FileID key, long consensusTimestamp) {
+        final var cacheKey = CacheKey.of(key, consensusTimestamp);
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Avoid naming clash

```suggestion
public @Nullable File load(@NonNull FileID fileId, long consensusTimestamp) {
        final var cacheKey = CacheKey.of(fileId, consensusTimestamp);
```

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java [hunk 22]
```diff
@@ -68,12 +90,33 @@ public class SystemFileLoader {
...
+        final var cache = getCacheForKey(key);
+        if (cache == null) {
+            return loadFromDB(key, consensusTimestamp);
+        }
+        // Try to return the value from the cache
+        var wrapper = cache.get(cacheKey);
+        if (wrapper != null) {
+            return (File) wrapper.get();
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Avoid allocating wrapper

```suggestion
        var file = cache.get(cacheKey, File.class);
        if (file != null) {
            return file;
```

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java (hunk 12 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]: Renamed

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java (hunk 13 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]: Renamed

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java (hunk 14 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java (hunk 15 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/evm/config/EvmConfiguration.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java (hunk 16 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/repository/properties/CacheProperties.java]: Sorted

File: web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java (hunk 17 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/singleton/MidnightRatesSingleton.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 18 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 19 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Sure, addressed.

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 20 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 21 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Addressed

File: web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java (hunk 22 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/SystemFileLoader.java]: Addressed

**Review by steven-sheehy — APPROVED** [review]
LGTM
