### PR TITLE
Return null in case token with negative num value is being read

### LINKED ISSUE #12082: InvalidEntityException: Invalid entity ID
### Description

The following exception was noticed in Grafana logs. Seems like some overflow issue.

```
2025-09-28 14:38:48.415	
2025-09-28T11:38:48.415Z ERROR tomcat-handler-819627 c.h.n.a.w.h.DispatchProcessor Possibly CATASTROPHIC failure - exception thrown while handling dispatch org.hiero.mirror.common.exception.InvalidEntityException: Invalid entity ID: 0.0.-8400402504822257042
	at org.hiero.mirror.common.domain.entity.EntityId.encode(EntityId.java:77)
	at org.hiero.mirror.common.domain.entity.EntityId.of(EntityId.java:138)
	at com.hedera.services.utils.EntityIdUtils.toEntityId(EntityIdUtils.java:101)
	at org.hiero.mirror.web3.state.CommonEntityAccessor.get(CommonEntityAccessor.java:38)
	at org.hiero.mirror.web3.state.keyvalue.TokenReadableKVState.readFromDataSource(TokenReadableKVState.java:76)
	at org.hiero.mirror.web3.state.keyvalue.TokenReadableKVState.readFromDataSource(TokenReadableKVState.java:47)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at org.hiero.mirror.web3.state.core.MapWritableKVState.readFromDataSource(MapWritableKVState.java:26)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at com.swirlds.state.spi.WritableKVStateBase.get(WritableKVStateBase.java:84)
	at com.swirlds.state.spi.WrappedWritableKVState.readFromDataSource(WrappedWritableKVState.java:51)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at com.swirlds.state.spi.WritableKVStateBase.get(WritableKVStateBase.java:84)
	at com.swirlds.state.spi.WrappedWritableKVState.readFromDataSource(WrappedWritableKVState.java:51)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at com.swirlds.state.spi.WritableKVStateBase.get(WritableKVStateBase.java:84)
	at com.swirlds.state.spi.WrappedWritableKVState.readFromDataSource(WrappedWritableKVState.java:51)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at com.swirlds.state.spi.WritableKVStateBase.get(WritableKVStateBase.java:84)
	at com.swirlds.state.spi.WrappedWritableKVState.readFromDataSource(WrappedWritableKVState.java:51)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at com.swirlds.state.spi.WritableKVStateBase.get(WritableKVStateBase.java:84)
	at com.hedera.node.app.workflows.handle.stack.WritableKVStateStack.get(WritableKVStateStack.java:82)
	at com.swirlds.state.spi.WrappedWritableKVState.readFromDataSource(WrappedWritableKVState.java:51)
	at com.swirlds.state.spi.ReadableKVStateBase.get(ReadableKVStateBase.java:63)
	at com.swirlds.state.spi.WritableKVStateBase.get(WritableKVStateBase.java:84)
	at com.hedera.node.app.workflows.handle.stack.WritableKVStateStack.get(WritableKVStateStack.java:82)
	at com.hedera.node.app.state.ReadonlyKVStateWrapper.get(ReadonlyKVStateWrapper.java:56)
	at com.hedera.node.app.service.token.impl.ReadableTokenStoreImpl.getTokenLeaf(ReadableTokenStoreImpl.java:99)
	at com.hedera.node.app.service.token.impl.ReadableTokenStoreImpl.get(ReadableTokenStoreImpl.java:57)
	at com.hedera.node.app.service.token.impl.util.TokenHandlerHelper.getIfUsable(TokenHandlerHelper.java:184)
	at com.hedera.node.app.service.token.impl.util.TokenHandlerHelper.getIfUsable(TokenHandlerHelper.java:161)
	at com.hedera.node.app.service.token.impl.util.TokenHandlerHelper.getIfUsable(TokenHandlerHelper.java:144)
	at com.hedera.node.app.service.token.impl.handlers.TokenAssociateToAccountHandler.validateSemantics(TokenAssociateToAccountHandler.java:147)
	at com.hedera.node.app.service.token.impl.handlers.TokenAssociateToAccountHandler.handle(TokenAssociateToAccountHandler.java:89)
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchHandle(TransactionDispatcher.java:131)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.tryHandle(DispatchProcessor.java:140)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.processDispatch(DispatchProcessor.java:114)
	at com.hedera.node.app.workflows.handle.DispatchHandleContext.dispatch(DispatchHandleContext.java:431)
	at com.hedera.node.app.service.contract.impl.exec.scope.HandleSystemContractOperations.dispatch(HandleSystemContractOperations.java:84)
	at com.hedera.node.app.service.contract.impl.exec.scope.SystemContractOperations.dispatch(SystemContractOperations.java:51)
	at com.hedera.node.app.service.contract.impl.exec.systemcontracts.hts.DispatchForResponseCodeHtsCall.execute(DispatchForResponseCodeHtsCall.java:205)
	at com.hedera.node.app.service.contract.impl.exec.systemcontracts.common.AbstractNativeSystemContract.resultOfExecuting(AbstractNativeSystemContract.java:125)
	at com.hedera.node.app.service.contract.impl.exec.systemcontracts.common.AbstractNativeSystemContract.computeFully(AbstractNativeSystemContract.java:113)
	at com.hedera.node.app.service.contract.impl.exec.systemcontracts.HtsSystemContract.computeFully(HtsSystemContract.java:58)
	at com.hedera.node.app.service.contract.impl.exec.processors.CustomMessageCallProcessor.doExecuteSystemContract(CustomMessageCallProcessor.java:273)
	at com.hedera.node.app.service.contract.impl.exec.processors.CustomMessageCallProcessor.start(CustomMessageCallProcessor.java:144)
	at org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:196)
	at com.hedera.node.app.service.contract.impl.exec.FrameRunner.runToCompletion(FrameRunner.java:140)
	at com.hedera.node.app.service.contract.impl.exec.FrameRunner.runToCompletion(FrameRunner.java:90)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.processTransactionWithParties(TransactionProcessor.java:137)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.processTransaction(TransactionProcessor.java:111)
	at com.hedera.node.app.service.contract.impl.exec.ContextTransactionProcessor.call(ContextTransactionProcessor.java:151)
	at com.hedera.node.app.service.contract.impl.handlers.ContractCallHandler.handle(ContractCallHandler.java:57)
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchHandle(TransactionDispatcher.java:131)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.tryHandle(DispatchProcessor.java:140)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.processDispatch(DispatchProcessor.java:114)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors.lambda$newExecutor$0(TransactionExecutors.java:224)
...
```

### Steps to reproduce

n/a

### Additional context

_No response_

### Hedera network

testnet

### Version

v1.139.0

### Operating system

None

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:
It seems users are passing evm address value as token addresses, which results to decoding them in a very big number that overflows Long type and produces TokenID with negative num value.

In case of such a wrong input in the calldata this PR returns null, instead of trying to decode this TokenID, the PR changes the logic to just return a null value and most likely lead to the transaction getting reverted. This will also clear out Grafana logs with unnecessary exception statements.

Fixes #12082

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java [hunk 1]
```diff
@@ -72,6 +72,10 @@ protected TokenReadableKVState(
 
     @Override
     protected Token readFromDataSource(@Nonnull TokenID key) {
+        if (key.tokenNum() < 0) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: Shouldn't we also check if realm != 0 or shard != 0? Long zero EVM address have to have 12 bytes as zero. It's possible they have pass a token id with positive num but non-zero shard or realm.

File: web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java [hunk 2]
```diff
@@ -108,6 +109,29 @@ void airdropToken(final EntityType receiverType) {
...
+        // When
+        final var functionCall = contract.send_tokenAirdrop(
+                invalidTokenAddress,
+                getAddressFromEntity(sender),
+                toAddress(receiver).toHexString(),
+                DEFAULT_TOKEN_AIRDROP_AMOUNT,
+                DEFAULT_TINYBAR_VALUE);
+
+        // Then
+        assertThatThrownBy(functionCall::send).isInstanceOf(MirrorEvmTransactionException.class);
```
Comment (steven-sheehy) [inline web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java]: It returns an error before and after the fix. Can't we verify the cause is not `InvalidEntityException` and is a revert or something else?

File: web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java (hunk 1 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: Is this check enough? We have exceptions with non-negative values as well: 
`Invalid entity ID: 0.0.5901004952499928656`

File: web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java (hunk 2 above)
Comment (IvanKavaldzhiev) [reply web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java]: I enhanced the test with such a check and added more negative test cases.

File: web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java (hunk 1 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: Added test case also for large token nums.

I think the shard and realm numbers don't matter in this case. 0.0.-1234 and 1.2.-9432 will both be invalid token nums. And 1.2.100 should be a valid token num if non-zero shard & realm are enabled.

Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: How the value of 274877906943L was determined? It will be more readable to extract it as a constant and write a comment explaining why this is the max value.

Comment (steven-sheehy) [reply web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: > I think the shard and realm numbers don't matter in this case. 0.0.-1234 and 1.2.-9432 will both be invalid token nums. And 1.2.100 should be a valid token num if non-zero shard & realm are enabled.

And what about if they have `1.2.1000`? The num is positive and small but has a non-zero realm or shard which is not valid for a token ID.

File: web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java [hunk 3]
```diff
@@ -72,6 +72,10 @@ protected TokenReadableKVState(
 
     @Override
     protected Token readFromDataSource(@Nonnull TokenID key) {
+        if (key.tokenNum() < 0 || key.tokenNum() > 274877906943L) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: This duplicates the logic in EntityId. I think we should change `CommonEntityAccessor` to put a try/catch around `toEntityId()` for token id only. If we fail to parse the entity id then we return null/Optional.empty() for the token. Also if shard or realm is not zero return null/empty

File: web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java (hunk 1 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: For the moment I didn't add a specific checks for shards and realms and switched the logic to fully rely on the EntityId.encode checks. There might be a chance that a TokenID fetched from DB is passed in CommonEntityAccessor.

File: web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java (hunk 3 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/state/keyvalue/TokenReadableKVState.java]: Fixed

File: web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java [hunk 4]
```diff
@@ -868,4 +900,26 @@ private void verifyContractCallWithException(final RemoteFunctionCall<?> functio
...
+
+        // Parse shard.realm.num format
+        String[] parts = tokenId.split("\\.");
+
+        long shard = Long.parseLong(parts[0]);
+        long realm = Long.parseLong(parts[1]);
+        long num = Long.parseLong(parts[2]);
+
+        // Convert to hex address format
+        return String.format("0x%08x%016x%016x", (int) shard, realm, num);
```
Comment (steven-sheehy) [inline web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java]: shard and realm are not encoded in an address so we should not attempt to do that here. Also, use `DomainUtils.toEvmAddress()`

Comment (IvanKavaldzhiev) [reply web3/src/test/java/org/hiero/mirror/web3/service/ContractCallAirdropSystemContractTest.java]: Fixed

**Review by steven-sheehy — APPROVED** [review]
LGTM
