### PR TITLE
Deduplicate lambda storage updates

### LINKED ISSUE #12637: Importer halted on duplicate key value violations
### Description

Importer halted when processing hook storage change in integration env:

```
2025-12-17T21:01:35.865Z ERROR pool-8-thread-2 o.h.m.i.p.r.RecordFileParser Error parsing file 2025-12-16T23_57_52.341033000Z.rcd.gz after 41.13 ms org.hiero.mirror.importer.exception.ParserException: Error copying 3 items to table hook_storage_change
	at org.hiero.mirror.importer.parser.batch.BatchInserter.persist(BatchInserter.java:111)
	at org.hiero.mirror.importer.parser.batch.CompositeBatchPersister.persist(CompositeBatchPersister.java:58)
	at org.hiero.mirror.importer.parser.record.entity.ParserContext.lambda$forEach$0(ParserContext.java:63)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.forEach(Unknown Source)
	at org.hiero.mirror.importer.parser.record.entity.ParserContext.forEach(ParserContext.java:63)
	at org.hiero.mirror.importer.parser.record.entity.sql.SqlEntityListener.flush(SqlEntityListener.java:412)
	at org.hiero.mirror.importer.parser.record.entity.sql.SqlEntityListener.onEnd(SqlEntityListener.java:98)
	at org.hiero.mirror.importer.parser.record.entity.sql.SqlEntityListener.onEnd(SqlEntityListener.java:73)
	at org.hiero.mirror.importer.parser.record.entity.CompositeRecordStreamFileListener.onEnd(CompositeRecordStreamFileListener.java:23)
	at org.hiero.mirror.importer.parser.record.entity.CompositeRecordStreamFileListener.onEnd(CompositeRecordStreamFileListener.java:13)
	at org.hiero.mirror.importer.parser.AbstractStreamFileParser.doFlush(AbstractStreamFileParser.java:185)
	at org.hiero.mirror.importer.parser.AbstractStreamFileParser.parse(AbstractStreamFileParser.java:91)
	at org.hiero.mirror.importer.parser.record.RecordFileParser.parse(RecordFileParser.java:112)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:380)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:114)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:357)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:246)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:135)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:162)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)
	at org.hiero.mirror.importer.parser.record.RecordFileParser$$SpringCGLIB$$0.parse(<generated>)
	at org.hiero.mirror.importer.downloader.BatchStreamFileNotifier$StreamFileSubscriber.handle(BatchStreamFileNotifier.java:123)
	at org.hiero.mirror.importer.downloader.BatchStreamFileNotifier$StreamFileSubscriber.run(BatchStreamFileNotifier.java:96)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Ending write to copy failed.
	at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:120)
	at com.fasterxml.jackson.dataformat.csv.impl.UTF8Writer.close(UTF8Writer.java:74)
	at com.fasterxml.jackson.dataformat.csv.impl.CsvEncoder.close(CsvEncoder.java:1109)
	at com.fasterxml.jackson.dataformat.csv.CsvGenerator.close(CsvGenerator.java:549)
	at com.fasterxml.jackson.databind.ObjectWriter._writeValueAndClose(ObjectWriter.java:1294)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1098)
	at org.hiero.mirror.importer.parser.batch.BatchInserter.persistItems(BatchInserter.java:128)
	at org.hiero.mirror.importer.parser.batch.BatchInserter.persist(BatchInserter.java:108)
	... 33 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "hook_storage_change_pkey"
  Detail: Key (owner_id, hook_id, key, consensus_timestamp)=(2302, 124, \x01, 1765929472341033000) already exists.
  Where: COPY hook_storage_change, line 3
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2736)
	at org.postgresql.core.v3.QueryExecutorImpl.processCopyResults(QueryExecutorImpl.java:1310)
	at org.postgresql.core.v3.QueryExecutorImpl.endCopy(QueryExecutorImpl.java:1108)
	at org.postgresql.core.v3.CopyInImpl.endCopy(CopyInImpl.java:53)
	at org.postgresql.copy.PGCopyOutputStream.endCopy(PGCopyOutputStream.java:198)
	at org.postgresql.copy.PGCopyOutputStream.close(PGCopyOutputStream.java:118)
	... 40 common frames omitted
```

### Steps to reproduce

check the description

### Additional context

_No response_

### Hedera network

other

### Version

v0.146.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR adds logic to deduplicate lambda storage updates

- Deduplicate the storage updates and honor the last one

**Related issue(s)**:

Fixes #12637 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by jnels124 — APPROVED** [review]
LGTM

File: importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EVMHookHandler.java [hunk 1]
```diff
@@ -228,39 +218,67 @@ private HookType translateHookType(HookCase hookCase) {
...
+                }
+            }
         }
-    }
 
-    private void processStorageSlotUpdate(
-            LambdaStorageSlot storageSlot, long consensusTimestamp, long ownerEntityId, long hookId) {
-        final var slotKey = toBytes(storageSlot.getKey());
+        private void persistChange(final byte[] key, final byte[] valueWritten) {
+            if (!processed.add(Arrays.hashCode(key))) {
```
Comment (steven-sheehy) [inline importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EVMHookHandler.java]: Concerned of potential for hash collisions since in theory two 256 bit keys could hash to the same 32 bit integer. And there's no hash buckets to handle duplicate collisions. Prefer we just use `Set<Bytes>` instead as there won't be many items in the set to make memory a concern.

File: importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EvmHookStorageHandler.java [hunk 2]
```diff
@@ -5,11 +5,11 @@
 import com.hedera.hapi.node.hooks.legacy.LambdaStorageUpdate;
 import com.hedera.services.stream.proto.StorageChange;
 import java.util.List;
-import org.hiero.mirror.common.domain.entity.EntityId;
 
 public interface EvmHookStorageHandler {
+
     void processStorageUpdates(
-            long consensusTimestamp, long hookId, EntityId ownerId, List<LambdaStorageUpdate> storageUpdates);
+            long consensusTimestamp, long hookId, long ownerId, List<LambdaStorageUpdate> storageUpdates);
```
Comment (steven-sheehy) [inline importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EvmHookStorageHandler.java]: Why this change? We should prefer higher level interfaces like EntityId as per the dependency inversion principle.

Comment (xin-hedera) [reply importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EvmHookStorageHandler.java]: the other method in the interface is a `long`, so we would prefer the other way around.

File: importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EVMHookHandler.java (hunk 1 above)
Comment (xin-hedera) [reply importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EVMHookHandler.java]: changed to use `ByteBuffer` and `Set<ByteBuffer>`

File: importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EvmHookStorageHandler.java (hunk 2 above)
Comment (xin-hedera) [reply importer/src/main/java/org/hiero/mirror/importer/parser/record/transactionhandler/EvmHookStorageHandler.java]: reverted the changes
