### PR TITLE
Fix flaky rest tests

### LINKED ISSUE #10992: Flaky REST Gradle workflow
### Description

The REST API Gradle workflow frequently fails in GitHub Actions due to some container test setup issues.

### Steps to reproduce

1. Push a PR
2. It triggers the Gradle build workflow
3. The REST API steps periodically fail and have to be retried

### Additional context

https://github.com/hiero-ledger/hiero-mirror-node/actions/runs/14598767151/job/40951347248?pr=10991

```
ERROR: Unable to obtain connection from database (jdbc:postgresql://localhost:32786/mirror_node) for user 'mirror_node': Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused
PASS __tests__/accounts.deduplication.timestamp.test.js (7893 ms)
ERROR: Unable to obtain connection from database (jdbc:postgresql://localhost:32786/mirror_node) for user 'mirror_node': Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused
ERROR: Unable to obtain connection from database (jdbc:postgresql://localhost:32786/mirror_node) for user 'mirror_node': Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused

Error: expect(received).resolves.toBeNull()

Received promise rejected instead of resolved
Rejected to value: [Error: relation "record_file" does not exist]

    at expect (node_modules/expect/build/index.js:113:15)
    at Object.expect (__tests__/service/recordFileService.test.js:70:11)
```

### Hedera network

other

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR again tries to fix the flakiness in js rest tests

- Move postgresql db container management to the global context

**Related issue(s)**:

Fixes #10992 

**Notes for reviewer**:

Though we limit the number of jest workers to 2 for CI and 50% of the CPU cores in other envs, it doesn't really limit the number of database containers we create. The reason is jest run each test module in a sandbox, so we end up creating multiple postgresql database containers for the same worker, and the number of db containers equal to the number of integration test modules the worker is assigned to run. At a glance, with 5 jest workers running on my dev laptop, there's about 10 containers created and running at the same time.

The fix has a bit complexity that we run a tiny express server in the global context to server post requests from worker processes and create / return db connection parameters so the workers know how to connect.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: rest/__tests__/integrationContainerOps.js [hunk 1]
```diff
@@ -48,92 +40,42 @@ const cleanUp = async () => {
...
-  const psqlContainer = await getDbContainer();
-  const network = await getNetwork();
-  if (!network) {
-    throw new Error('Network not found');
-  }
+  const connectionParams = await getDbConnectionParams();
+  await flywayMigrate(connectionParams);
   return new GenericContainer('gcr.io/mirrornode/hedera-mirror-rest-java:latest')
     .withEnvironment({
       HEDERA_MIRROR_RESTJAVA_DB_HOST: `postgres-${workerId}`,
```
Comment (jnels124) [inline rest/__tests__/integrationContainerOps.js:48]: I need to fix this. This is no longer correct without the network. Test I ran passed because restjava still starts and serves requests when it can not connect to the db and test didn't reach into db.

Comment (xin-hedera) [reply rest/__tests__/integrationContainerOps.js:48]: Sounds like you need to add the docker network name to the response from the express server in global setup

Comment (jnels124) [reply rest/__tests__/integrationContainerOps.js]: Didn't appear to be available from the container itself. We can reference other containers though using the host gateway

**Review by steven-sheehy — APPROVED** [review]
LGTM
