### PR TITLE
Log web3 request for server errors

### LINKED ISSUE #13366: Enhance web3 logs format
### Problem

Currently, the web3 logs in Grafana get truncated in almost all of the cases (even if they are compressed). This leads to losing valuable information needed for investigating issues like the receiver/sender address, etc. Example log:
```
POST /api/v1/contracts/call in 10010 ms : 500 Mirror EVM transaction error: FAIL_INVALID, data:  - {"data":"0x407a4b08000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000003e80000000000000000000000004f67794128c98f44b9703a1476fdb9b8e8f33a150000000000000000000000009665a504affac93fc9c68186d1b70c059dc2442b000000000000000000000000f
```

### Solution

Change the log format, so that the receiver (and possibly other valuable fields) is always logged at the beginning and only the call data gets truncated.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by steven-sheehy**
**Description**:

* Change the contract call API to log the full request for 5xx errors
* Move `data` field to the end of the request when logging truncated requests
* Fix monitor calls to network/nodes

**Related issue(s)**:

Fixes #13366

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: web3/src/main/java/org/hiero/mirror/web3/config/LoggingFilter.java [hunk 1]
```diff
@@ -121,4 +127,20 @@ private String getMessage(HttpServletRequest request, Exception e) {
...
+            return json;
+        }
+
+        int end = json.indexOf(COMMA, start);
+        if (end == -1) {
+            return json;
+        }
+
+        String dataField = json.substring(start, end);
+        return json.replace(COMMA + dataField, StringUtils.EMPTY).replace(BRACE, COMMA + dataField + BRACE);
```
Comment (jnels124) [inline web3/src/main/java/org/hiero/mirror/web3/config/LoggingFilter.java]: is it ever possible for data to be the first field? If so this would duplicate the data field right?

Comment (steven-sheehy) [reply web3/src/main/java/org/hiero/mirror/web3/config/LoggingFilter.java]: I've fixed some issues with the parsing and added a test for this scenario and more.

**Review by jnels124 — DISMISSED** [review]
LGTM. Only comment i have is this will break if we ever change this response to have nested objects. I am not sure if we want a check in `reorderFields` to ensure that there are not nested objects.

**Review by ashumahajan — DISMISSED** [review]
LGTM

**Review by jnels124 — APPROVED** [review]
