### PR TITLE
Fix precompile.feature acceptance tests

### LINKED ISSUE #10498: Fix precompile.feature acceptance test suite against modularized EVM
Fix the failing tests in precompile.feature and adapt them to work against modularized EVM

### PR DESCRIPTION
**Pull request by filev94**
**Description**:
This PR fixes the precompile.feature acceptance tests. The issues were:
    - missing configuration for fungible and non-fungible tokens when being created
    - different result when going through new code compared to old code
    - wrongful usage of fungibleTokenId instead of nonFungibleTokenId in method that tests non-fungible token.

**Related issue(s)**:

Fixes #10498 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java [hunk 1]
```diff
@@ -349,30 +390,42 @@ public void getDefaultFreezeOfNonFungibleToken() {
...
     @And("the contract call REST API should return the default kyc for a fungible token")
     public void getDefaultKycOfFungibleToken() {
-        var data = encodeData(PRECOMPILE, GET_TOKEN_DEFAULT_KYC_SELECTOR, asAddress(fungibleTokenId));
+        var data = encodeData(PRECOMPILE, GET_TOKEN_DEFAULT_KYC_SELECTOR, fungibleTokenAddress);
 
         var response = callContract(data, precompileTestContractSolidityAddress);
+        boolean defaultKycStatus = false;
+        // In the modularized code, the status is now true when the token has a KycNotApplicable status,
+        // whereas the mono logic returns false. We need to toggle the status based on the modularized flag.
+        if (web3Properties.isModularizedServices()) {
```
Comment (bilyana-gospodinova) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java:399]: We test this invertion in the next test for NFT. Can we use the new fungible token here and verify for one of the other statuses? If the tests pass, we will have more coverage this way.

Comment (filev94) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/PrecompileContractFeature.java:400]: I used the new fungible token that I created for custom fees and modified it to have Granted status for this test. Just had to flip the defaultKycStatus for the latter to pass

**Review by bilyana-gospodinova — APPROVED** [review]
LGTM
