### PR TITLE
Prevent `null` singleton values

### LINKED ISSUE #12055: `NullPointerException` on `ThrottleServiceManager.resetThrottlesUnconditionally()`
### Description

The following exception was noticed in Grafana logs:

```
2025-09-24 03:31:37.038	
2025-09-24T00:31:37.028Z ERROR tomcat-handler-26249 c.h.n.a.w.h.DispatchProcessor Possibly CATASTROPHIC failure - exception thrown while handling dispatch java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at com.hedera.node.app.throttle.ThrottleServiceManager.resetThrottlesUnconditionally(ThrottleServiceManager.java:237)
	at com.hedera.node.app.workflows.handle.throttle.DispatchUsageManager.screenForCapacity(DispatchUsageManager.java:72)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.tryHandle(DispatchProcessor.java:139)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.processDispatch(DispatchProcessor.java:114)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors.lambda$newExecutor$0(TransactionExecutors.java:224)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors$DefaultTracerBinding.runWhere(TransactionExecutors.java:326)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors.lambda$newExecutor$1(TransactionExecutors.java:223)
	at org.hiero.mirror.web3.service.TransactionExecutionService.execute(TransactionExecutionService.java:83)
	at org.hiero.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:126)
...
```

### Steps to reproduce

n/a

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.139.0

### Operating system

None

### LINKED ISSUE #12400: `NullPointerException` on `ReadableEntityIdStoreImpl.getCounterFor()`
### Description

The following exception was noticed in the Grafana logs:

```
2025-11-13 07:33:51.6252025-11-13T05:33:51.624Z ERROR tomcat-handler-269651 c.h.n.a.w.h.DispatchProcessor Possibly CATASTROPHIC failure - exception thrown while handling dispatch java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at com.hedera.node.app.ids.ReadableEntityIdStoreImpl.getCounterFor(ReadableEntityIdStoreImpl.java:108)
	at com.hedera.node.app.service.contract.impl.state.ReadableContractStateStore.getNumSlots(ReadableContractStateStore.java:114)
	at com.hedera.node.app.service.contract.impl.state.DispatchingEvmFrameState.getKvStateSize(DispatchingEvmFrameState.java:173)
	at com.hedera.node.app.service.contract.impl.state.RootProxyWorldUpdater.summarizeSizeEffects(RootProxyWorldUpdater.java:159)
	at com.hedera.node.app.service.contract.impl.state.RootProxyWorldUpdater.commit(RootProxyWorldUpdater.java:89)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.safeCommit(TransactionProcessor.java:179)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.processTransactionWithParties(TransactionProcessor.java:156)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.processTransaction(TransactionProcessor.java:115)
	at com.hedera.node.app.service.contract.impl.exec.ContextTransactionProcessor.call(ContextTransactionProcessor.java:164)
	at com.hedera.node.app.service.contract.impl.handlers.ContractCallHandler.handle(ContractCallHandler.java:57)
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchHandle(TransactionDispatcher.java:131)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.tryHandle(DispatchProcessor.java:148)
```

### Steps to reproduce

n/a

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.142.1

### Operating system

None

### PR DESCRIPTION
**Pull request by bilyana-gospodinova**
**Description**:
In `hedera-app` bump from 0.64.3 to 0.65.0 the `WritableSingletonStateBase` class was changed to abstract. Also, its get method was modified so that the current singleton value is returned even if it is `null`, which was not allowed in the previous release. Also, with this `hedera-app` bump the `NullPointerException` issues started to appear. This PR returns the previous behaviour - return the modified value only if it is not `null`, delegate to the super implementation (our custom singleton states that return non-null values in `get()`) if `null`.

Fixes #12400
Fixes #12055

### CODE REVIEW

File: web3/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+    }
+
+    @Override
+    public T get() {
+        // If there is a modification, then we've already done a "put" or "remove"
+        // and should return based on the modification
+        if (isModified()) {
+            // The change from the copied class is here - preventing null values
+            // as they cause NullPointerExceptions in some various places in the code.
+            final var currentValue = currentValue();
```
Comment (IvanKavaldzhiev) [inline web3/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java:60]: It's good to have this difference described also in a class top-level comment.

Comment (bilyana-gospodinova) [reply web3/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java:60]: Done

File: web3/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+import edu.umd.cs.findbugs.annotations.NonNull;
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * A convenient base class for mutable singletons.
+ * Copy of the class from hedera-app. The difference is that the get() method is modified not to return null values.
+ * @param <T> The type
+ */
+public abstract class WritableSingletonStateBase<T> extends ReadableSingletonStateBase<T>
```
Comment (steven-sheehy) [inline web3/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java:16]: Why can't we just override get() in `FunctionWritableSingletonState`?

Comment (bilyana-gospodinova) [reply web3/src/main/java/com/swirlds/state/spi/WritableSingletonStateBase.java:16]: Unfortunately, this is not enough - there is one more implementation of this class - `WrappedWritableSingletonState` which is called directly in hedera-app and which bypasses our `FunctionWritableSingletonState`.
