### PR TITLE
Fix creation of duplicate synthetic events

### LINKED ISSUE #13263: Synthetic logs for Transfer events are duplicated in some cases
### Description

It seems for transactions that are related to smart contract execution having a nested transfer event there are synthetic logs being duplicated on MN side. That happens when a sender (topic1), a receiver (topic2) or both are accounts having an alias/evm_address used to generate the topics based on the alias/evm_address.

In addition the synthetically created log on MN has a transaction hash of the child record item, instead of the one of the parent transaction that holds the ContractResult.

### Steps to reproduce

Create a ContractCall or EthereumTransaction with ContractCall that triggers EVM execution producing a transfer log, emitted by CN in the record stream.

Inspect the transaction events in Hashscan after it is ingested in mirror-node.

### Additional context

_No response_

### Hedera network

previewnet

### Version

v0.150.0

### Operating system

None

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:
This PR fixes:

- creation of duplicate transfer synthetic logs
- setting transaction hash , consensusTimestamp, logIndex, transactionIndex, contractId, rootContractId  to be the contract related parent item (if available)
- properly create bloom filter for the synthetic ContractLog using the alias of the sender/receivers (topic1/topic2) if available. The bloom needs to be set in SyntheticLogListener.onEnd, when the sender/receiver aliases will be resolved

**Related issue(s)**:

Fixes #13263

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: common/src/main/java/org/hiero/mirror/common/util/DomainUtils.java [hunk 1]
```diff
@@ -364,19 +369,111 @@ public static BytesValue trim(final BytesValue data) {
...
+            byte[] topic3,
+            byte[] data,
+            @NonNull ContractAccountResolver accountResolver) {
         var topicList = log.getTopicList();
         int topicCount = topicList.size();
         return trimmedByteStringEquals(topicCount > 0 ? topicList.get(0) : null, topic0)
-                && trimmedByteStringEquals(topicCount > 1 ? topicList.get(1) : null, topic1)
-                && trimmedByteStringEquals(topicCount > 2 ? topicList.get(2) : null, topic2)
+                && transferIndexedAddressTopicMatches(topicCount > 1 ? topicList.get(1) : null, topic1, accountResolver)
+                && transferIndexedAddressTopicMatches(topicCount > 2 ? topicList.get(2) : null, topic2, accountResolver)
```
Comment (IvanKavaldzhiev) [inline common/src/main/java/org/hiero/mirror/common/util/DomainUtils.java]: We should also check whether the contractId is the same, since we can have 2 valid logs with the same data, topic0, topic1, topic2 and topic3 but related to invocation to different contracts.

File: common/src/main/java/org/hiero/mirror/common/util/DomainUtils.java [hunk 2]
```diff
@@ -364,19 +369,134 @@ public static BytesValue trim(final BytesValue data) {
...
+            @Nullable ByteString contractResultTopic,
+            byte[] syntheticTopic,
+            @NonNull ContractAccountResolver accountResolver) {
+        if (trimmedByteStringEquals(contractResultTopic, syntheticTopic)) {
+            return true;
+        }
+
+        var contractResultLogTrimmed = trimmedLogTopicBytes(contractResultTopic);
+        var contractResultLogEntity = resolveTransferIndexedAccount(contractResultLogTrimmed, accountResolver);
+        if (contractResultLogEntity.isEmpty()) {
```
Comment (jnels124) [inline common/src/main/java/org/hiero/mirror/common/util/DomainUtils.java]: This looks like we can potentially miss events if lookup fails because the entity is created in the same recordfile/block as this event. Also will skip creating events if running as a partial mirrornode that doesn't have the entity in db

File: importer/src/test/java/org/hiero/mirror/importer/parser/contractlog/SyntheticLogListenerIntegrationTest.java
Comment (jnels124) [inline importer/src/test/java/org/hiero/mirror/importer/parser/contractlog/SyntheticLogListenerIntegrationTest.java:1]: Should we have a test that has:
* a child contract execution emits a transfer,
* the synthetic log is deduped correctly when alias/EVM topics are present, and
* the persisted synthetic log uses the parent transaction hash.

Comment (IvanKavaldzhiev) [reply importer/src/test/java/org/hiero/mirror/importer/parser/contractlog/SyntheticLogListenerIntegrationTest.java:1]: Added

File: importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java [hunk 3]
```diff
@@ -67,55 +103,21 @@ private boolean isContract(RecordItem recordItem) {
     }
 
     private boolean shouldSkipLogCreationForContractTransfer(SyntheticContractLog syntheticLog) {
-        if (!(syntheticLog instanceof TransferContractLog transferLog)) {
+        if (!(syntheticLog instanceof TransferContractLog)) {
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java]: should we move the `isContract(recordItem)` check in this function, and probably also rename it to just `shouldSkipLogCreation`? It's clearer and easier to understand in my opinion.

File: importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java [hunk 4]
```diff
@@ -29,33 +30,68 @@ public void create(SyntheticContractLog log) {
...
+            transactionIndex = recordItem.getTransactionIndex();
+            transactionHash = recordItem.getTransactionHash();
+            contractId = log.getEntityId();
+            rootContractId = log.getEntityId();
+        }
 
         ContractLog contractLog = new ContractLog();
 
-        contractLog.setBloom(isContract(recordItem) ? createBloom(log) : empty);
+        contractLog.setBloom(isContract(recordItem) ? CONTRACT_LOG_MARKER : empty);
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java:83]: can we not use `null` as the marker?

**Review by jnels124 — DISMISSED** [review]

File: importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java [hunk 5]
```diff
@@ -29,34 +30,69 @@ public void create(SyntheticContractLog log) {
...
+
+            final var parentTransactionBody = contractRelatedParentRecordItem.getTransactionBody();
+            if (parentTransactionBody.hasContractCall()) {
+                final var contractIdReceipt =
+                        parentTransactionRecord.getReceipt().getContractID();
+
+                rootContractId = EntityId.of(contractIdReceipt);
+            } else {
+                rootContractId =
+                        EntityId.of(parentTransactionRecord.getReceipt().getContractID());
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java:70]: the logic in the two branches is the same, they both get root contract id from `parentTransactionRecord.getReceipt().getContractID()`

File: importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java (hunk 4 above)
Comment (IvanKavaldzhiev) [reply importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java:83]: I wanted to use a marker as a safety mechanism, so that the bloom is not accidentially left null before persisting, which will produce an error.

File: importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java (hunk 3 above)
Comment (IvanKavaldzhiev) [reply importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java]: Agree, fixed.

File: importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java (hunk 5 above)
Comment (IvanKavaldzhiev) [reply importer/src/main/java/org/hiero/mirror/importer/parser/contractlog/SyntheticContractLogServiceImpl.java:70]: Fixed

**Review by xin-hedera — DISMISSED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM

**Review by jnels124 — APPROVED** [review]
