### PR TITLE
Fix REST API tests for Windows compatibility

### LINKED ISSUE #12249: Investigate and resolve issues running REST API tests on windows
### Description

There have been issues reported by community members with being able to run tests on windows machines. We need to investigate the issue and resolve any problems.

### Steps to reproduce

run `./gradlew :rest:test`
identify any errors

### Additional context

_No response_

### Hedera network

other

### Version

v.0.142.0

### Operating system

Windows

### PR DESCRIPTION
**Pull request by martingeorgiev1**
**Description**:

Fix REST API tests to run on Windows by handling OS-specific differences

* Add Windows-specific path handling in database setup scripts
* Update PostgreSQL container operations to work on both Windows and Linux
* Fix file path separators to use platform-appropriate format
* Tests now pass on Windows and Linux/WSL

**Related issue(s)**:

Fixes #12249

**Notes for reviewer**:
- All tests pass on both Windows and Linux (WSL)
- The changes are in test setup files to handle Windows path conventions
- No changes to production code, only test infrastructure
- To run tests: `./gradlew :rest:test`
- Verified on:
  - Windows 10/11 with Node.js 22
  - Ubuntu WSL2 with Node.js 22

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [X] Tested locally

### CODE REVIEW

File: rest/__tests__/integrationContainerOps.js [hunk 1]
```diff
@@ -113,36 +113,41 @@ const flywayMigrate = async (connectionParams) => {
   const {database, host, password, port, user} = connectionParams;
   logger.info(`Using flyway CLI to construct schema for jest worker ${workerId} on port ${port}`);
   const jdbcUrl = `jdbc:postgresql://${host}:${port}/${database}`;
-  const flywayConfigPath = path.join(os.tmpdir(), `config_worker_${workerId}.json`); // store configs in temp dir
+  const flywayConfigPath = path.join(
+    os.platform() === 'win32' ? path.join('.', 'build', 'flyway data') : os.tmpdir(),
+    `config_worker_${workerId}.json`
+  ); // store configs in temp dir
```
Comment (steven-sheehy) [inline rest/__tests__/integrationContainerOps.js]: If we're storing the config in data path in windows we might as well do it in linux. Does this work?

```suggestion
  const flywayConfigPath = path.join(FLYWAY_DATA_PATH, `config_worker_${workerId}.json`);
```

Comment (martingeorgiev1) [reply rest/__tests__/integrationContainerOps.js]: You are correct, your suggested changes are working perfectly. I'm updating the PR

**Review by xin-hedera — APPROVED** [review]
LGTM
