### PR TITLE
Fixing failing topic acceptance test 

### LINKED ISSUE #11173: Topic message acceptance test fails in previewnet
### Description

Topic message acceptance test failed in previewnet when validating v0.130.0-rc1 deployment

```
  JUnit Platform Suite:AcceptanceTest:Cucumber:HCS Base Coverage Feature:Validate Topic message submission:Examples:Example #1.1
    ClasspathResourceSource [classpathResourceName = 'features/topic/topic.feature', filePosition = FilePosition [line = 30, column = 7]]
    => java.lang.reflect.UndeclaredThrowableException
       org.hiero.mirror.test.e2e.acceptance.steps.TopicFeature$$SpringCGLIB$$0.submitTopicMessage(<generated>)
       java.base/java.lang.reflect.Method.invoke(Unknown Source)
       io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
       io.cucumber.java.Invoker.invoke(Invoker.java:24)
       io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
       [...]
     Caused by: com.hedera.hashgraph.sdk.PrecheckStatusException: Hedera transaction `0.0.8035@1747178837.784000586` failed pre-check with the status `INSUFFICIENT_PAYER_BALANCE`
       com.hedera.hashgraph.sdk.Executable$GrpcRequest.mapStatusException(Executable.java:962)
       com.hedera.hashgraph.sdk.Executable.execute(Executable.java:449)
       com.hedera.hashgraph.sdk.Transaction.execute(Transaction.java:36)
       com.hedera.hashgraph.sdk.ChunkedTransaction.executeAll(ChunkedTransaction.java:317)
       com.hedera.hashgraph.sdk.TopicMessageSubmitTransaction.executeAll(TopicMessageSubmitTransaction.java:30)
       [...]
```

### Steps to reproduce

Run acceptance tests against previewnet with cucumber tag `@topic and @release`

### Additional context

_No response_

### Hedera network

previewnet

### Version

v0.130.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by filev94**
**Description**:
This PR changes the DEFAULT_INITIAL_BALANCE from 50_000_000 to 75_000_000 so that payer account in TopicFeature acceptance tests can have enough balance.

**Related issue(s)**:

Fixes #11173 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/client/AccountClient.java [hunk 1]
```diff
@@ -36,7 +36,7 @@
 @Named
 public class AccountClient extends AbstractNetworkClient {
 
-    private static final long DEFAULT_INITIAL_BALANCE = 50_000_000L; // 0.5 ℏ
+    private static final long DEFAULT_INITIAL_BALANCE = 75_000_000L; // 0.75 ℏ
```
Comment (kselveliev) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/client/AccountClient.java:39]: Is this the actual minimum amount needed? If yes LGTM.

Comment (filev94) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/client/AccountClient.java:39]: It works with 70 million as well, but i wanted to be on the safe side. It does not work with 65 million.

**Review by kselveliev — APPROVED** [review]

**Review by xin-hedera — APPROVED** [review]
LGTM

**Comment by xin-hedera** [comment]
would prefer initial balance in USD, that should probably go to a different ticket.

**Review by sdimitrov9 — APPROVED** [review]
