### PR TITLE
Fix flakiness in historical tests by trimming total supply from getTokenInfo response in historical.feature tests

### LINKED ISSUE #10634: HIP-1056 Historical contract acceptance test failed
### Description

When running acceptance test suite with previewnet block stream files, it failed at the following step:

```
org.opentest4j.AssertionFailedError: 
expected: 0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d400000000000000000000000000000000000000000000000000000000000000d600000000000000000000000000000000000000000000000000000000000000d800000000000000000000000000000000000000000000000000000000000000da0000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000002bf700000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000683f42ea0000000000000000000000000000000000000000000000000000000000002bf700000000000000000000000000000000000000000000000000000000006acfbf000000000000000000000000000000000000000000000000000000000000001866756e6769626c655f686973746f726963616c5f6e616d650000000000000000000000000000000000000000000000000000000000000000000000000000001366756e6769626c655f686973746f726963616c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000454d6972726f72204e6f646520616363657074616e636520746573743a20323032352d30332d31345431383a31393a32332e3031333332325a2043726561746520746f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000220000000000000000000000000000000000000000000000000000000000000036000000000000000000000000000000000000000000000000000000000000004a000000000000000000000000000000000000000000000000000000000000005e000000000000000000000000000000000000000000000000000000000000007200000000000000000000000000000000000000000000000000000000000000860000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000043078303100000000000000000000000000000000000000000000000000000000
 but was: 0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000f42400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d400000000000000000000000000000000000000000000000000000000000000d600000000000000000000000000000000000000000000000000000000000000d800000000000000000000000000000000000000000000000000000000000000da0000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a00000000000000000000000000000000000000000000000000000000000002bf700000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000026000000000000000000000000000000000000000000000000000000000683f42ea0000000000000000000000000000000000000000000000000000000000002bf700000000000000000000000000000000000000000000000000000000006acfbf000000000000000000000000000000000000000000000000000000000000001866756e6769626c655f686973746f726963616c5f6e616d650000000000000000000000000000000000000000000000000000000000000000000000000000001366756e6769626c655f686973746f726963616c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000454d6972726f72204e6f646520616363657074616e636520746573743a20323032352d30332d31345431383a31393a32332e3031333332325a2043726561746520746f6b656e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000220000000000000000000000000000000000000000000000000000000000000036000000000000000000000000000000000000000000000000000000000000004a000000000000000000000000000000000000000000000000000000000000005e000000000000000000000000000000000000000000000000000000000000007200000000000000000000000000000000000000000000000000000000000000860000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002071b5dccca6b519e78c685a2f88f1dfd1be4d400234db6b5443a8877c6445f0db000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000043078303100000000000000000000000000000000000000000000000000000000
	at app//com.hedera.mirror.test.e2e.acceptance.steps.HistoricalFeature.getHistoricalDataForTokenSymbol(HistoricalFeature.java:305)
	at ✽.I verify that historical data for "FUNGIBLEHISTORICAL" is returned via getTokenInfo(classpath:features/contract/historical.feature:27)
```

### Steps to reproduce

check the description

### Additional context

_No response_

### Hedera network

previewnet

### Version

0.126.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by nickeynikolovv**
Add a workaround for a flaky behaviour in tests that are calling getTokenInfo. A method that trims the totalSupply from the response is added.  The flakiness occurs because sometimes the response from getTokenInfo historical returns 0 for total supply instead of the real value. It is because the query for totalSupply historical depends on the db tables - `token_balance`, `token_transfers` and `account_balance` and because they update on every 15 minutes.
If the environment (e.g local node) is recently started and the db tables are still not populated with entries (the 15 mins update hasn't processed yet) the query for total supply will calculate and return 0. If there are entries, the result will be correct. 
- I could reproduce it only on local environment and only right after I started local node and the db tables were still empty. 
- Tried to reproduce it on previewnet, but couldn't. 

Another approach was to add await on the assertion at the end of the test, but this might cause a delay of 15-20 minutes in test execution which is not good.

At the end the totalSupply is not needed in those tests, because we update the name, memo and some additional parameters of the token

**Related issue(s)**:

Fixes #10634 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java [hunk 1]
```diff
@@ -956,6 +968,38 @@ private boolean isEstimatePrecompileFeatureContractMethod(final Selector selecto
...
+    private String trimTotalSupplyForGetTokenInfo(String response) {
+        var responseWithoutOx = "";
+        if (response.startsWith(RESPONSE_PREFIX)) {
+            responseWithoutOx = response.substring(2);
+        }
+        // TotalSupply value is located between 128 and 192 indexes
+        int startIndex = 128;
+        int endIndex = startIndex + 64;
+
+        return responseWithoutOx.substring(0, startIndex) + responseWithoutOx.substring(endIndex);
```
Comment (steven-sheehy) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java:984]: Should always check string size before doing substring

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java [hunk 2]
```diff
@@ -956,6 +968,38 @@ private boolean isEstimatePrecompileFeatureContractMethod(final Selector selecto
...
+    private String trimTotalSupplyForFungibleTokenInfo(String response) {
+        var responseWithoutOx = "";
+        if (response.startsWith(RESPONSE_PREFIX)) {
+            responseWithoutOx = response.substring(2);
+        }
+        // TotalSupply value is located between 258 and 322 indexes
+        int startIndex = 258;
+        int endIndex = startIndex + 64;
+
+        return responseWithoutOx.substring(0, startIndex) + responseWithoutOx.substring(endIndex);
```
Comment (steven-sheehy) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java:1000]: Check string size first

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java [hunk 3]
```diff
@@ -291,18 +292,22 @@ public void getHistoricalDataForNonExistingAccount() {
...
+
         waitForNextBlock();
 
         networkTransactionResponse = tokenClient.updateToken(tokenId, admin);
         verifyMirrorTransactionsResponse(mirrorClient, 200);
+
         var historicalResponse = callContract(
                 initialBlockNumber, data, precompileContractSolidityAddress, GET_TOKEN_INFO.getActualGas());
-        assertThat(response).isEqualTo(historicalResponse);
+        var historicalTrimmedResponse = trimTotalSupplyForGetTokenInfo(historicalResponse.toString());
```
Comment (kselveliev) [inline hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java:309]: Couple of places in the changesets where the var can be final, could adjust

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java (hunk 2 above)
Comment (nickeynikolovv) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java]: Done

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java (hunk 1 above)
Comment (nickeynikolovv) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java]: Done

File: hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java (hunk 3 above)
Comment (nickeynikolovv) [reply hedera-mirror-test/src/test/java/com/hedera/mirror/test/e2e/acceptance/steps/HistoricalFeature.java]: done

**Review by kselveliev — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]
