### PR TITLE
Increase web3 acceptance test stability inside solo

### LINKED ISSUE #12385: Acceptance failure for NFT name
### Description

https://github.com/hiero-ledger/hiero-consensus-node/actions/runs/19226200227/job/54953925716

### Steps to reproduce

Run CITR workflow

### Additional context

```
2025-11-10T09:09:56.583Z  INFO ForkJoinPool-1-worker-6 o.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-1-web3/api/v1/contracts/call: 200 OK 
2025-11-10T09:09:56.583Z  INFO ForkJoinPool-1-worker-6 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodehash opcode against a system account 999 num returns empty bytes 
2025-11-10T09:09:56.585Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-1-web3/api/v1/contracts/call: 200 OK 
2025-11-10T09:09:56.591Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.AccountFeature Executing scenario: Validate in-equivalence system accounts for balance, extcodesize, extcodecopy, extcodehash 
2025-11-10T09:09:56.591Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I successfully create selfdestruct contract 
2025-11-10T09:09:56.592Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I successfully create equivalence call contract 
2025-11-10T09:09:56.592Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.HistoricalFeature Executing step: the mirror node REST API should return status 200 for the contracts creation 
2025-11-10T09:09:56.592Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify the equivalence contract bytecode is deployed 
2025-11-10T09:09:56.592Z  INFO ForkJoinPool-1-worker-3 o.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-1-web3/api/v1/contracts/call: 200 OK 
2025-11-10T09:09:56.593Z  INFO ForkJoinPool-1-worker-3 o.h.m.t.e.a.s.ERCContractFeature Executing step: I call the erc contract via the mirror node REST API for token symbol 
2025-11-10T09:09:56.596Z  INFO ForkJoinPool-1-worker-4 o.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-1-web3/api/v1/contracts/call: 400 BAD_REQUEST 
2025-11-10T09:09:56.597Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.c.MirrorNodeClient GET http://mirror-1-rest/api/v1/contracts/0000000000000000000000000000000000000409: 200 OK 
2025-11-10T09:09:56.598Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify the selfdestruct contract bytecode is deployed 
2025-11-10T09:09:56.599Z  INFO ForkJoinPool-1-worker-2 o.h.m.t.e.a.c.MirrorNodeClient POST http://mirror-1-web3/api/v1/contracts/call: 200 OK 
2025-11-10T09:09:56.599Z  INFO ForkJoinPool-1-worker-2 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I verify extcodesize opcode against a system account 10 num returns 0 
2025-11-10T09:09:56.600Z ERROR ForkJoinPool-1-worker-4 o.h.m.t.e.a.s.CallFeature Scenario failure: 
I successfully create ERC contract
I successfully create Precompile contract
I verify the precompile contract bytecode is deployed
I successfully create EstimateGas contract
I ensure token "FUNGIBLE" has been created
I ensure token "NFT" has been created
I call function with IERC721Metadata token "NFT" name <- 400 Bad Request: "{"_status":{"messages":[{"message":"FAIL_INVALID","detail":"","data":""}]}}"
I call function with IERC721Metadata token "NFT" symbol
I call function with IERC721Metadata token NFT totalSupply
I call function with IERC721 token NFT balanceOf owner
I call function with HederaTokenService isToken token FUNGIBLE
I call function with HederaTokenService isFrozen token FUNGIBLE, account
I call function with HederaTokenService isKyc token FUNGIBLE, account
I call function with HederaTokenService getTokenDefaultFreezeStatus token FUNGIBLE
I call function with HederaTokenService getTokenDefaultKycStatus token FUNGIBLE
I call function with update and I expect return of the updated value
I call function that makes N times state update
I call function with nested deploy using create function
I call function with nested deploy using create2 function
I call function with transfer that returns the balance
I directly call Ethereum precompile 0x01
I directly call Ethereum precompile 0x02
I burn FUNGIBLE token and get the total supply and balance
I mint a NFT
the mirror node should return status 200 for the HAPI transaction
I burn NFT and get the total supply and balance
I pause "FUNGIBLE" token, unpause and get the status of the token
I pause "NFT" token, unpause and get the status of the token
I associate FUNGIBLE token to receiver account
the mirror node should return status 200 for the HAPI transaction
I associate NFT token to receiver account
the mirror node should return status 200 for the HAPI transaction
I approve and transfer FUNGIBLE token to receiver account
the mirror node should return status 200 for the HAPI transaction
I approve and transfer NFT token to receiver account
the mirror node should return status 200 for the HAPI transaction
I mint FUNGIBLE token and get the total supply and balance
I mint NFT token and get the total supply and balance
I wipe FUNGIBLE token and get the total supply and balance
I wipe NFT and get the total supply and balance
I freeze "FUNGIBLE" token, unfreeze and get status
I freeze "NFT" token, unfreeze and get status
I associate precompile contract with the tokens
the mirror node should return status 200 for the HAPI transaction
I transfer FUNGIBLE token to the precompile contract
the mirror node should return status 200 for the HAPI transaction
I dissociate a NFT and fail transfer
I approve and transfer NFT token to the precompile contract
the mirror node should return status 200 for the HAPI transaction
I approve a FUNGIBLE token and get allowance
I approve a NFT token and get allowance
I dissociate a FUNGIBLE token and fail transfer
I approve a NFT token and transfer it
I associate FUNGIBLE_KYC_UNFROZEN token to receiver account
the mirror node should return status 200 for the HAPI transaction
I grant and revoke KYC
I approve a FUNGIBLE token and transfer it
I successfully update the balance of an account and get the updated balance after 2 seconds
 org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"_status":{"messages":[{"message":"FAIL_INVALID","detail":"","data":""}]}}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:103)
	at org.springframework.web.client.StatusHandler.lambda$defaultHandler$3(StatusHandler.java:86)
	at org.springframework.web.client.StatusHandler.handle(StatusHandler.java:146)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.applyStatusHandlers(DefaultRestClient.java:838)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.lambda$readBody$4(DefaultRestClient.java:827)
	at org.springframework.web.client.DefaultRestClient.readWithMessageConverters(DefaultRestClient.java:216)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.readBody(DefaultRestClient.java:826)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.lambda$body$0(DefaultRestClient.java:757)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:586)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchange(DefaultRestClient.java:540)
	at org.springframework.web.client.RestClient$RequestHeadersSpec.exchange(RestClient.java:680)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.executeAndExtract(DefaultRestClient.java:821)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.body(DefaultRestClient.java:757)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.lambda$callPostRestEndpoint$5(MirrorNodeClient.java:561)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:357)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:230)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.callPostRestEndpoint(MirrorNodeClient.java:558)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.contractsCall(MirrorNodeClient.java:325)
	at org.hiero.mirror.test.e2e.acceptance.steps.AbstractFeature.callContract(AbstractFeature.java:181)
	at org.hiero.mirror.test.e2e.acceptance.steps.AbstractFeature.callContract(AbstractFeature.java:166)
	at org.hiero.mirror.test.e2e.acceptance.steps.AbstractFeature.callContract(AbstractFeature.java:152)
	at org.hiero.mirror.test.e2e.acceptance.steps.CallFeature.ierc721MetadataTokenName(CallFeature.java:238)
	at ✽.I call function with IERC721Metadata token "NFT" name(classpath:features/contract/call.feature:11)

2025-11-10T09:09:56.602Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.c.MirrorNodeClient GET http://mirror-1-rest/api/v1/contracts/00000000000000000000000000000000000003fa: 200 OK 
2025-11-10T09:09:56.603Z  INFO ForkJoinPool-1-worker-7 o.h.m.t.e.a.s.EquivalenceFeature Executing step: I execute selfdestruct and set beneficiary to 358 num 
2025-11-10T09:09:56.603Z  INFO ForkJoinPool-1-worker-4 o.h.m.t.e.a.s.CallFeature Executing step: I call function with IERC721Metadata token "NFT" symbol 
2025-11-10T09:09:56.603Z  INFO ForkJoinPool-1-worker-4 o.h.m.t.e.a.s.CallFeature Executing step: I call function with IERC721Metadata token NFT totalSupply 
```

### Hedera network

other

### Version

0.138.0

### Operating system

None

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:
This PR improves the mapping of web3 error response codes with HTTP statuses. In case of `CONTRACT_EXECUTION_EXCEPTION` and `FAIL_INVALID` response codes, the web3 controller will now return `500 Internal Server Error`, which should properly trigger the retry mechanisms inside acceptance tests. Previously it returned a `400 Bad Request` response, which was omitted for retrying.

**Related issue(s)**:

Fixes #12385

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java [hunk 1]
```diff
@@ -228,7 +228,10 @@ public void approveAndTransferNftToPrecompileContract() throws InvalidProtocolBu
     }
 
     // ETHCALL-017
-    @RetryAsserts
+    @Retryable(
```
Comment (bilyana-gospodinova) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java]: If we decide to go with this approach, shouldn't we enhance the existing `@RetryAsserts` annotation with the `HttpClientErrorException`? The same issue with solo/infrastructure could easily happen with the next method (or any other method) as well: `I call function with IERC721Metadata token "NFT" symbol`

Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java]: Added a new `RetryConnection` annotation that targets connection issues specifically.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java [hunk 2]
```diff
@@ -28,15 +28,15 @@ public class RestProperties implements ApiProperties {
     private String baseUrl;
 
     @Min(1)
-    private int maxAttempts = 20;
+    private int maxAttempts = 40;
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: Need to document changes in test README

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java [hunk 3]
```diff
@@ -28,15 +28,15 @@ public class RestProperties implements ApiProperties {
...
 
     @NotNull
     @DurationMin(millis = 500L)
     private Duration maxBackoff = Duration.ofSeconds(4L);
 
     @NotNull
     @DurationMin(millis = 100L)
-    private Duration minBackoff = Duration.ofMillis(500L);
+    private Duration minBackoff = Duration.ofSeconds(1L);
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: Doubt this change makes any impact. It will double on the second attempt and there's 40 attempts. Probably can revert to favor a quicker initial retry.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java [hunk 4]
```diff
@@ -508,10 +506,6 @@ public void ethCallBurnFungibleTokenGetTotalSupplyAndBalanceOfTreasury() {
                 .isEqualTo(intValue(results.get(3)));
     }
 
-    @Retryable(
-            retryFor = {HttpClientErrorException.class},
-            backoff = @Backoff(delayExpression = "#{@acceptanceTestProperties.backOffPeriod.toMillis()}"),
-            maxAttemptsExpression = "#{@acceptanceTestProperties.maxRetries}")
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java:514]: Why would we remove this retry of HttpClientErrorException but not add RetryConnection?

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java [hunk 5]
```diff
@@ -228,7 +226,7 @@ public void approveAndTransferNftToPrecompileContract() throws InvalidProtocolBu
     }
 
     // ETHCALL-017
-    @RetryAsserts
+    @RetryConnection
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java]: I'm not convinced this is the best place to retry HTTP errors. All HTTP communication that would throw a `HttpClientErrorException` would go through the `RestClient`. You should make such tweaks in `ClientConfiguration`.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java (hunk 2 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: Reduced back to 20. Since we have exponentialBackoff, the number of retries should be enough.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java (hunk 3 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: Reverted

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java (hunk 4 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java:514]: This logic is now moved to ClientConfiguration and RestClient

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java (hunk 5 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/steps/CallFeature.java]: This logic is now moved to ClientConfiguration and RestClient

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/ClientConfiguration.java [hunk 6]
```diff
@@ -61,7 +63,9 @@ RetryTemplate retryTemplate() {
                 PrecheckStatusException.class,
                 ReceiptStatusException.class,
                 RuntimeException.class,
-                TimeoutException.class);
+                TimeoutException.class,
+                HttpClientErrorException.class,
+                ResourceAccessException.class);
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/ClientConfiguration.java]: This RetryTemplate seems to be just used by SDK calls. The SDK doesn't use Spring so would never throw a Spring exception. So think we can revert this and just use the change in `shouldRetry`.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java [hunk 7]
```diff
@@ -38,10 +40,19 @@ public class RestProperties implements ApiProperties {
...
 
+    private boolean retryOnHttpException = true;
+
     // Don't retry negative test cases
     public boolean shouldRetry(Throwable t) {
-        return !(t instanceof HttpClientErrorException e)
-                || (e.getStatusCode() != HttpStatus.BAD_REQUEST && e.getStatusCode() != HttpStatus.NOT_IMPLEMENTED);
+        boolean shouldRetry;
+        if (retryOnHttpException) {
+            shouldRetry = !(t instanceof HttpClientErrorException e) || e.getStatusCode() != HttpStatus.NOT_IMPLEMENTED;
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: This only changes it to retry bad request 400 errors. Why would we want to change that behavior? Bad user input can never succeed.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java [hunk 8]
```diff
@@ -38,10 +40,19 @@ public class RestProperties implements ApiProperties {
...
+        } else {
+            shouldRetry = !(t instanceof HttpClientErrorException e)
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: If we keep this if/else, should just return directly instead of store into a temporary variable.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java (hunk 7 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: I wanted to adapt the logic, so that retry happens in `HttpClientErrorException` except it's a `NOT_IMPLEMENTED` error, so the correct statement should be:

 `shouldRetry = t instanceof HttpClientErrorException e && e.getStatusCode() != HttpStatus.NOT_IMPLEMENTED;`

Comment (steven-sheehy) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: If you change it that when then it would not retry non-HttpClientErrorException like server exceptions or lower level HTTP transport errors.

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/ClientConfiguration.java (hunk 6 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/ClientConfiguration.java]: Removed

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java (hunk 7 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: I refactored the check

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java (hunk 8 above)
Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: Fixed

File: test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java [hunk 9]
```diff
@@ -38,10 +38,14 @@ public class RestProperties implements ApiProperties {
     @DurationMin(millis = 100L)
     private Duration minBackoff = Duration.ofMillis(500L);
 
+    private boolean retryOnBadRequestException = true;
+
     // Don't retry negative test cases
     public boolean shouldRetry(Throwable t) {
         return !(t instanceof HttpClientErrorException e)
-                || (e.getStatusCode() != HttpStatus.BAD_REQUEST && e.getStatusCode() != HttpStatus.NOT_IMPLEMENTED);
+                || (retryOnBadRequestException
```
Comment (steven-sheehy) [inline test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: Think the real problem is that we return 400 for FAIL_INVALID and other system errors in web3 instead of 5xx which will get retried.

Comment (IvanKavaldzhiev) [reply test/src/test/java/org/hiero/mirror/test/e2e/acceptance/config/RestProperties.java]: I adapted the web3 mapping logic in GenericControllerAdvice.

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java [hunk 10]
```diff
@@ -78,9 +80,17 @@ private ResponseEntity<?> mirrorEvmTransactionError(
         final var childTransactionErrors = e.getChildTransactionErrors().stream()
                 .map(message -> new ErrorMessage(message, StringUtils.EMPTY, StringUtils.EMPTY))
                 .toList();
-        return new ResponseEntity<>(
-                new GenericErrorResponse(e.getMessage(), e.getDetail(), e.getData(), childTransactionErrors),
-                BAD_REQUEST);
+        if (e.getMessage() != null
+                && (FAIL_INVALID.name().equals(e.getMessage())
+                        || CONTRACT_EXECUTION_EXCEPTION.name().equals(e.getMessage()))) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: I don't think `CONTRACT_EXECUTION_EXCEPTION` is a server error but more a generic fallback error. Please clarify.

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java [hunk 11]
```diff
@@ -78,9 +80,17 @@ private ResponseEntity<?> mirrorEvmTransactionError(
         final var childTransactionErrors = e.getChildTransactionErrors().stream()
                 .map(message -> new ErrorMessage(message, StringUtils.EMPTY, StringUtils.EMPTY))
                 .toList();
-        return new ResponseEntity<>(
-                new GenericErrorResponse(e.getMessage(), e.getDetail(), e.getData(), childTransactionErrors),
-                BAD_REQUEST);
+        if (e.getMessage() != null
+                && (FAIL_INVALID.name().equals(e.getMessage())
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: We should enhance `MirrorEvmTransactionException` to store the `ResponseCodeEnum` so we don't have to compare by string. It's already passed in constructor.

Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: We should create a `private static final Set<ResponseCodeEnum> SERVER_RESPONSE_CODES = new EnumSet.of(...)` and just check if exception status is in set.

Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: We should have at minimum: FAIL_INVALID, FAIL_FEE, FAIL_BALANCE, PLATFORM_NOT_ACTIVE, PLATFORM_TRANSACTION_NOT_CREATED

Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: Added

Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: Added

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java (hunk 10 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: It's a fallback error, in case all the rest of the response codes were not used. In my opinion, it can be interpreted as an unexpected or unclear server error during smart contract execution.

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java (hunk 11 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: Added

File: web3/src/test/java/org/hiero/mirror/web3/controller/ContractControllerTest.java [hunk 12]
```diff
@@ -411,6 +412,31 @@ void callWithBlockNumberNotFoundExceptionTest() throws Exception {
...
+    @ValueSource(
+            strings = {
+                "FAIL_INVALID",
+                "FAIL_FEE",
+                "FAIL_BALANCE",
+                "PLATFORM_NOT_ACTIVE",
+                "PLATFORM_TRANSACTION_NOT_CREATED",
+                "TRANSACTION_EXPIRED",
+                "UNKNOWN",
+                "WAITING_FOR_LEDGER_ID"
```
Comment (steven-sheehy) [inline web3/src/test/java/org/hiero/mirror/web3/controller/ContractControllerTest.java]: Should use an enum source and expose package private response codes from advice to stay DRY.

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java [hunk 13]
```diff
@@ -78,9 +99,16 @@ private ResponseEntity<?> mirrorEvmTransactionError(
         final var childTransactionErrors = e.getChildTransactionErrors().stream()
                 .map(message -> new ErrorMessage(message, StringUtils.EMPTY, StringUtils.EMPTY))
                 .toList();
-        return new ResponseEntity<>(
-                new GenericErrorResponse(e.getMessage(), e.getDetail(), e.getData(), childTransactionErrors),
-                BAD_REQUEST);
+
+        if (e.getResponseCode() != null && SERVER_RESPONSE_CODES.contains(e.getResponseCode())) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: The set returns false for null.

```suggestion
        if (SERVER_RESPONSE_CODES.contains(e.getResponseCode())) {
```

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java [hunk 14]
```diff
@@ -47,6 +58,16 @@
 @Order(Ordered.HIGHEST_PRECEDENCE)
 class GenericControllerAdvice extends ResponseEntityExceptionHandler {
 
+    private static final Set<ResponseCodeEnum> SERVER_RESPONSE_CODES = EnumSet.of(
+            FAIL_INVALID,
+            FAIL_FEE,
+            FAIL_BALANCE,
+            PLATFORM_NOT_ACTIVE,
+            PLATFORM_TRANSACTION_NOT_CREATED,
+            TRANSACTION_EXPIRED,
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: TRANSACTION_EXPIRED should be a user error.

File: web3/src/test/java/org/hiero/mirror/web3/controller/ContractControllerTest.java (hunk 12 above)
Comment (IvanKavaldzhiev) [reply web3/src/test/java/org/hiero/mirror/web3/controller/ContractControllerTest.java]: Decided to use MethodSource. I think it's more simple that way.

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java (hunk 13 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: Fixed

File: web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java (hunk 14 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/org/hiero/mirror/web3/controller/GenericControllerAdvice.java]: Removed

**Review by steven-sheehy — APPROVED** [review]
LGTM
