### PR TITLE
Fix flaky rest tests

### LINKED ISSUE #10992: Flaky REST Gradle workflow
### Description

The REST API Gradle workflow frequently fails in GitHub Actions due to some container test setup issues.

### Steps to reproduce

1. Push a PR
2. It triggers the Gradle build workflow
3. The REST API steps periodically fail and have to be retried

### Additional context

https://github.com/hiero-ledger/hiero-mirror-node/actions/runs/14598767151/job/40951347248?pr=10991

```
ERROR: Unable to obtain connection from database (jdbc:postgresql://localhost:32786/mirror_node) for user 'mirror_node': Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused
PASS __tests__/accounts.deduplication.timestamp.test.js (7893 ms)
ERROR: Unable to obtain connection from database (jdbc:postgresql://localhost:32786/mirror_node) for user 'mirror_node': Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused
ERROR: Unable to obtain connection from database (jdbc:postgresql://localhost:32786/mirror_node) for user 'mirror_node': Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32786 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Caused by: java.net.ConnectException: Connection refused

Error: expect(received).resolves.toBeNull()

Received promise rejected instead of resolved
Rejected to value: [Error: relation "record_file" does not exist]

    at expect (node_modules/expect/build/index.js:113:15)
    at Object.expect (__tests__/service/recordFileService.test.js:70:11)
```

### Hedera network

other

### Version

main

### Operating system

None

### PR DESCRIPTION
**Pull request by xin-hedera**
**Description**:

This PR fixes the flaky rest tests

- Move flyway initialization to globalSetup and do it only once
- Fail the whole test suite early if retries are exhausted
- Bump flyway jar to v11.8.2

**Related issue(s)**:

Fixes #10992 

**Notes for reviewer**:

We have separate storage directories for jest worker processes and for a fresh clone, each worker, when running the first integration test, will do `flyway migrate` and trigger the gzipped flyway jar downloading.

Sometimes, downloading the artifact just fails, then the database is left in a state without any of the tables we need, so we see a lot of `relation xxx doesn't exist` errors in integration tests.

The downside of the change is now we try to initialize flyway for all tests, even though the test doesn't need database / flyway.

Jest doesn't provide the list of test files to run in its global setup context, nor a function to get that list.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: rest/__tests__/globalSetup.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+  };
+
+  fs.mkdirSync(FLYWAY_DATA_PATH, {recursive: true});
+  fs.writeFileSync(flywayConfigPath, JSON.stringify(flywayConfig));
+
+  let retries = 10;
+  while (retries-- > 0) {
+    try {
+      execSync(`node ${FLYWAY_EXE_PATH} -c ${flywayConfigPath} info`, {stdio: 'pipe'});
+      break;
```
Comment (xin-hedera) [inline rest/__tests__/globalSetup.js:30]: the `break` in theory is dead code, since the jdbc url has an invalid port (-1), `execSync` will always throw. However, just leave it here to avoid any surprises

**Review by steven-sheehy — APPROVED** [review]
LGTM
