### PR TITLE
CORS Issue with REST Java API POST Endpoints

### LINKED ISSUE #12629: CORS Issue with REST Java API POST Endpoints
## Description
When running Solo tests in the browser, tests fail when making POST requests to the Java REST API due to missing CORS configuration.

### Steps to reproduce

1. Start mirror node REST Java API
2. Attempt POST request from browser with different origin
3. Preflight OPTIONS request fails with 403

## Error
```
Access to fetch at 'http://127.0.0.1:8084/api/v1/network/fees?mode=STATE'
from origin 'http://localhost:63315' has been blocked by CORS policy:
Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

## Fix

Add CORS configuration

### Hedera network

other

### Version

0.146.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by martingeorgiev1**
**Description**:

Add CORS configuration to REST Java API to allow cross-origin requests from browsers.

* Add CORS configurer bean to GenericControllerAdvice
* Allow all origins for /api/** endpoints
* Align with TypeScript REST API and web3 module patterns

**Related issue(s)**:

Fixes #12629 

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java [hunk 1]
```diff
@@ -60,6 +63,17 @@ class GenericControllerAdvice extends ResponseEntityExceptionHandler {
     private final MessageSource messageSource = new ErrorMessageSource();
     private final RestJavaProperties properties;
 
+    @Bean
+    @SuppressWarnings("java:S5122") // Make sure that enabling CORS is safe here.
+    public WebMvcConfigurer corsConfigurer() {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]:
```suggestion
   WebMvcConfigurer corsConfigurer() {
```

Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/controller/GenericControllerAdvice.java]: We should have a test like `ContractControllerTest.callSuccessCors()` in `ControllerTest.RestTest`.
