### PR TITLE
Load web3 resources during k8s readiness probe

### LINKED ISSUE #11802: CPU spikes in modularized web3 pods
### Description

There are cpu spikes in web3 pods with modularized flow enabled. Might be the cause for timeouts and slowness overall.

### Steps to reproduce

Restarts and pod scaling seem to trigger cpu spikes.

### Additional context

Image

### Hedera network

mainnet, other

### Version

v0.135.0

### Operating system

None

### PR DESCRIPTION
**Pull request by sdimitrov9**
**Description**:
Use ApplicationReadyEvent to load resources by calling simple contract before k8s readiness elapses.

**Related issue(s)**:

Fixes #11802 

**Notes for the reviewer**
The contract call for the oldest EVM version is failing with PAYER_ACCOUNT_NOT_FOUND, the calls with the other EVM versions are passing.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        final Address HTS_PRECOMPILE_ADDRESS = Address.fromHexString("0x0000000000000000000000000000000000000167");
+        final Bytes IS_TOKEN_CALL_DATA =
+                Bytes.fromHexString("0x997b63220000000000000000000000000000000000000000000000000000000000000000");
+        final Address SENDER_ADDRESS = Address.fromHexString("0x0000000000000000000000000000000000000002");
+
+        return ContractExecutionParameters.builder()
+                .block(BlockType.LATEST)
+                .callData(IS_TOKEN_CALL_DATA)
+                .callType(CallType.ETH_CALL)
+                .gas(15_000_000L)
```
Comment (kselveliev) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: I guess we don't need that much gas for this call.

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+     * (isToken() of HTS precompile in this case) using the system treasury account as sender
+     */
+    protected ContractExecutionParameters getContractExecutionParameters() {
+        final Address HTS_PRECOMPILE_ADDRESS = Address.fromHexString("0x0000000000000000000000000000000000000167");
+        final Bytes IS_TOKEN_CALL_DATA =
+                Bytes.fromHexString("0x997b63220000000000000000000000000000000000000000000000000000000000000000");
+        final Address SENDER_ADDRESS = Address.fromHexString("0x0000000000000000000000000000000000000002");
+
+        return ContractExecutionParameters.builder()
+                .block(BlockType.LATEST)
```
Comment (xin-hedera) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: should we also make a historical call?

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+                .callData(IS_TOKEN_CALL_DATA)
+                .callType(CallType.ETH_CALL)
+                .gas(15_000_000L)
+                .isEstimate(false)
+                .isModularized(true)
+                .isStatic(true)
+                .receiver(HTS_PRECOMPILE_ADDRESS)
+                .sender(new HederaEvmAccount(SENDER_ADDRESS))
```
Comment (kselveliev) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: We might also not need a sender address for isToken call.

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+    public Web3Warmup(@Qualifier("contractExecutionService") ContractCallService contractCallService) {
+        this.contractCallService = contractCallService;
+    }
+
+    /**
+     * Call simple read only contract function to load web3
+     * resources before k8s readiness elapses
+     */
+    @EventListener(ApplicationReadyEvent.class)
+    public void triggerResourceLoadingByFirstContractCallAfterStartup() {
```
Comment (bilyana-gospodinova) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: We need this warm up only if the modularizedServices flag is enabled. Otherwise, we can skip.

Comment (xin-hedera) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: kinda feel the method name is too long and explicit. perhaps sth like `warmupCall()`

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+import org.hiero.mirror.web3.service.model.CallServiceParameters.CallType;
+import org.hiero.mirror.web3.service.model.ContractExecutionParameters;
+import org.hiero.mirror.web3.viewmodel.BlockType;
+import org.hyperledger.besu.datatypes.Address;
+import org.springframework.beans.factory.annotation.Qualifier;
+import org.springframework.boot.context.event.ApplicationReadyEvent;
+import org.springframework.context.event.EventListener;
+
+@Named
+public class Web3Warmup {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]:
```suggestion
final class ApplicationWarmup {
```

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+
+    private final ContractCallService contractCallService;
+
+    public Web3Warmup(@Qualifier("contractExecutionService") ContractCallService contractCallService) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Remove constructor, add RequiredArgsConstructor and move qualifier to the field. Lombok will copy it to the constructor

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 4 above)
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: This should probably be `@Async`.

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 2 above)
Comment (steven-sheehy) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: In addition to latest, we should warm up all historical EVM versions e.g. `properties.getNetwork().getEvmVersions()`. For non-mainnet environments that will be empty which is fine.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 1 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Changed to 1M

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 2 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 4 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Done

Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 5 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 6 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 4 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java (hunk 3 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/Web3Warmup.java]: The contract call fails without a valid sender.

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java [hunk 7]
```diff
@@ -0,0 +1,76 @@
...
+     * resources before k8s readiness elapses. Method is async to
+     * run it in a separate thread and not block the main one by
+     * potentially waiting for the contract call to complete.
+     */
+    @Async
+    @EventListener(ApplicationReadyEvent.class)
+    public void warmupCall() {
+        if (evmProperties.isModularizedServices()) {
+            final var evmVersions = evmProperties.getEvmVersions();
+            evmVersions.descendingMap().entrySet().stream().forEach(entry -> {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: There's no latest entry in map so you still have to always invoke that one explicitly.

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+                final var blockType =
+                        new BlockType(String.valueOf(entry.getValue().minor()), entry.getKey());
+                try {
+                    ContractExecutionParameters contractExecutionParameters = getContractExecutionParameters(blockType);
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]:
```suggestion
                    final var contractExecutionParameters = getContractExecutionParameters(blockType);
```

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+    }
+
+    /**
+     * Prepare contract execution parameters to call simple read-only function
+     * (isToken() of HTS precompile in this case) using the system treasury account as sender
+     */
+    private ContractExecutionParameters getContractExecutionParameters(BlockType blockType) {
+        final Address HTS_PRECOMPILE_ADDRESS = Address.fromHexString("0x0000000000000000000000000000000000000167");
+        final Bytes IS_TOKEN_CALL_DATA =
+                Bytes.fromHexString("0x997b63220000000000000000000000000000000000000000000000000000000000000000");
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: These aren't static so they should be named lower camel case. Could also remove the variable and create them inline in the builder like the others.

```suggestion
        final var htsSystemContract = Address.fromHexString("0x0000000000000000000000000000000000000167");
        final var isTokenCallData = Bytes.fromHexString("0x997b63220000000000000000000000000000000000000000000000000000000000000000");
```

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java [hunk 10]
```diff
@@ -0,0 +1,76 @@
...
+        if (evmProperties.isModularizedServices()) {
+            final var evmVersions = evmProperties.getEvmVersions();
+            evmVersions.descendingMap().entrySet().stream().forEach(entry -> {
+                final var blockType =
+                        new BlockType(String.valueOf(entry.getValue().minor()), entry.getKey());
+                try {
+                    ContractExecutionParameters contractExecutionParameters = getContractExecutionParameters(blockType);
+                    contractCallService.callContract(contractExecutionParameters);
+                } catch (Exception e) {
+                    log.warn("Warmup call for block {} failed: {}", blockType, e.getMessage());
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Catching exception code smell and this is probably worthy of an error log and stacktrace.

```suggestion
                } catch (RuntimeException e) {
                    log.error("Warmup call for block {} failed:", blockType, e);
```

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java [hunk 11]
```diff
@@ -0,0 +1,76 @@
...
+    /**
+     * Call simple read only contract function to load web3
+     * resources before k8s readiness elapses. Method is async to
+     * run it in a separate thread and not block the main one by
+     * potentially waiting for the contract call to complete.
+     */
+    @Async
+    @EventListener(ApplicationReadyEvent.class)
+    public void warmupCall() {
+        if (evmProperties.isModularizedServices()) {
```
Comment (steven-sheehy) [inline web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Prefer fail fast so it reduces nested statements.

```suggestion
        if (!evmProperties.isModularizedServices()) {
            return;
```

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java (hunk 11 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java (hunk 10 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java (hunk 9 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Fixed

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java (hunk 8 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Modified

File: web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java (hunk 7 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/state/ApplicationWarmup.java]: Fixed

**Review by IvanKavaldzhiev — APPROVED** [review]
LGTM

**Review by xin-hedera — APPROVED** [review]
LGTM
