### PR TITLE
Fix failing web3 tests with non-zero shard and realm

### LINKED ISSUE #11456: Update Contract Call Tests to work with non-zero shard and realm
### Problem

After updating to tests to work with non zero shard and realm in web3, there are still some contract call tests failing. 

### Solution

* Configure shard/realm with non zero values
* run web3 test task
* Notice the test failures
* Fix remaining test failures

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by IvanKavaldzhiev**
**Description**:
This PR fixes the remaining failing web3 tests with non-zero shard and realm. They were only mono code based tests.

**Related issue(s)**:

Fixes #11456 

**Notes for reviewer**:

Dependant on #11542 

**Checklist**

- [X] Documented (Code comments, README, etc.)
- [X] Tested (unit, integration, etc.)

### CODE REVIEW

File: web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java [hunk 1]
```diff
@@ -402,7 +402,7 @@ private static TokenCreateWrapper getTokenCreateWrapperFungible(
                 isFungible,
                 tokenName,
                 tokenSymbol,
-                tokenTreasury.getAccountNum() != 0 ? tokenTreasury : null,
+                (tokenTreasury.getShardNum() != 0 || tokenTreasury.getRealmNum() != 0) ? tokenTreasury : null,
```
Comment (xin-hedera) [inline web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java]: why is this needed? The logic now becomes `tokenTreasury` is only valid when it has non-zero shard or non-zero realm.

The original logic should work regardless of shard / realm value since an entity whose number = 0 is not valid in any shard / realm network.

**Comment by kselveliev** [comment]
Probably needs a bit more adjustments since web3 check is failing

File: web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java (hunk 1 above)
Comment (IvanKavaldzhiev) [reply web3/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java]: Correct, the tests are failing with shard/realm=0. I reverted the changes.

**Review by xin-hedera — APPROVED** [review]
LGTM
