### PR TITLE
Set transaction fee and patch nonce when building ethereum transaction body

### LINKED ISSUE #12928: Acceptance test workflow failed with `INSUFFICIENT_TX_FEE` from web3 opcodes endpoint
### Description

Acceptance test workflow started to fail after this [PR](https://github.com/hiero-ledger/hiero-mirror-node/pull/12841)

specifically, it failed when calling web3 opcode endpoint

```
2026-02-10T19:20:05.542Z  INFO ForkJoinPool-1-worker-4 o.h.m.t.e.a.s.EthereumFeature Executing step: [32mthe mirror node contract results opcodes API should return a non-empty response[0m 
2026-02-10T19:20:05.542Z  INFO ForkJoinPool-1-worker-4 o.h.m.t.e.a.s.EthereumFeature Opcode tracer is enabled -> verify contract results opcodes against web3. 
2026-02-10T19:20:05.736Z  INFO ForkJoinPool-1-worker-4 o.h.m.t.e.a.c.MirrorNodeClient GET http://mirror-1-web3/api/v1/contracts/results/0.0.1003-1770751193-736000057/opcodes: 400 BAD_REQUEST 
2026-02-10T19:20:05.739Z ERROR ForkJoinPool-1-worker-4 o.h.m.t.e.a.s.EthereumFeature Scenario failure: 
[32mI successfully created a signer account with an EVM address alias[0m
[32mI successfully create contract by Legacy ethereum transaction[0m
[32mthe mirror node REST API should return status 200 for the eth contract creation transaction[0m
[31mthe mirror node contract results opcodes API should return a non-empty response <- 400 Bad Request: "{"_status":{"messages":[{"message":"INSUFFICIENT_TX_FEE","detail":"","data":""}]}}"[0m
[90mI successfully call function using EIP-1559 ethereum transaction[0m
[90mthe mirror node REST API should return status 200 for the ethereum transaction[0m
[90mthe mirror node REST API should verify the ethereum called contract function[0m
[90mthe mirror node Rest API should verify the contracts have correct nonce[0m
[90mI successfully call function using EIP-2930 ethereum transaction[0m
[90mthe mirror node REST API should return status 200 for the ethereum transaction[0m
[90mthe mirror node REST API should verify the ethereum called contract function[0m
 org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: "{"_status":{"messages":[{"message":"INSUFFICIENT_TX_FEE","detail":"","data":""}]}}"
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:106)
	at org.springframework.web.client.StatusHandler.createException(StatusHandler.java:132)
	at org.springframework.web.client.StatusHandler.lambda$createDefaultStatusHandler$1(StatusHandler.java:107)
	at org.springframework.web.client.StatusHandler.handle(StatusHandler.java:75)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.applyStatusHandlers(DefaultRestClient.java:915)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.lambda$readBody$0(DefaultRestClient.java:904)
	at org.springframework.web.client.DefaultRestClient.readWithMessageConverters(DefaultRestClient.java:223)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.readBody(DefaultRestClient.java:903)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.lambda$body$0(DefaultRestClient.java:818)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:612)
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchange(DefaultRestClient.java:567)
	at org.springframework.web.client.RestClient$RequestHeadersSpec.exchange(RestClient.java:750)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.executeAndExtract(DefaultRestClient.java:896)
	at org.springframework.web.client.DefaultRestClient$DefaultResponseSpec.body(DefaultRestClient.java:818)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.lambda$callWeb3GetRestEndpoint$0(MirrorNodeClient.java:716)
	at org.springframework.core.retry.RetryTemplate.execute(RetryTemplate.java:135)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.retry(MirrorNodeClient.java:601)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.callWeb3GetRestEndpoint(MirrorNodeClient.java:714)
	at org.hiero.mirror.test.e2e.acceptance.client.MirrorNodeClient.getContractResultsOpcodes(MirrorNodeClient.java:332)
	at org.hiero.mirror.test.e2e.acceptance.steps.EthereumFeature.verifyOpcodes(EthereumFeature.java:148)
	at ✽.the mirror node contract results opcodes API should return a non-empty response(classpath:features/contract/ethereum.feature:10)
```

Note the ethereum transaction and all child transactions are successful.

### Steps to reproduce

Check recent acceptance workflow runs. Also can reproduce by running it in a local solo cluster, with the same configuration.

### Additional context

_No response_

### Hedera network

other

### Version

0.149.0-SNAPSHOT

### Operating system

None

### PR DESCRIPTION
**Pull request by sdimitrov9**
**Description**:
Set transaction fee when building ethereum transaction body.
Patch nonce to bypass nonce verification during transaction replay.

**Related issue(s)**:

Fixes #12928 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+                return null;
+            }
+            elements = payload.asRLPList().elements();
+            nonceIndex = 1;
+        }
+        if (elements.size() <= nonceIndex) {
+            return null;
+        }
+        return elements.get(nonceIndex).asLong();
+    }
```
Comment (bilyana-gospodinova) [inline web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java]: I think the code is more readable this way:
```suggestion
    public static Long extractNonce(byte[] transactionBytes) {
        if (transactionBytes == null || transactionBytes.length == 0) {
            return null;
        }

        try {
            int firstByte = transactionBytes[0] & 0xFF;
            
            // Legacy RLP lists start with 0xc0-0xff. They don't have the typeByte at the beginning.
            if (firstByte >= 0xc0) {
                return getNonceFromRlpList(transactionBytes, 0);
            } else {
                // Typed transactions: [TypeByte][RLPList]. Nonce is always the second element (index 1).
                byte[] rlpPayload = Arrays.copyOfRange(transactionBytes, 1, transactionBytes.length);
                return getNonceFromRlpList(rlpPayload, 1);
            }
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Decodes an RLP list and extracts an element by index.
     */
    private static Long getNonceFromRlpList(byte[] rlpData, int index) {
        var decoder = RLPDecoder.RLP_STRICT.sequenceIterator(rlpData);
        if (!decoder.hasNext()) return null;

        var list = decoder.next();
        if (!list.isList()) return null;

        var elements = list.asRLPList().elements();
        return elements.size() > index ? elements.get(index).asLong() : null;
    }
```
It explains the differences in the transaction format and it gets more clear why sometimes we read the nonce from the first index and sometimes - from the second.

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java [hunk 2]
```diff
@@ -202,12 +203,41 @@ private TransactionBody buildContractCallTransactionBody(
...
     private TransactionBody buildEthereumTransactionBody(final CallServiceParameters params) {
-        final var ethereumTransactionBuilder = EthereumTransactionBody.newBuilder()
-                .ethereumData(com.hedera.pbj.runtime.io.buffer.Bytes.wrap(
-                        params.getEthereumData().toArrayUnsafe()));
-        return defaultTransactionBodyBuilder(params)
-                .ethereumTransaction(ethereumTransactionBuilder.build())
+        final var data = params.getEthereumData();
+        if (data == null || data.isEmpty()) {
+            log.error("Ethereum data is missing in params!");
+        }
```
Comment (bilyana-gospodinova) [inline web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: Is this check necessary? We call this method only if: 
```
params instanceof ContractDebugParameters
                && params.getEthereumData() != null
                && !params.getEthereumData().isEmpty()
```

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java [hunk 3]
```diff
@@ -202,12 +203,41 @@ private TransactionBody buildContractCallTransactionBody(
...
+                        .maxGasAllowance(Long.MAX_VALUE)
+                        .build())
+                .transactionFee(CONTRACT_CREATE_TX_FEE)
                 .build();
+
+        patchSenderNonce(params);
+        return txnBody;
+    }
+
+    private void patchSenderNonce(final CallServiceParameters params) {
```
Comment (bilyana-gospodinova) [inline web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: Please add a comment here explaining why we need to modify the in-state nonce. It is clear now, but it won't be in some months.

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java (hunk 2 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: Wouldn't we prefer to leave the check to make the code future proof and instead of logging the error to throw IllegalArgumentException?
```
if (data == null || data.isEmpty()) {
            throw new IllegalArgumentException("Ethereum data is missing in params");
        }
```

File: web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java (hunk 1 above)
Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java]: Arrays.copyOfRange() is heavy operation allocating memory and copying every byte from the old array to a new one. Otherwise I combined the best from your proposal with the current solution and now it should be  easier to read, while having the same performance.

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java (hunk 2 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: I don't think we need the same check in multiple places that get called consecutively. This method gets called only internally where we have built the ethereum transaction in the opcodes endpoint. Proper test coverage should ensure that we have built it correctly. This check would make more sense if it gets called with some user input and this is not the case here. Perhaps you can switch the method's input `CallServiceParameters` type to `ContractDebugParameters` to reflect the intention to use the method only for the debug case.

File: web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java (hunk 1 above)
Comment (bilyana-gospodinova) [reply web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java]: That's fine. Perhaps we can gain even more performance if we don't decode all elements from the `RLPList`. We can use the `iterator()` instead of `elements()` and parse only the first and second item.

File: web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+package org.hiero.mirror.web3.utils;
+
+import com.esaulpaugh.headlong.rlp.RLPDecoder;
+import com.esaulpaugh.headlong.rlp.RLPItem;
+import java.util.List;
+import lombok.experimental.UtilityClass;
+import org.jspecify.annotations.Nullable;
+
+@UtilityClass
+public class EthereumTransactionNonceExtractor {
```
Comment (IvanKavaldzhiev) [inline web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java]: It's good to use already present code. You can reuse the `EthTxData.populateEthTxData()` from hapi-utils. Then from `EthTxData` you can directly extract the nonce and this whole class can be deleted.

Comment (sdimitrov9) [reply web3/src/main/java/org/hiero/mirror/web3/utils/EthereumTransactionNonceExtractor.java]: Done

File: web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java [hunk 5]
```diff
@@ -202,12 +203,39 @@ private TransactionBody buildContractCallTransactionBody(
...
+     *  the state, to bypass the nonce verification during transaction replay.
+     */
+    private void patchSenderNonce(final CallServiceParameters params) {
+        if (params.getSender().isZero() && params.getValue() == 0L) {
+            return;
+        }
+        final long nonce = populateEthTxData(params.getEthereumData().toArray()).nonce();
+        if (!ContractCallContext.isInitialized()) {
+            return;
+        }
```
Comment (bilyana-gospodinova) [inline web3/src/main/java/org/hiero/mirror/web3/service/TransactionExecutionService.java]: This can be combined with lines 224-226. This way we will not do parsing unnecessarily.

**Review by bilyana-gospodinova — APPROVED** [review]
