### PR TITLE
Fix gas calculation in /network/fees rest-java API

### LINKED ISSUE #12946: Network fees endpoint shows incorrect gas
### Description

The network fees endpoint will show incorrect gas if the wrong exchange rate is used and the difference is big enough.

The issue behind the scene is rest-java service always use the `currentRate` exchange rate from the latest exchange rate file active at timestamp `T`. However it is possible that the `currentRate`'s expirationTime is before `T`, and the effective active exchange rate should be `nextRate`.

There is also a potential rounding problem in the way it's calculdated:

`gas * hbarEquiv / (centsEquiv * 1000)`

in consensus node, it's done in two steps

- `gasInTinyCents = gas / 1000`
- `gasInTinyBars = gasInTinyCents * hbarEquiv / centsEquiv`

We should do the same (two-step). It's not a problem now since the gas value in fee schedule is always a multiple of 1000.

### Steps to reproduce

https://mainnet.mirrornode.hedera.com/api/v1/network/fees?timestamp=1769544041.288936000

```json
{
  "fees": [
    {
      "gas": 81,
      "transaction_type": "ContractCall"
    },
    {
      "gas": 81,
      "transaction_type": "ContractCreate"
    },
    {
      "gas": 81,
      "transaction_type": "EthereumTransaction"
    }
  ],
  "timestamp": "1768500000.359440900"
}
```

All values should be 80 if `nextRate` was used.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.147.0

### Operating system

None

### PR DESCRIPTION
**Pull request by sdimitrov9**
**Description**:
Fix gas calculation in network fees java api by using the calculation approach from consensus node.

**Related issue(s)**:

Fixes #12946 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 1]
```diff
@@ -34,23 +36,26 @@ public interface FeeScheduleMapper {
...
-    default java.util.List<NetworkFee> mapFees(
+    default List<NetworkFee> mapFees(
             SystemFile<CurrentAndNextFeeSchedule> feeScheduleFile,
             SystemFile<ExchangeRateSet> exchangeRateFile,
+            Bound bound,
             Sort.Direction order) {
 
-        var schedule = feeScheduleFile.protobuf().getCurrentFeeSchedule();
-        var rate = exchangeRateFile.protobuf().getCurrentRate();
+        final var schedule = feeScheduleFile.protobuf().getCurrentFeeSchedule();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]: Shouldn't the same logic apply to the fee schedule to get the next if past time?

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 2]
```diff
@@ -60,6 +65,27 @@ default java.util.List<NetworkFee> mapFees(
                 .toList();
     }
 
+    private long getReferenceTimestampNanos(SystemFile<CurrentAndNextFeeSchedule> feeScheduleFile, Bound bound) {
+        final long upperBound = (bound == null || bound.isEmpty()) ? Long.MAX_VALUE : bound.adjustUpperBound();
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]: Bound should never be null (since we return Bound.EMPTY) and adjustUpperBound() should already return max value if empty.

```suggestion
        final long upperBound = bound.adjustUpperBound();
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java [hunk 3]
```diff
@@ -60,6 +65,27 @@ default java.util.List<NetworkFee> mapFees(
...
+        }
+
+        return upperBound;
+    }
+
+    private ExchangeRate getEffectiveExchangeRate(ExchangeRateSet exchangeRateSet, long refTimestampNanos) {
+        final var currentRate = exchangeRateSet.getCurrentRate();
+        final var currentRateExpirationTime = currentRate.getExpirationTime().getSeconds();
+
+        if (refTimestampNanos > currentRateExpirationTime * 1_000_000_000L) {
```
Comment (steven-sheehy) [inline rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]:
```suggestion
        if (refTimestampNanos > currentRateExpirationTime * DomainUtils.NANOS_PER_SECOND) {
```

File: rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java (hunk 1 above)
Comment (sdimitrov9) [reply rest-java/src/main/java/org/hiero/mirror/restjava/mapper/FeeScheduleMapper.java]: Addressed

**Review by xin-hedera — APPROVED** [review]
LGTM
