### PR TITLE
Fix storage slot value removal issue

### LINKED ISSUE #10895: Contract storage update throws `IllegalArgumentException`
### Description

The following exception is observed in the logs:

```
2025-04-11T08:56:13.699Z ERROR tomcat-handler-234508 c.h.n.a.w.h.DispatchProcessor Possibly CATASTROPHIC failure - exception thrown while handling dispatch java.lang.IllegalArgumentException: Cannot change # of storage slots (currently 0) by -1 for contract ContractID[shardNum=0, realmNum=0, contract=OneOf[kind=CONTRACT_NUM, value=5770313]]
	at com.hedera.node.app.service.token.impl.api.TokenServiceApiImpl.updateStorageMetadata(TokenServiceApiImpl.java:316)
	at com.hedera.node.app.service.contract.impl.exec.scope.HandleHederaOperations.updateStorageMetadata(HandleHederaOperations.java:265)
	at com.hedera.node.app.service.contract.impl.infra.IterableStorageManager.lambda$persistChanges$3(IterableStorageManager.java:113)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at com.hedera.node.app.service.contract.impl.infra.IterableStorageManager.persistChanges(IterableStorageManager.java:109)
	at com.hedera.node.app.service.contract.impl.state.RootProxyWorldUpdater.commit(RootProxyWorldUpdater.java:96)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.safeCommit(TransactionProcessor.java:185)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.processTransactionWithParties(TransactionProcessor.java:161)
	at com.hedera.node.app.service.contract.impl.exec.TransactionProcessor.processTransaction(TransactionProcessor.java:123)
	at com.hedera.node.app.service.contract.impl.exec.ContextTransactionProcessor.call(ContextTransactionProcessor.java:142)
	at com.hedera.node.app.service.contract.impl.handlers.ContractCallHandler.handle(ContractCallHandler.java:71)
	at com.hedera.node.app.workflows.dispatcher.TransactionDispatcher.dispatchHandle(TransactionDispatcher.java:145)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.tryHandle(DispatchProcessor.java:146)
	at com.hedera.node.app.workflows.handle.DispatchProcessor.processDispatch(DispatchProcessor.java:125)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors.lambda$newExecutor$0(TransactionExecutors.java:222)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors$DefaultTracerBinding.runWhere(TransactionExecutors.java:284)
	at com.hedera.node.app.workflows.standalone.TransactionExecutors.lambda$newExecutor$1(TransactionExecutors.java:221)
	at com.hedera.mirror.web3.service.TransactionExecutionService.execute(TransactionExecutionService.java:73)
	at com.hedera.mirror.web3.service.ContractCallService.doProcessCall(ContractCallService.java:126)
	at com.hedera.mirror.web3.service.ContractCallService.callContract(ContractCallService.java:116)
	at com.hedera.mirror.web3.service.ContractExecutionService.estimateGas(ContractExecutionService.java:87)
	at com.hedera.mirror.web3.service.ContractExecutionService.lambda$processCall$0(ContractExecutionService.java:60)
	at com.hedera.mirror.web3.common.ContractCallContext.lambda$run$0(ContractCallContext.java:83)
	at java.base/java.lang.ScopedValue$Carrier$CallableAdapter.call(Unknown Source)
	at java.base/jdk.internal.vm.ScopedValueContainer.callWithoutScope(Unknown Source)
	at java.base/jdk.internal.vm.ScopedValueContainer.call(Unknown Source)
	at java.base/java.lang.ScopedValue$Carrier.get(Unknown Source)
	at java.base/java.lang.ScopedValue.getWhere(Unknown Source)
	at com.hedera.mirror.web3.common.ContractCallContext.run(ContractCallContext.java:83)
	at com.hedera.mirror.web3.service.ContractExecutionService.processCall(ContractExecutionService.java:51)
	at com.hedera.mirror.web3.controller.ContractController.call(ContractController.java:66)
```

### Steps to reproduce

N/A

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.107.0

### Operating system

None

### PR DESCRIPTION
**Pull request by kselveliev**
**Description**:
This PR fixes storage slot value removal in modularized flow.

When the account is a contract we need to populate `contractKvPairsNumber` base on its storage values.

Currently it is always 0 and when we try to make a storage slot update where we set value to 0 we get an error.

`Account` - set contractKvPairsNumber 
`AccountReadableKVState` - set `contractKvPairsNumber` to the `Account` model
`StorageContractTest` - add tests for the previously failing scenarios

Fixes #10895

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/keyvalue/AccountReadableKVState.java [hunk 1]
```diff
@@ -103,6 +107,7 @@ private Account accountFromEntity(Entity entity, final Optional<Long> timestamp)
                 .approveForAllNftAllowances(getApproveForAllNfts(entity.getId(), timestamp))
                 .autoRenewAccountId(toAccountId(entity.getAutoRenewAccountId()))
                 .autoRenewSeconds(Objects.requireNonNullElse(entity.getAutoRenewPeriod(), DEFAULT_AUTO_RENEW_PERIOD))
+                .contractKvPairsNumber(getStorageKVPairs(entity, timestamp))
```
Comment (steven-sheehy) [inline hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/keyvalue/AccountReadableKVState.java:110]: Is it truly necessary to set it to an accurate value read from the db or is it sufficient to set it to a sufficiently high number that the the negative slot verification doesn't fail? That is, can we set it to `Integer.MAX_VALUE` and call it a day? I see this contractKvPairsNumber is only used for this validation and rent charging.

Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/keyvalue/AccountReadableKVState.java:110]: If we set Integer. MAX_VALUE we start getting into
`.hedera.mirror.web3.exception.MirrorEvmTransactionException: MAX_CONTRACT_STORAGE_EXCEEDED`
I tried to hack it with Integer.MAX_VALUE/2 but still got the same error.

Maybe if we see what is max contract storage we can hack in a sufficiently high number and it should probably work fine.

Comment (steven-sheehy) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/keyvalue/AccountReadableKVState.java:110]: Guess it should be `ContractsConfig.maxKvPairsIndividual()`?

Comment (kselveliev) [reply hedera-mirror-web3/src/main/java/com/hedera/mirror/web3/state/keyvalue/AccountReadableKVState.java]: Updated to use `ContractsConfig.maxKvPairsIndividual() / 2`. This should cover updates and removals.

**Review by bilyana-gospodinova — DISMISSED** [review]

**Review by nickeynikolovv — APPROVED** [review]
LGTM

File: hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/StorageContractTest.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+        domainBuilder.recordFile().customize(f -> f.bytes(runtimeBytecode)).persist();
+        return entity;
+    }
+
+    private Entity persistHistoricalContract(
+            final byte[] runtimeBytecode, final Address contractAddress, final Range<Long> historicalRange) {
+        final var contractEntityId = entityIdFromEvmAddress(contractAddress);
+        final var evmAddress = toEvmAddress(contractEntityId);
+        final var entity = domainBuilder
+                .entity()
```
Comment (filev94) [inline hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/StorageContractTest.java:97]: You could do domainBuilder.entity(contractEntityId) and skip the setting of id and num in the customize. A bit cleaner IMO. Same for the persistContract above.

Comment (kselveliev) [reply hedera-mirror-web3/src/test/java/com/hedera/mirror/web3/service/StorageContractTest.java]: Addressed

**Review by filev94 — APPROVED** [review]

**Review by steven-sheehy — APPROVED** [review]

**Review by bilyana-gospodinova — APPROVED** [review]
