### PR TITLE
Made weibar migration to async

### LINKED ISSUE #13183: Java db migration v2.24.1 failed with OOM
### Description

V2.24.1 failed in staging with OOM exception:

```
2026-03-20T03:32:35.751Z  INFO main o.f.c.i.c.DbMigrate Migrating schema "public" to version "2.24.1 - Convert ethereum transaction gas and value fields from tinybar to weibar by re-parsing RLP data"
 2026-03-20T03:36:22.025Z  WARN main o.s.b.w.s.r.c.AnnotationConfigReactiveWebServerApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/hibernate/autoconfigure/HibernateJpaConfiguration.class]: Failed to initialize dependency 'flywayInitializer' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/flyway/autoconfigure/FlywayAutoConfiguration$FlywayConfiguration.class]: Java heap space
2026-03-20T03:36:32.121Z ERROR main o.s.b.SpringApplication Application run failed org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/hibernate/autoconfigure/HibernateJpaConfiguration.class]: Failed to initialize dependency 'flywayInitializer' of LoadTimeWeaverAware bean 'entityManagerFactory': Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/flyway/autoconfigure/FlywayAutoConfiguration$FlywayConfiguration.class]: Java heap space
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:201)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:977)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:621)
	at org.springframework.boot.web.server.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:69)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:756)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:445)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.hiero.mirror.importer.ImporterApplication.main(ImporterApplication.java:15)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:106)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:40)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/flyway/autoconfigure/FlywayAutoConfiguration$FlywayConfiguration.class]: Java heap space
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:525)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:371)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:331)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
	... 15 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2530)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:429)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:526)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:436)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:196)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:139)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$query$0(JdbcTemplate.java:738)
	at org.springframework.jdbc.core.JdbcTemplate$$Lambda/0x00000000707236b0.doInPreparedStatement(Unknown Source)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:670)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:732)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:752)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:778)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:205)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:217)
	at org.hiero.mirror.importer.migration.ConvertEthereumTransactionToWeiBarMigration.doMigrate(ConvertEthereumTransactionToWeiBarMigration.java:66)
	at org.hiero.mirror.importer.migration.AbstractJavaMigration.migrate(AbstractJavaMigration.java:40)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:71)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.lambda$execute$0(JavaMigrationExecutor.java:61)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor$$Lambda/0x0000000070732fe8.call(Unknown Source)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:31)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:60)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:391)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:283)
	at org.flywaydb.core.internal.command.DbMigrate$$Lambda/0x0000000070737290.call(Unknown Source)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:59)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:282)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:255)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:153)
	at org.flywaydb.core.internal.command.DbMigrate$$Lambda/0x000000007072fd28.call(Unknown Source)
	at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:77)
```

### Steps to reproduce

see the description

### Additional context

_No response_

### Hedera network

other

### Version

v0.151.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by ashumahajan**
**Description**:
Made weibar migration to async with 5000 rows processing per iteration

Fixes #13183

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 1]
```diff
@@ -2,125 +2,150 @@
...
+            order by consensus_timestamp desc
+            limit 5000
+            """;
 
     private static final String UPDATE_SQL = "update ethereum_transaction set gas_price = ?, "
             + "max_fee_per_gas = ?, max_priority_fee_per_gas = ?, "
             + "value = ? where consensus_timestamp = ?";
 
-    private final ObjectProvider<NamedParameterJdbcOperations> jdbcOperationsProvider;
+    private static final String UPDATE_V2_SQL = "update ethereum_transaction set gas_price = ?, "
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: The update SQL misses two columns, and it should be the same regardless of v1 / v2

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 2]
```diff
@@ -2,125 +2,150 @@
...
+    @Override
+    protected Long getInitial() {
+        return Long.MAX_VALUE;
+    }
+
     @Override
-    public MigrationVersion getVersion() {
-        return v2 ? MigrationVersion.fromVersion("2.24.1") : MigrationVersion.fromVersion("1.119.1");
+    protected MigrationVersion getMinimumVersion() {
+        return MigrationVersion.fromVersion("1.119.0");
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: the minimum version depends on v1/v2, for v2, it should be 2.24.0

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 3]
```diff
@@ -2,125 +2,150 @@
...
-        var failedCount = new AtomicLong(0);
+    @NonNull
+    @Override
+    protected Optional<Long> migratePartial(Long lastConsensusTimestamp) {
+        var params = Map.of("consensusTimestamp", lastConsensusTimestamp);
+        var transactions = getNamedParameterJdbcOperations()
+                .query(
+                        SELECT_TRANSACTIONS_SQL,
+                        params,
+                        (rs, _) -> new TransactionRow(
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: create a final static row mapper, `new DataClassRowMapper<>(TransactionRow.class)` and use it here, install of `ResultSet`

File: importer/src/main/resources/application.yml [hunk 4]
```diff
@@ -19,6 +19,8 @@ hiero:
         tempSchema: temporary
         username: mirror_importer
       migration:
+        convertEthereumTransactionToWeiBarMigration:
+          checksum: 1
```
Comment (xin-hedera) [inline importer/src/main/resources/application.yml]: default is 1, so only when we make changes to the migration we bump up the checksum and it'll run again.

```suggestion
```

File: importer/src/test/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigrationTest.java [hunk 5]
```diff
@@ -38,7 +38,7 @@ class ConvertEthereumTransactionToWeiBarMigrationTest extends ImporterIntegratio
 
     @Test
     void empty() {
-        migration.doMigrate();
+        migration.migrateAsync();
```
Comment (xin-hedera) [inline importer/src/test/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigrationTest.java]: it's an async migration, we need to use awaitility to make the tests more stable. check `TopicMessageLookupMigrationTest` for example

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 6]
```diff
@@ -2,125 +2,150 @@
...
     }
 
     @Override
     public String getDescription() {
         return "Convert ethereum transaction gas and value fields from tinybar to weibar by re-parsing RLP data";
     }
 
+    @NonNull
+    @Override
+    protected Long getInitial() {
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java:91]: we'd need a table to hold the progress (the last consensus timestamp the migration has processed) so when importer restarts before the async migration completes, the migration can resume from where it's left.

can be 
```sql
create table if not exists convert_ethereum_transaction_weibar_progress (
  last_consensus_timestamp bigint not null
);
```

you should override `performSynchronousSteps` to

- create the table
- set initial consensus timestamp to `select min(last_consensus_timestamp) from convert_ethereum_transaction_weibar_progress` and fallback to `Long.MAX_VALUE` when the table is empty

in `getInitial()` always return the initial consensus timestamp

In each `migratePartial`, insert the last consensus timestamp into the table.

In the last `migratePartial`, drop the table.

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 7]
```diff
@@ -2,125 +2,154 @@
...
 
+    @NonNull
     @Override
-    public MigrationVersion getVersion() {
-        return v2 ? MigrationVersion.fromVersion("2.24.1") : MigrationVersion.fromVersion("1.119.1");
+    protected Long getInitial() {
+        return Long.MAX_VALUE;
     }
 
+    private static final Map<Boolean, MigrationVersion> MINIMUM_VERSION = Map.of(
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: move this up to where the other class attributes are

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 8]
```diff
@@ -2,125 +2,178 @@
...
     ConvertEthereumTransactionToWeiBarMigration(
+            DBProperties dbProperties,
             Environment environment,
             ImporterProperties importerProperties,
-            ObjectProvider<NamedParameterJdbcOperations> jdbcOperationsProvider,
-            ObjectProvider<EthereumTransactionParser> ethereumTransactionParserProvider) {
-        super(importerProperties.getMigration());
+            ObjectProvider<JdbcOperations> jdbcOperationsProvider,
+            ObjectProvider<EthereumTransactionParser> ethereumTransactionParserProvider,
+            @Owner ObjectProvider<JdbcOperations> ownerJdbcOperationsProvider,
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: We are mixing database users in the same db transaction (`@Owner` uses `mirror_node`, without the annotation, it's `mirror_importer`), it's bad practice and may cause problems.


```suggestion
            ObjectProvider<EthereumTransactionParser> ethereumTransactionParserProvider,
            @Owner ObjectProvider<JdbcOperations> ownerJdbcOperationsProvider,
```

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 9]
```diff
@@ -2,125 +2,178 @@
...
+            ObjectProvider<TransactionOperations> transactionOperationsProvider) {
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: The `transactionOperations` bean uses `mirror_importer`, we should switch to the owner.

```suggestion
```

Override `getTransactionOperations`, to provide `transactionOperations` with owner jdbcOperations, refer to `FixCryptoAllowanceAmountMigration`

```java
    @Getter(lazy = true)
    private final TransactionOperations transactionOperations = transactionOperations();

    private TransactionOperations transactionOperations() {
        var jdbcTemplate = (JdbcTemplate) getJdbcOperations();
        var transactionManager = new DataSourceTransactionManager(Objects.requireNonNull(jdbcTemplate.getDataSource()));
        return new TransactionTemplate(transactionManager);
    }
```

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 10]
```diff
@@ -2,125 +2,178 @@
...
+            + "value = ? where consensus_timestamp = ? and payer_account_id = ?";
+
+    private static final Map<Boolean, MigrationVersion> MINIMUM_VERSION = Map.of(
+            Boolean.FALSE, MigrationVersion.fromVersion("1.119.0"),
+            Boolean.TRUE, MigrationVersion.fromVersion("2.24.0"));
 
-    private final ObjectProvider<NamedParameterJdbcOperations> jdbcOperationsProvider;
     private final ObjectProvider<EthereumTransactionParser> ethereumTransactionParserProvider;
+    private final ObjectProvider<JdbcOperations> ownerJdbcOperationsProvider;
+    private final ObjectProvider<TransactionOperations> transactionOperationsProvider;
```
Comment (xin-hedera) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: check the other feedback.

we should just pass `@Owner` jdbcOperationsProvider to the parent class, and use it everywhere.

```suggestion
```

File: importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java [hunk 11]
```diff
@@ -2,42 +2,81 @@
...
+    private static final String SELECT_TRANSACTIONS_SQL = """
+            select consensus_timestamp, data, payer_account_id
+            from ethereum_transaction
+            where consensus_timestamp < :consensusTimestamp
+            order by consensus_timestamp desc
+            limit 5000
+            """;
+
+    private static final DataClassRowMapper<TransactionRow> TRANSACTION_ROW_MAPPER =
+            new DataClassRowMapper<>(TransactionRow.class);
```
Comment (steven-sheehy) [inline importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: Might need to be BeanPropertyRowMapper for graal. Check with Jesse.

Comment (jnels124) [reply importer/src/main/java/org/hiero/mirror/importer/migration/ConvertEthereumTransactionToWeiBarMigration.java]: yes this will need to be a BeanPropertyRowMapper

**Review by steven-sheehy — APPROVED** [review]
